- Cargo.toml
- components/builder-admin/Cargo.toml
- components/builder-api-client/Cargo.toml
- components/builder-api/Cargo.toml
- components/builder-core/Cargo.toml
- components/builder-db/Cargo.toml
- components/builder-depot-client/Cargo.toml
- components/builder-depot/Cargo.toml
- components/builder-graph/Cargo.toml
- components/builder-http-gateway/Cargo.toml
- components/builder-jobsrv/Cargo.toml
- components/builder-originsrv/Cargo.toml
- components/builder-protocol/Cargo.toml
- components/builder-router/Cargo.toml
- components/builder-sessionsrv/Cargo.toml
- components/builder-worker/Cargo.toml
- components/op/Cargo.toml
> Update deps to be git refs instead of paths

- .envrc
- .gitignore
> add envrc back from migration

- components/builder-datastore/hooks/run
- components/builder-datastore/plan.sh
> chmod postgres data dir on startup

- .gitignore
- .secrets/habitat-env.sample
- .studiorc
- DEVELOPING.md
> Make habitat-env mandatory

- .secrets/habitat-env.sample
- .studiorc
- support/builder/config.sh
> Update link for github app button in dev env

- components/op/README.md
- components/op/habitat/plan.sh
> Add habitat plan to op tool

- terraform/instances.tf
Note that this is intended to be a short to medium term fix around the
core issue that networking should be setup at instance boot time, not
after the instance has been booted and set up for service. See the
`TODO` comment for more detail.
> [tf/builder-worker] Stop worker before setting up network interface.

- .studiorc
- Dockerfile
- builder/plan.sh
- components/airlock/plan.sh
- components/builder-api-proxy/plan.sh
- components/builder-api/doc/api.raml
- components/builder-api/habitat/plan.sh
- components/builder-datastore/plan.sh
- components/builder-graph/habitat/plan.sh
- components/builder-jobsrv/habitat/plan.sh
- components/builder-originsrv/habitat/plan.sh
- components/builder-router/habitat/plan.sh
- components/builder-sessionsrv/habitat/plan.sh
- components/builder-worker/habitat/plan.sh
- support/builder/init-datastore.sh
- terraform/instances.tf
- terraform/scripts/create_bootstrap_bundle.sh
- terraform/scripts/install_base_packages.sh
> Rename core/builder-* habitat/builder-*

- components/builder-worker/src/runner/mod.rs
More error handling cleanup for builder worker - we will spit out more logging in each phase, and include more explanatory error messages.
> More error handling/log cleanup

- components/builder-protocol/protocols/originsrv.proto
- components/builder-protocol/src/message/originsrv.rs
> added new proto defs for origin encryption keys

- DEVELOPING.md
Noticed these while running through the development environment setup.
> Fix environment variable names

- DEVELOPING.md
> Add dev environment notes about VM options

- components/builder-depot/src/server.rs
> Add api endpoint to fetch latest origin public encryption key

- Cargo.lock
- components/builder-core/src/integrations.rs
- components/builder-depot/src/server.rs
- components/builder-worker/habitat/plan.sh
Blocked by: https://github.com/habitat-sh/core/pull/8
> Update calls to crypto keys library for core changes

- Cargo.lock
- components/builder-api/doc/api.raml
- components/builder-api/src/github.rs
- components/builder-api/src/server/mod.rs
- test/builder-api/src/ext.js
DO NOT MERGE until after https://github.com/habitat-sh/habitat/pull/4700 merges and the `Cargo.lock` dependency is bumped!
> Remove dead code

- components/builder-api/src/github.rs
- components/builder-api/src/server/handlers.rs
- components/builder-sessionsrv/src/server/handlers.rs
- components/builder-worker/src/vcs.rs
To help track down our Github API rate limiting issues, this PR adds additional logging around webhook processing and Github App token generation, which should hopefully shed some light on what our heaviest authenticated requests are.
> Instrument (some) GitHub interactions

- components/builder-api-proxy/default.toml
> Set access tokens flag to true by default

- .travis.yml
Forgot this when I moved the code over... oops
> Add github-api-client to Travis CI config

- components/builder-web/app/app.module.ts
- components/builder-web/app/app.scss
- components/builder-web/app/side-nav/side-nav.component.html
- components/builder-web/app/side-nav/side-nav.component.spec.ts
- components/builder-web/app/statuspage/_statuspage-indicator.component.scss
- components/builder-web/app/statuspage/statuspage-indicator.component.ts
- components/builder-web/index.html
References https://github.com/habitat-sh/habitat/issues/4699
Signed-off-by: Garrett Amini <kadjar@gmail.com>
> #4699 - adding statuspage component

- components/builder-worker/habitat/plan.sh
> pin docker deps for now to unblock prod

- Cargo.lock
- appveyor.yml
- components/builder-api/Cargo.toml
- components/github-api-client/Cargo.toml
This has moved to habitat-sh/core
See https://github.com/habitat-sh/habitat/issues/4726 and https://github.com/habitat-sh/core/pull/14
> Use http-client from core

- components/builder-core/src/access_token.rs
- components/builder-core/src/integrations.rs
Tweak builder token validation.
> Tweak builder

- CODEOWNERS
> Adding myself to the codeowners file

- CODEOWNERS
> Adjusting my CODEOWNERS entries

- components/builder-web/app/actions/users.ts
This action appears to have been lost in a recent rebase.
> Restore loadOAuthState

- CODEOWNERS
> Add myself to more stuff

- components/builder-worker/habitat/default.toml
Minor tweak to remove un-needed configs from worker
> Minor config cleanup for builder worker

- .studiorc
Update dev env script to correctly upload the builder key if it already exists.
> Upload builder key if it already exists

- components/builder-worker/habitat/plan.sh
> Add correct protobuf dep to Habitat package for worker

- components/builder-sessionsrv/habitat/plan.sh
> fix protobuf in sessionsrv

- support/ci/compile_libsodium.sh
- support/ci/rust_env.sh
Fix Travis by porting over this change : https://github.com/habitat-sh/habitat/commit/be0da26fa4f688c84b2be02d6695fda92add5963
> Update libsodium to fix travis breakage

- components/builder-web/app/oauth-providers/index.ts
Fixes https://github.com/habitat-sh/habitat/issues/4959#issuecomment-382451778
> Fix Bitbucket casing

- components/builder-web/npm-shrinkwrap.json
Signed-off-by: Garrett Amini <kadjar@gmail.com>
https://github.com/habitat-sh/builder/issues/399
> #399 Manually bumping hoek in shrinkwrap

- components/builder-jobsrv/src/server/handlers.rs
Update job audit code to not write entry if a build is not actually issued (eg, for uploads that don't result in any builds being issued).
> Don't add audit entry for non-build

- components/builder-jobsrv/src/server/worker_manager.rs
This fixes a missed case in the job cancelation logic - when a job cancels due to timeout, but the worker continues to run (eg, if it is in an operation that takes a while to cancel), then the job would continue to get attempt cancelation on every heartbeat, resulting in large number of status messages for the cancel operation.
> Fix duplicate job cancels on job timeout

- components/builder-graph/habitat/plan.sh
Fix the Habitat build for builder-graph tool
> Fix builder-graph build

- components/builder-web/app/banner/banner.component.html
- components/builder-web/app/banner/banner.component.ts
https://github.com/habitat-sh/builder/issues/430
Signed-off-by: Garrett Amini <kadjar@gmail.com>
> Updating banner for on-prem announcement

- components/builder-depot/src/upstream.rs
This fixes some issues with the upstream handling:
1. The package version comparison between local and remote was incorrect if the local package that triggered the check was an older version
2. Packages could get downloaded multiple times when triggered with a non-qualified ident
3. The logging could incorrectly log an update in some cases where the download did not actually occur
> Bug fixes for upstream handling

- components/builder-depot/src/server.rs
> Allow overriding target during download as well

- DEVELOPING.md
- support/builder/config.sh
Adds an upstream config to the default dev environment
> Add upstream to default dev config

- components/builder-jobsrv/src/server/handlers.rs
This is a small change to filter out un-connected plans when scheduling group jobs.  Currently we filter out un-connected plans later when the jobs are getting dispatched, and it can create a situation where we have a large set of un-connected and un-dispatchable projects in the build queue. 
> Filter out non-connected plans early

- components/builder-depot/src/server.rs
- components/builder-depot/src/upstream.rs
- components/builder-protocol/protocols/originsrv.proto
- components/libbuild-protocols.rs
There is also a companion PR that updates the builder depot client, https://github.com/habitat-sh/habitat/pull/5154
> Enable syncing of windows packages

- Cargo.lock
> Update habitat repo ref

- .studiorc
Some tweaks to dev env script:
1. Don't use explicit port when talking to builder API
2. Remove code (such as project creation helper) that is un-used/obsolete
> Dev env tweaks

- support/builder/s3migrate.sh
> Corrects botched copy paste

- components/builder-web/app/banner/banner.component.html
> Run base plans refresh banner

- components/builder-minio/habitat/default.toml
- components/builder-minio/habitat/hooks/init
- components/builder-minio/habitat/hooks/run
> Adds support for SSL with signed certificates to Builder-Minio package

- components/builder-depot/src/backend/s3.rs
- components/builder-depot/src/metrics.rs
> Corrects upload metrics adds more info logging on upload requests

- components/builder-api/src/config.rs
> Corrects API backend test

- Makefile
See https://github.com/habitat-sh/builder/pull/441
> Remove unused makefile targets that reference removed VERSION file

- components/builder-db/tests/db/start.sh
> Fix the shebang line in init-datastore.sh

- components/builder-depot/src/server.rs
> Bubbles up download failures from s3

- components/builder-depot/src/backend/s3.rs
- components/builder-depot/src/lib.rs
- components/builder-depot/src/server.rs
A bit more error logging to pin down download failures..
> More error logging

- .gitignore
- components/builder-depot/src/backend/s3.rs
- components/builder-depot/src/lib.rs
- components/builder-depot/src/server.rs
Signed-off-by: Ian Henry ihenry@chef.io
> Use tmpfile for s3 transitional caching

- components/builder-worker/src/runner/studio.rs
Without a `HAB_STUDIO_SECRET_` prefix, the feature flag toggle gets
used outside the studio, but not _inside_, which is where we really
need it.
This is a filthy hack until
https://github.com/habitat-sh/habitat/issues/5274 happens.
> Allow HAB_FEAT_IGNORE_LOCAL to get into the worker studio

- .travis.yml
> Update Rust to 1.27.0

- components/builder-api/src/server/handlers.rs
- components/builder-depot/src/backend/s3.rs
- components/builder-depot/src/server.rs
- components/builder-http-gateway/src/http/helpers.rs
- components/builder-jobsrv/src/server/worker_manager.rs
- components/builder-worker/src/runner/studio.rs
> Update to the latest rustfmt for rust 1.27.0

- components/builder-api-proxy/habitat/config/nginx.conf
- components/builder-api-proxy/habitat/default.toml
More updates for rate limiting, including different settings for known vs unknown (eg, bot) user agents.
> More updates for rate limits

- Cargo.lock
> [core] Add new PackageTarget from habitat-sh/core#42.

- components/builder-api-proxy/habitat/config/nginx.conf
> Corrects typo in  Nginx config

- components/builder-depot/src/server.rs
- components/builder-depot/src/upstream.rs
This change fixes a missing call to minio upload when the upstream syncs down a package. This causes the package metadata to get created, but the package artifact itself is missing from mino.  Resolves https://github.com/habitat-sh/builder/issues/562
> Fix missing minio upload for upstream downloads

- CODEOWNERS
Yeah... I guess it's time to start owning some shit seein' as how I'm the only team member that doesn't currently. This seems as good a place as any to start.
> Add myself to the dang Codeowners file

- .travis.yml
- components/airlock/src/namespace.rs
- components/builder-api/src/backend/s3.rs
- components/builder-api/src/depot/server.rs
- components/builder-core/src/job.rs
- components/builder-core/src/logger.rs
- components/builder-core/src/package_graph.rs
- components/builder-db/src/async.rs
- components/builder-graph/src/data_store.rs
- components/builder-http-gateway/src/http/middleware.rs
- components/builder-jobsrv/src/data_store.rs
- components/builder-jobsrv/src/server/scheduler.rs
- components/builder-jobsrv/src/server/worker_manager.rs
- components/builder-jobsrv/tests/data_store/mod.rs
- components/builder-originsrv/src/data_store.rs
- components/builder-originsrv/tests/data_store/mod.rs
- components/builder-protocol/src/jobsrv.rs
- components/builder-protocol/src/originsrv.rs
- components/builder-sessionsrv/src/data_store.rs
- components/builder-sessionsrv/tests/data_store/mod.rs
- components/builder-worker/src/network.rs
- components/builder-worker/src/runner/job_streamer.rs
- components/builder-worker/src/runner/studio.rs
- components/builder-worker/src/runner/util.rs
- components/builder-worker/src/server.rs
- components/builder-worker/src/vcs.rs
- components/oauth-client/src/client.rs
- components/oauth-client/src/lib.rs
https://blog.rust-lang.org/2018/08/02/Rust-1.28.html
> [ci,rustfmt] Formatting due to rustfmt 0.8.2 in Rust 1.28.0.

- components/builder-api/src/depot/server.rs
> Adds support for force uploading packages

- components/builder-api/src/upstream.rs
1-liner fix to update an incorrect log message
> Fix upstream log

- DEVELOPING.md
Fixing an old link.
Signed-off-by: Garrett Amini <kadjar@gmail.com>
> habitat -> builder

- tools/merge-shards/merge-shards.sh
These changes have already been tested as part of the shard migration in acceptance.
> Fix migration script to work with prod data

- DEVELOPING.md
> Add notes on merging shards

- terraform/templates/hab-sup.service
> Stop hab-sup gracefully instead of just killing it

- terraform/files/postgres.yaml
> Shards went away, so this isn't needed

- terraform/instances.tf
Updating the datastore instance size in Terraform
> Upgrade datastore instance size

- components/net/src/conn/mod.rs
> Up the timeout and add better error messaging

- components/builder-db/src/migration.rs
We now check to see if there are any `shard_` schemas in the database, and if not, we can assume this is a fresh database - so don't abort.
Closes https://github.com/habitat-sh/builder/issues/596
> Don't abort for brand new databases

- components/builder-api/src/server/resources/channels.rs
> Adds channel support with actix-web

- CODEOWNERS
Signed-off-by: Liz Chen <apriofrost@gmail.com>
> add Liz as codeowner of CLI UX related files

- .travis.yml
Updating travis.yml to reflect the deletion of a couple of builder components
> Remove deleted components from travis.yml

- components/builder-api-proxy/habitat/config/nginx.conf
> Adds round robin to api-proxy to prevent dead member binding

- tools/merge-databases/merge-databases.sh
> minor fix to merge_databases script

- components/builder-graph/README.md
- components/builder-graph/src/config.rs
- components/builder-graph/src/data_store.rs
- components/builder-jobsrv/src/config.rs
- components/builder-jobsrv/src/migrations/2018-08-29-173340_initial_jobsrv_migration/down.sql
- components/builder-originsrv/src/config.rs
- components/builder-sessionsrv/src/migrations/2018-08-24-193407_initial_sessionsrv_migration/down.sql
- support/db/start.sh
- terraform/files/postgres.yaml
- test/builder-api/bin/cleanup-integration-tests.sh
- test/builder-api/test.sh
This is to cleanup some of the oversights from the database merge
> Clean up tests around old database names

- components/builder-api/src/server/error.rs
- components/builder-api/src/server/resources/notify.rs
- components/builder-api/src/server/services/github.rs
Minor refactor / update for the github push handling to help diagnose/resolve failures in acceptance.
> Updates for github push

- components/builder-api-proxy/habitat/config/nginx.conf
> Always proxy pass, regardless of caching

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/services/github.rs
- components/builder-api/src/server/services/s3.rs
Tweak some warning/error messages to add more data
> Tweak warnings with added info

- components/builder-api-proxy/habitat/config/nginx.conf
> Fix typo in nginx conf

- components/builder-core/src/metrics.rs
Remove a verbose and unneeded debug msg
> Remove unneeded debug msg

- .travis.yml
- components/airlock/src/namespace.rs
- components/airlock/src/pty.rs
- components/builder-api/src/server/mod.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/origins.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/resources/profile.rs
- components/builder-api/src/server/resources/projects.rs
- components/builder-api/src/server/services/s3.rs
- components/builder-api/src/server/services/upstream.rs
- components/builder-core/src/job.rs
- components/builder-db/src/migration.rs
- components/builder-graph/src/main.rs
- components/builder-jobsrv/src/data_store.rs
- components/builder-jobsrv/src/server/log_archiver/s3.rs
- components/builder-jobsrv/src/server/log_ingester.rs
- components/builder-jobsrv/src/server/scheduler.rs
- components/builder-jobsrv/src/server/worker_manager.rs
- components/builder-originsrv/src/data_store.rs
- components/builder-protocol/src/jobsrv.rs
- components/builder-protocol/src/originsrv.rs
- components/builder-worker/src/heartbeat.rs
- components/builder-worker/src/log_forwarder.rs
- components/builder-worker/src/runner/mod.rs
- support/ci/compile_libsodium.sh
https://blog.rust-lang.org/2018/09/13/Rust-1.29.html
> [ci,rustfmt] Formatting due to rustfmt 0.99.1-stable in Rust 1.29.0.

- terraform/instances.tf
Update the originsrv instance size in terraform
> Update originsrv instance size

- MAINTAINERS.md
Signed-off-by: Matthew Peck <mpeck@chef.io>
> add myself to project maintainers

- .studiorc
- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-api/habitat/config/config.toml
- components/builder-api/habitat/default.toml
- components/builder-api/habitat/plan.sh
- components/builder-api/src/config.rs
- components/builder-api/src/lib.rs
- components/builder-api/src/server/framework/middleware.rs
- components/builder-api/src/server/mod.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/services/memcache.rs
- components/builder-api/src/server/services/mod.rs
- components/builder-memcached/default.toml
- components/builder-memcached/hooks/run
- components/builder-memcached/plan.sh
- components/builder-protocol/src/originsrv.rs
This adds a memcache service to builder and bakes memcache support into the builder API.
> Add memcached to builder for latest channel calls.

- terraform/instances.tf
> Add terraform config to setup memcached

- components/builder-api/src/server/schema/project.rs
- components/builder-api/src/server/schema/project_integration.rs
> Adds more schemas for originsrv merge

- components/builder-api/src/server/framework/middleware.rs
> bypass db check for builder token

- .studiorc
- components/builder-api/src/config.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/services/github.rs
- components/builder-originsrv/src/server/handlers.rs
A few misc cleanups - update a few error messages to be more appropriate for their context (suppress needless noise in prod), add a test for memcache config, and update memcached behavior in .studiorc for the dev env.
> Misc err cleanup etc

- .bldr.toml
- components/builder-memcached/plan.sh
- components/builder-minio/habitat/plan.sh
- components/builder-originsrv/src/server/handlers.rs
More small cleanup - update bldr.toml to reflect latest changes, add core/git to build deps for minio and memcached, convert an error to debug.
> More small cleanup

- components/builder-api/src/server/db.rs
- components/builder-api/src/server/handlers/channel.rs
- components/builder-api/src/server/mod.rs
- components/builder-api/src/server/models/channel.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-originsrv/src/migrations/2018-09-26-359845_origin_channel_functions/up.sql
> Make channels delete operation pull from the db

- components/builder-api/src/server/handlers/channel.rs
- components/builder-api/src/server/models/channel.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-originsrv/src/migrations/2018-09-27-854186_origin_channel_create/up.sql
> Move create channel function to directdb call

- components/builder-web/app/origin/origin-page/origin-members-tab/origin-members-tab.component.html
Signed-off-by: Shaun Mouton <smouton@chef.io>
> a simple spelling fix

- components/builder-api/src/server/handlers/channel.rs
- test/builder-api/src/channels.js
> Return 409 on conflict creating channels

- DEVELOPING.md
Add some info re: builder metrics to the developing doc
> Update developing doc with info on statsd metrics

- tools/hab_token/Usage.md
- tools/hab_token/hab-token
Helper script for managing multiple hab tokens (eg, for dev/acceptance/prod envs)
> Add hab token helper script

- DEVELOPING.md
This adds a few clarifying details, along with a section on how to prepare an empty depot to run local builds.
> Clarify some details for setting up Builder dev

- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-api/src/lib.rs
- components/builder-api/src/server/db.rs
- components/builder-api/src/server/error.rs
- components/builder-api/src/server/framework/middleware.rs
- components/builder-api/src/server/mod.rs
- components/builder-api/src/server/models/account.rs
- components/builder-api/src/server/services/memcache.rs
- components/builder-protocol/src/originsrv.rs
Woo doggies. This was a massive miserable bag of spaghetti snakes. This is a major simplification and @elliott-davis wrote like 99% of this PR.
>  Sessionsrv migration to api

- components/builder-api/habitat/hooks/run
- components/builder-datastore/hooks/run
- components/builder-jobsrv/habitat/hooks/run
- components/builder-originsrv/habitat/hooks/run
- components/builder-router/habitat/hooks/run
- components/builder-worker/habitat/hooks/run
> More service startup events

- components/builder-jobsrv/src/data_store.rs
- components/builder-jobsrv/src/server/handlers.rs
- components/builder-jobsrv/src/server/mod.rs
- components/builder-protocol/protocols/jobsrv.proto
- components/builder-protocol/src/jobsrv.rs
Removing some dead code from jobsrv
> Remove some dead code in jobsrv

- components/builder-api/habitat/hooks/run
- components/builder-datastore/hooks/run
- components/builder-jobsrv/habitat/hooks/run
- components/builder-originsrv/habitat/hooks/run
- components/builder-router/habitat/hooks/run
- components/builder-worker/habitat/hooks/run
> Fix shellcheck breakage

- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-api/src/lib.rs
- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/models/channel.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/schema/audit.rs
- components/builder-api/src/server/schema/mod.rs
- components/builder-originsrv/src/migrations/2018-10-09-192420_origin_package_channels/up.sql
> finish promote/demote with audit

- .travis.yml
https://blog.rust-lang.org/2018/10/12/Rust-1.29.2.html
> [ci] Update to Rust 1.29.2.

- DEVELOPING.md
Add a brief note re: package synchronization to the developer README
> Add brief note regarding syncing packages to DEVELOPING.md

- .studiorc
> Adds helper for executing functional tests in builder devenv

- components/builder-db/src/models/package.rs
- components/builder-db/src/schema/package.rs
- components/builder-jobsrv/src/data_store.rs
- components/builder-originsrv/src/data_store.rs
- components/builder-originsrv/src/migrations/2018-10-10-198563_enum_visibility/up.sql
> smallint doesn't work for port numbers

- .studiorc
- components/builder-datastore/plan.sh
Minor tweak to .studiorc - resolves https://github.com/habitat-sh/builder/issues/139
> Start supervisor if not started already when building

- components/builder-api/src/server/resources/pkgs.rs
If we get a fully qualified ident we shouldn't use the latest function to query the db.
Instead, we should use the exact match function from the database.
> Ignore target info when package ident is fully qualified

- components/builder-db/src/models/package.rs
- components/builder-originsrv/src/data_store.rs
- components/builder-originsrv/src/migrations/2018-10-23-111111_ident_matching/up.sql
> Fix ident searching by searching ident array instead of using LIKE query

- .bldr.toml
> Adds builder-db as a build dep on builder-api

- components/builder-api/src/server/resources/channels.rs
- components/builder-db/src/models/channel.rs
- components/builder-originsrv/src/migrations/2018-10-25-111222_channel_latest/up.sql
- components/builder-protocol/src/originsrv.rs
> Make latest channel package call a direct-db call from the API

- components/builder-api/src/server/resources/origins.rs
- components/builder-db/src/models/keys.rs
Converts signing keys to direct DB
> Convert signing keys to direct DB

- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-api/src/lib.rs
- components/builder-api/src/server/resources/profile.rs
- components/builder-api/src/server/services/memcache.rs
> Hash session tokens to prevent some OAuth tokens from being too long for memcache to handle

- components/builder-api/src/server/resources/channels.rs
- components/builder-db/src/models/channel.rs
- components/builder-db/src/models/package.rs
- components/builder-db/src/schema/channel.rs
- test/builder-api/src/channels.js
> Convert Package Channel List to call the db directly

- components/builder-api/src/server/resources/profile.rs
- components/builder-db/src/models/account.rs
- test/builder-api/src/profile.js
Fix breakage in access tokens, and add some e2e tests for the functionality.
> Fix access token breakage

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-db/src/models/package.rs
> Convert package downloads to direct-db

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-db/src/models/channel.rs
- components/builder-db/src/models/package.rs
- components/builder-db/src/schema/package.rs
> Convert list package versions to direct db

- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/resources/projects.rs
A few more channel conversions - move channels_for_package_ident out of helpers.
> More channel related conversions

- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-db/src/models/channel.rs
More jobs related conversions to direct DB
> More jobs related conversion

- components/builder-api/src/server/resources/origins.rs
- components/builder-db/src/models/package.rs
> Convert list_unique_packages to directdb

- components/builder-db/src/models/package.rs
> Make package search correctly search public packages

- components/builder-db/src/metrics.rs
> Add missed metrics file

- components/builder-db/src/migrations/2108-11-03-111111_search_index/up.sql
> Add index on full text search vector

- .travis.yml
- components/builder-api/src/server/services/github.rs
https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html
> Bump to rust 1.30.0

- components/builder-db/src/migrations/2018-11-06-111111_origins_with_stats/up.sql
> fix bad group by in view for package counts for origin

- components/builder-db/src/migrations/2018-11-06-111111_origins_with_stats/up.sql
- components/builder-db/src/models/package.rs
> Fix package counting and sorting bugs

- components/builder-api/src/server/resources/channels.rs
> Fix missing call to expire cache on package promote

- components/builder-api/src/server/resources/origins.rs
- components/builder-db/src/models/secrets.rs
Fix hab origin secret list breakage
> Fix struct for origin secrets list

- components/builder-api/src/server/resources/projects.rs
- components/builder-db/src/models/mod.rs
- components/builder-db/src/models/projects.rs
- components/builder-db/src/schema/project.rs
> Make VCS installation id optional

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-db/src/models/package.rs
> tweak target handling when fetching packages

- components/builder-api/src/server/resources/projects.rs
This improves the perf for the get jobs API by removing the fan out for retrieving channels/platforms as those are not being used.
> Remove channels/platform fan-out from get jobs API

- components/builder-api/src/server/services/memcache.rs
- components/oauth-client/src/client.rs
- components/segment-api-client/src/client.rs
Minor tweak to move some debug statements to trace
> Update some debug statements

- components/builder-api/src/server/framework/middleware.rs
> Increases session length to 72 hours

- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-db/src/diesel_pool.rs
- components/builder-db/src/pool.rs
Minor update to re-use a db connection in the high volume channel package api
> Reuse connection for channels call

- .envrc
- .studiorc
- DEVELOPING.md
- components/builder-web/README.md
- terraform/templates/hab-sup.service
This PR updates the Builder development documentation to clean up, simplify and tighten the steps that are required in order to configure the environment. It also updates the Web development readme that was significantly out of date.
Also there are a couple of small bug fixes/changes to the env scripts.
> Update Builder dev doc / scripts

- components/airlock/src/command/netns/create.rs
- components/airlock/src/command/netns/createinns.rs
- components/airlock/src/command/nsrun.rs
- components/airlock/src/command/run.rs
- components/airlock/src/coreutils.rs
- components/airlock/src/main.rs
- components/airlock/src/mount.rs
- components/airlock/src/namespace.rs
- components/airlock/src/pty.rs
- components/airlock/src/user.rs
- components/airlock/src/util.rs
Fix some missed clippy warnings in the airlock component.
> Fixed some missed clippy warnings

- .travis.yml
- components/builder-protocol/src/message/mod.rs
Update Travis yml - install non-preview rustfmt and add clippy check
> Add Clippy lint job to travis.yml

- components/builder-api/src/server/resources/authenticate.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/ext.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/origins.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/resources/profile.rs
- components/builder-api/src/server/resources/projects.rs
- components/builder-api/src/server/resources/user.rs
- components/builder-api/src/server/services/github.rs
- components/builder-worker/src/vcs.rs
- test/builder-api/package.json
- test/builder-api/test.sh
Add / clean up debug output for error conditions in the builder API routes.
> Add more debug logging to API routes

- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/services/memcache.rs
This change adds caching for 404 (Not Found) latest package calls. Since the uncached latest package call is expensive, this change can prevent inadvertent DOS of the builder service.
> Add 404 caching for latest package calls

- components/builder-api-proxy/habitat/config/nginx.conf
- components/builder-api/src/main.rs
- components/builder-jobsrv/src/main.rs
- components/builder-worker/src/main.rs
I'm not sure on this, but looks like a minor bug. Its better to re-test this commit.
> Minor fixes

- components/builder-api/src/server/services/memcache.rs
Minor error handling update in the memcache client
> Update memcache error handling

- Cargo.lock
> update cargo deps

- .envrc
- components/builder-core/src/integrations.rs
- test/builder-api/test.sh
Update to test.sh to help diagnose Travis err.  Also update .envrc
> Update test script

- components/builder-db/src/models/jobs.rs
- components/builder-db/src/schema/jobs.rs
Update the Jobs schema/model to account for nullable data
> Fix jobs vcs data type

- CODEOWNERS
> Remove Garrett Amini from CODEOWNERS

- Cargo.lock
> update cargo locks

- components/builder-datastore/hooks/init
> refactor code to avoid shellcheck warning

- CODEOWNERS
Update codeowners to add myself to some files
> Update codeowners to add myself to files

- Cargo.lock
> Update Cargo.lock for 0.73.0

- components/builder-api/src/server/services/github.rs
Fixes a bug where we are not checking for job server enablement when kicking off a webhook build.
> Check for jobsrv enabled when kicking off webhook build

- components/builder-api/src/server/resources/jobs.rs
- components/builder-worker/src/runner/mod.rs
A couple of bug fixes in builder-api and builder-worker
> A couple of bug fixes

- components/builder-worker/src/runner/docker.rs
- components/builder-worker/src/runner/mod.rs
- components/builder-worker/src/runner/studio.rs
- components/builder-worker/src/server.rs
Some updates to environment handling for Windows builder worker
> Tweak builder-worker for Windows builds

- .travis.yml
- components/airlock/src/namespace.rs
- components/airlock/src/pty.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/origins.rs
- components/builder-core/src/job.rs
- components/builder-jobsrv/src/server/scheduler.rs
- components/builder-protocol/src/message/mod.rs
- components/builder-worker/src/runner/util.rs
> Rust 1.32.0

- components/builder-web/app/shared/job-notice/job-notice.component.html
- components/builder-web/package-lock.json
Both [UI-150](https://chefio.atlassian.net/secure/RapidBoard.jspa?rapidView=261&projectKey=UI&modal=detail&selectedIssue=UI-150) & part of #819 
- Link within `job-notice.component` now routes to` /#/origins/{job.origins}/jobs/{job.owner_id} `
extra: package.json seems to be out of sync for items removed from builder-ui. Nothing is added - I think this PR might be small enough to fix it here, but happy to move to another PR if not.
> "view more" link correctly routes to new origin jobs page

- components/builder-web/app/banner/banner.component.html
> Revert banner to pre-refresh message

- MAINTAINERS.md
- maintenance-policy.md
Long overdue cleanup, clarification and sane updates to the maintainers list and policy for Builder. 
Speak now or forever hold your peace.
> Update Maintainers and maintenance policy

- terraform/templates/windows_worker_user_data
Small change to set the target for the Windows worker when Terraforming
> Terraform: Add target to Windows worker user.toml

- terraform/instances.tf
- terraform/variables.tf
Small update to add new instance sizing variables for Terraform
> Add new instance sizing variables to Terraform

- Cargo.lock
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/services/memcache.rs
- components/builder-core/src/api_client.rs
- components/builder-core/src/build_config.rs
- components/builder-db/src/models/channel.rs
- components/builder-db/src/models/jobs.rs
- components/builder-db/src/models/origin.rs
- components/builder-db/src/models/package.rs
- components/builder-jobsrv/src/server/scheduler.rs
- components/builder-worker/src/config.rs
- components/builder-worker/src/runner/postprocessor.rs
- components/builder-worker/src/runner/publisher.rs
- components/builder-worker/src/runner/studio.rs
- components/builder-worker/src/runner/toml_builder.rs
See https://github.com/habitat-sh/core/pull/107
> Replace Strings and &strs with type-safe habitat_core::ChannelIdent type

- Cargo.lock
See https://github.com/habitat-sh/core/pull/118
> Cargo update for core 118

- Cargo.lock
- components/builder-api/src/server/resources/origins.rs
- components/builder-core/src/access_token.rs
- components/builder-core/src/integrations.rs
- components/builder-jobsrv/src/server/worker_manager.rs
https://github.com/habitat-sh/core/pull/115 has merged, so this can merge once CI passes
> Fix BoxKeyPair::encrypt return type

- components/builder-jobsrv/src/data_store.rs
- components/builder-protocol/src/jobsrv.rs
- components/builder-worker/src/server.rs
> Expose target in bldr job status

- terraform/scripts/install_linux2_packages.sh
Update Terraform for Linux2 builder-worker. This change removes un-needed packages and adds in Docker.
> Update terraform for Linux2 worker

- .travis.yml
- components/builder-api/src/server/framework/middleware.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-graph/src/main.rs
> Update to rust 1.33.0

- terraform/instances.tf
> Update firewall rules for Linux2 instance

- terraform/instances.tf
> Update Linux2 firewall

- components/airlock/README.md
> Add Airlock README usage docs.

- components/builder-db/src/models/jobs.rs
- components/builder-jobsrv/src/server/scheduler.rs
Add target awareness to queued job processing - this also helps resolve a case where jobs can get stuck behind other jobs for a different target.
> Use target when processing queued jobs

- components/builder-api/src/server/resources/pkgs.rs
Currently force uploading a package can fail if the metadata already exists but the artifact does not. This fixes the case by accounting for the metadata conflict (on conflict do nothing) case.
> Fix force upload by handling error on DB conflict

- components/builder-core/src/logger.rs
- terraform/templates/sch_log_parser.py
This change updates the job server logging to include target information. The Datadog dashboard log parsing module is also updated appropriately.
> Update job logging to include job target

- Cargo.lock
See https://github.com/habitat-sh/habitat/issues/6284
> Cargo update following release 0.78.0

- components/builder-worker/src/runner/mod.rs
Slight tweak of the build worker container cleanup to address some cases where the named container still exists when the job starts.
> Better clean up of job container

- terraform/load-balancers.tf
Minor tweak to ELB idle timeout setting. This is a change to help with large file uploads.
> Tweak ELB idle timeout

- .expeditor/config.yml
I'm assuming this is the minimal Expeditor config?
> Add Expeditor so we get DCO checks

- components/builder-api/src/server/resources/pkgs.rs
Minor tweak to enable file uploads to succeed for Mac OX packages
> Fix upload to not fail when graph not found

- components/builder-web/app/package/package-versions/package-versions.component.html
- components/builder-web/app/package/package-versions/package-versions.component.ts
One more UI update to make targets work in the versions tab
> Tweak target for package versions

- .bldr.toml
> Some bldr.toml cleanup

- .studiorc
- components/builder-api-proxy/habitat-dev/plan.sh
- components/builder-api-proxy/habitat/plan.sh
- components/builder-datastore/plan.sh
- support/bash_completion.sh
- support/builder/s3migrate.sh
- support/ci/builder-base-plan.sh
- support/ci/fast_pass.sh
- support/ci/rustfmt.sh
- support/ci/shared.sh
- terraform/scripts/create_bootstrap_bundle.sh
Update toolchain to nightly-2019-04-09
There were no changes when running `cargo +nightly-2019-04-09 fmt`
> rustfmt update post 0.79.0 release

- components/builder-api/src/server/resources/jobs.rs
This change fixes https://github.com/habitat-sh/builder/issues/1020 by propagating the group target to the promote/demote operations.
> Fix job group promotion/demotion

- components/builder-api/habitat/default.toml
- components/builder-api/src/config.rs
Update to add section in default.toml for Artifactory, as well as a test for the config
> Add default toml and test for artifactory config

- Cargo.lock
- components/artifactory-client/Cargo.toml
- components/builder-api/Cargo.toml
- components/builder-core/Cargo.toml
- components/builder-db/Cargo.toml
- components/builder-graph/Cargo.toml
- components/builder-jobsrv/Cargo.toml
- components/builder-protocol/Cargo.toml
- components/builder-worker/Cargo.toml
> Update builder to use core in the habitat repo

- components/builder-db/src/migrations/2019-04-19_867530_build_dep_defaults/up.sql
> Corrects database in preparation for build_dep migration

- components/builder-api/src/server/resources/origins.rs
Bump up the visibility of errors during key creation in order to help debug behavior described in https://github.com/habitat-sh/builder/issues/1033
> More error visibility for key creation

- components/builder-db/src/models/package.rs
> Allows subset of package metadata into database on force upload

- components/artifactory-client/src/client.rs
Some updates to artifactory client error handling
> Improve Artifactory client error handling

- components/builder-jobsrv/habitat/config/config.toml
> Corrects features_enabled template in hab package

- terraform/scripts/create_bootstrap_bundle.sh
> Fixes bombing shellcheck in travis CI

- terraform/scripts/install_base_packages.sh
- terraform/scripts/install_linux2_packages.sh
- terraform/templates/windows_worker_user_data
This adds license acceptance to the Habitat Terraform scripts
> Add license acceptance to Terraform

- .expeditor/verify.pipeline.yml
- support/ci/rustfmt.sh
- support/ci/shared.sh
- test/denied_lints.txt
- test/run_cargo_test.sh
- test/run_clippy.sh
This does not include the integration tests, which should be added in a followup PR.
> Migrate verification tests to buildkite

- support/ci/shared.sh
No formatting changes were necessary.
> Update rustfmt for 0.81.0 release

- components/builder-worker/src/runner/docker.rs
- components/builder-worker/src/server.rs
> Fix Windows clippy errors

- components/builder-worker/src/runner/docker.rs
> Swap internal docker daemon spawning for reliance on host daemon

- terraform/instances.tf
> Adds license acceptance to worker instances

- terraform/instances.tf
Fix up Terraform missing comma
> Fix typo in Terraform instances

- support/builder/config.sh
> Support non-binding-svc workflow in local dev

- components/builder-db/src/models/package.rs
- components/builder-jobsrv/src/data_store.rs
- components/builder-jobsrv/src/server/mod.rs
> Replaces graph query with updated latest unique call

- .travis.yml
- components/builder-web/app/banner/banner.component.html
> Hide banner in builder web app

- terraform/instances.tf
- terraform/variables.tf
Update Terraform for job srv instance sizing
> Add jobsrv sizing variable

- .expeditor/verify_private.pipeline.yml
- .travis.yml
- components/builder-api/src/config.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-db/src/models/origin.rs
- components/builder-jobsrv/src/config.rs
- components/builder-jobsrv/src/server/worker_manager.rs
- components/github-api-client/src/client.rs
- test/denied_lints.txt
- test/run_clippy.ps1
> Update to Rust 1.35.0

- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-jobsrv/Cargo.toml
- components/builder-worker/src/error.rs
- components/builder-worker/src/runner/mod.rs
- components/builder-worker/src/runner/publisher.rs
- support/ci/shared.sh
Update to Nightly 2019-06-06
Pin actix-web until we are ready for 1.0.0
Updates to usage of Retry
> 0.82.0 Post-release tasks

- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-api/src/server/authorize.rs
- components/builder-api/src/server/framework/middleware.rs
- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/mod.rs
- components/builder-api/src/server/resources/authenticate.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/ext.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/notify.rs
- components/builder-api/src/server/resources/origins.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/resources/profile.rs
- components/builder-api/src/server/resources/projects.rs
- components/builder-api/src/server/resources/user.rs
- components/builder-api/src/server/services/github.rs
- components/builder-jobsrv/Cargo.toml
- components/builder-jobsrv/src/server/mod.rs
Signed-off-by: David McNeil <mcneil.david2@gmail.com>
> Upgrade actix-web to 1.0

- components/builder-jobsrv/src/error.rs
- components/builder-jobsrv/src/server/handlers.rs
- components/builder-jobsrv/src/server/scheduler.rs
- components/builder-jobsrv/src/server/worker_manager.rs
Fixes https://github.com/habitat-sh/builder/issues/1095
Make the scheduler code a bit more robust to exceptional conditions like malformed idents
> Clean up some unwraps

- test/run_cargo_test.sh
- test/run_clippy.sh
> Explicitly accept hab license now that we have new hab binary

- .expeditor/verify.pipeline.yml
> Use 2016 windows queues

- components/builder-web/app/origin/origin-create-page/origin-create-page.component.ts
- components/builder-web/app/origin/origin-page/origin-integrations-tab/origin-integrations-tab.component.ts
- components/builder-web/app/origin/origin-page/origin-job-detail/origin-job-detail.component.ts
- components/builder-web/app/origin/origin-page/origin-jobs-tab/origin-jobs-tab.component.ts
- components/builder-web/app/origin/origin-page/origin-keys-tab/origin-keys-tab.component.ts
- components/builder-web/app/origin/origin-page/origin-members-tab/origin-members-tab.component.ts
- components/builder-web/app/origin/origin-page/origin-packages-tab/origin-packages-tab.component.ts
- components/builder-web/app/origin/origin-page/origin-settings-tab/origin-settings-tab.component.ts
- components/builder-web/app/origin/origins-page/origins-page.component.spec.ts
- components/builder-web/app/origin/origins-page/origins-page.component.ts
- components/builder-web/app/package/package-job/package-job.component.ts
- components/builder-web/app/package/package-jobs/package-jobs.component.ts
- components/builder-web/app/package/package-latest/package-latest.component.spec.ts
- components/builder-web/app/package/package-latest/package-latest.component.ts
- components/builder-web/app/package/package-release/package-release.component.spec.ts
- components/builder-web/app/package/package-release/package-release.component.ts
- components/builder-web/app/package/package-settings/package-settings.component.ts
- components/builder-web/app/package/package-versions/package-versions.component.spec.ts
- components/builder-web/app/package/package-versions/package-versions.component.ts
- components/builder-web/app/profile/profile/profile.component.ts
- components/builder-web/app/search/search/search.component.spec.ts
- components/builder-web/app/search/search/search.component.ts
- components/builder-web/app/sign-in-page/sign-in-page.component.ts
Signed-off-by: Graham Weldon <graham@grahamweldon.com>
Automatically places the app.name (from Store) into templates where possible.
> Allow product name substitution in builder-web

- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/jobs.rs
- components/builder-api/src/server/resources/pkgs.rs
> Downgrade some logs to trace

- terraform/instances.tf
> add auto-update and listen flags to windows worker supervisors

- components/builder-api/src/server/resources/ext.rs
> Corrects URL handling in publishing integrations

- components/builder-worker/src/runner/docker.rs
> Corrects cmd environment for docker exports

- DEVELOPING.md
This commit adds words to developing.md about the needed static IP configuration steps.
Signed-off-by: Scott Christopherson <scott@chef.io>
> Update developing.md to include static ip info

- components/builder-api/src/server/services/github.rs
- components/builder-core/src/build_config.rs
This change makes the bldr.toml plan_path more user friendly
by adapting to formats that may not be exactly to spec - for
example, if a user specifies a plan.sh file as part of the plan
path, we can intelligently deal with it.
The change also adds improved logging and other simplifications
by removing parts of the code that are not used/supported.
Resolves https://github.com/habitat-sh/builder/issues/1140
> Improvments to GitHub web hook handling

- components/builder-api/doc/api.raml
> Adds channel {pro, de}motion api to raml docs

- components/oauth-client/src/bitbucket.rs
> Fixes oauth sign-on for bitbucket

- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/resources/channels.rs
Minor change to quiet down some un-needed debug logging, and add a bit more explanatory text in a few places.
> Quiet down some debug logging

- CODEOWNERS
> Remove baumanj from CODEOWNERS

- terraform/instances.tf
Resolves https://github.com/habitat-sh/builder/issues/1196
> Update Windows builder workers to Win 2019

- terraform/dns.tf
- terraform/instances.tf
- terraform/load-balancers.tf
- terraform/outputs.tf
- terraform/s3.tf
- terraform/security-groups.tf
- terraform/variables.tf
- terraform/versions.tf
- terraform/www.tf
Closes https://github.com/habitat-sh/builder/issues/1193
This upgrades our TF plans to be compatible with Terraform 0.12
Steps taken to produce and validate changes:
```
terraform 0.12upgrade
terraform fmt
terraform validate
```
For Acceptance and Live environments:
```
terraform plan
```
> terraform 0.12 required changes

- DEVELOPING.md
Signed-off-by: Scott Christopherson <scott@chef.io>
> Updating line about `incomingtcp` nat.conf setting

- DEVELOPING.md
We are thinking it is either this clarification note or switching the order of the doc steps
Signed-off-by: Shadae Holmes sholmes@chef.io
> Update to GuestOS Provisioning

- terraform/templates/hab-sup.init
- terraform/templates/hab-sup.service
- terraform/templates/windows_worker_user_data
See https://github.com/habitat-sh/habitat/pull/7214; this lets us dogfood the feature in our environments!
> Enable PIDS_FROM_LAUNCHER feature

- terraform/instances.tf
- terraform/variables.tf
> adding bastion host definitions

- components/builder-api/src/server/mod.rs
- components/builder-jobsrv/src/server/handlers.rs
- components/builder-jobsrv/src/server/mod.rs
- components/builder-jobsrv/src/server/scheduler.rs
This is an attempt to bypass the UI change requirement for the new package flow's backend changes
> Adds feature flag for job project selection

- .expeditor/scripts/verify/terraform_validate.sh
- .expeditor/verify.pipeline.yml
- terraform/instances.tf
- terraform/templates/hab-sup.init.tpl
- terraform/templates/hab-sup.service.tpl
- terraform/templates/windows_worker_user_data
- terraform/templates/windows_worker_user_data.tpl
- terraform/variables.tf
This started as simply ensuring that Windows workers got the new `PIDS_FROM_LAUNCHER` feature enabled, but turned into allowing us to declaratively manage which features (plural) were active at any given time.
Read the commit messages for further details.
> [terraform] Declaratively handle feature enablement

- components/builder-jobsrv/src/server/scheduler.rs
> Allow default target through job_spec

- components/builder-db/src/migrations/2019-12-05-163232_project_targets/up.sql
> Sets all project targets to linux

- components/builder-db/src/migrations/2019-12-05-163232_project_targets/up.sql
> fixes typo in db migration

- components/builder-api/src/server/resources/jobs.rs
> Wrap job log GET in legacyproject feature flag

- components/builder-api/doc/api.raml
- components/builder-api/src/server/resources/origins.rs
- components/builder-db/src/models/origin.rs
- test/builder-api/src/origins.js
> Adds new endpoint for transferring origin ownership

- CODEOWNERS
Adding myself to codeowners and removing Josh Black.
> update codeowners with recent changes

- components/builder-api/doc/api.raml
- components/builder-api/src/server/resources/origins.rs
- components/builder-db/src/models/origin.rs
- test/builder-api/src/origins.js
> Add api for departing from an origin

- .expeditor/builder_worker.pipeline.yml
- .expeditor/config.yml
This is an initial stub, just to allow Expeditor to create the
pipeline. Once that exists, we can start filling in details.
> [CI] Initial creation of builder-worker pipeline

- RELEASE.md
> [Docs] Document `habitat/builder-worker` release process

- components/builder-api/src/server/resources/origins.rs
- components/builder-db/src/migrations/2020-02-12-195406_audit_origin_table/up.sql
- components/builder-db/src/models/origin.rs
- components/builder-db/src/schema/audit.rs
Closes https://github.com/habitat-sh/builder/issues/1300
Key origin operations are logged.
> audit trail for key origin operations

- .studiorc
- DEVELOPING.md
- components/builder-api/habitat/hooks/run
- test/builder-api/test.sh
> fixes races and adds inspection functionality to studio development

- components/builder-datastore/plan.sh
> Upgrades the builder-datastore package to postgres 11

- DEVELOPING.md
If there are UI changes not yet in stable that you want to 👀, do this. 
> adding docs on how to build local UI assets in studio

- CODEOWNERS
> Add myself to Builder CODEOWNERS

- terraform/scripts/install_base_packages.sh
After we [consolidated](https://github.com/habitat-sh/builder/pull/1350) all bootstrapping into a single script, an issue emerged with `nmap` not being available for kernel2 at all.
This PR fixes this by ensuring that the package install commands only occur if the expected .hart file exists in the bootstrap bundle.  Validated that this works by tainting and rebuilding both linux and linux2 worker nodes in acceptance.
> nmap fixes in install_base_packages

- test/builder-api/src/projects.js
Pretty straightforward - adds tests to verify the new project platforms are functioning as expected.
> Adds tests for new platform project behaviors

- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/services/metrics.rs
> Adds memcache hit and miss metric tracking

- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/services/metrics.rs
> adding additional granularity to memcached pkg counters

- components/builder-db/src/migrations/2020-04-22-172800_correct_origin_members_owner_role/up.sql
- components/builder-db/src/models/origin.rs
- test/builder-api/src/origins.js
Closes https://github.com/habitat-sh/builder/issues/1398
> Corrects role data handling in origin transfer

- components/builder-api/src/server/authorize.rs
Closes https://github.com/habitat-sh/builder/issues/1402
> reducing log level to debug until all roles are fleshed out

- terraform/files/db_connect.sh
- terraform/instances.tf
- terraform/load-balancers.tf
- terraform/scripts/foundation.sh
- terraform/scripts/init_filesystem.sh
- terraform/scripts/worker_bootstrap.sh
- terraform/templates/windows_worker_user_data.tpl
- terraform/variables.tf
> prepping for AMI and instance type changes

- terraform/instances.tf
> relaxed bind mode for builder-api on jobsrv

- terraform/s3.tf
This will fix our failing CI tests.
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md
> terraform AWS module no longer supports setting region on aws_s3_bucket

- components/builder-web/app/package/package/package.component.ts
Fixes issue https://github.com/habitat-sh/builder/issues/1389 where users are redirected and can't view a public package if they are unauthenticated. The request to `/settings` is now only made for users who are authenticated origin members.
Before:
After:
> Don't request package settings if not an origin member

- terraform/instances.tf
> we want to start DD agent on the build workers

- components/builder-api/src/server/resources/origins.rs
- test/builder-api/src/roles.js
> Alters minimum requirement for listing user role to member

- terraform/instances.tf
- terraform/templates/windows_worker_user_data.tpl
- terraform/variables.tf
- tools/ssh_helpers/update-habitat-ssh
> enable ssh access to windows worker

- components/builder-api/src/server/authorize.rs
> reverting minimum role message to debug level

- components/builder-api/src/server/resources/origins.rs
> Return Ok when public key already exists

- Cargo.lock
- components/builder-api/Cargo.toml
- components/builder-api/src/lib.rs
- components/builder-api/src/main.rs
- components/builder-api/src/server/resources/channels.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-core/Cargo.toml
- components/builder-core/src/lib.rs
- components/builder-db/Cargo.toml
- components/builder-db/src/config.rs
- components/builder-db/src/lib.rs
- components/builder-db/src/models/package.rs
- components/builder-graph/Cargo.toml
- components/builder-graph/src/acyclic_rdeps.rs
- components/builder-graph/src/lib.rs
- components/builder-graph/src/main.rs
- components/builder-graph/src/rdeps.rs
- components/builder-jobsrv/Cargo.toml
- components/builder-jobsrv/src/lib.rs
- components/builder-jobsrv/src/main.rs
- components/builder-protocol/Cargo.toml
- components/builder-protocol/src/lib.rs
- components/builder-worker/Cargo.toml
- components/builder-worker/src/lib.rs
- components/builder-worker/src/main.rs
- test/run_clippy.ps1
- test/run_clippy.sh
Signed-off-by: David McNeil <mcneil.david2@gmail.com>
> Fail on compiler errors in run_clippy

- components/builder-core/src/metrics.rs
The clone here in an unsafe block created a race condition
```
unsafe {
INIT.call_once(|| {
SENDER = Box::into_raw(Box::new(init()));
});
(*SENDER).clone()
}
```
This was causing an increasing number of failures in the metrics code,
including illegal instruction and invalid memory references (SIGILL,
SIGSEV). Our favorite was 'thread panicked while panicking'. While we
don't know exactly what that means, recursive panic sounds
bad. Fortunately the failures happened often enough to be debuggable;
we suspect our increasing usage of tokio async more frequently
triggered this pre-existing issue.
The basic strategy rewrites the block to protect the clone with a
mutex, using the lazy_static macro to eliminate the need for the
unsafe block at all.
One possible risk with this approach is …
> Fix race condition in metrics setup

- DEVELOPING.md
This has been tripping up users creating a new studio setup.
> update studio developer docs with github app requirements

- components/builder-api/src/server/services/github.rs
> debug output unknown github events being received

- CODEOWNERS
> Remove me as codeowner

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-graph/src/acyclic_package_graph.rs
- components/builder-graph/src/cyclic_package_graph.rs
- components/builder-graph/src/graph_helpers.rs
- components/builder-graph/src/package_graph_target.rs
- components/builder-graph/src/package_graph_trait.rs
- components/builder-graph/src/package_ident_intern.rs
- components/builder-jobsrv/src/server/mod.rs
Reverts habitat-sh/builder#1554
> Revert "Add API endpoint to jobsrv to return graph "

- components/builder-db/src/migrations/00000000000000_diesel_initial_setup/up.sql
- components/builder-db/src/migrations/2020-11-09-000001_job_graph_scheduler/up.sql
A handful of other schema objects also need some idempotency checks!
> Add more idempotency to job_graph migration

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-graph/src/acyclic_package_graph.rs
- components/builder-graph/src/cyclic_package_graph.rs
- components/builder-graph/src/graph_helpers.rs
- components/builder-graph/src/package_graph_target.rs
- components/builder-graph/src/package_graph_trait.rs
- components/builder-graph/src/package_ident_intern.rs
- components/builder-jobsrv/src/server/mod.rs
Reverts habitat-sh/builder#1564
> Revert "Revert "Add API endpoint to jobsrv to return graph ""

- CODEOWNERS
> Remove christophermaier as code owner

- test/run_cargo_test.sh
> test using the same rust toolchain we use for release

- components/builder-worker/habitat/x86_64-windows/plan.ps1
- support/ci/builder-base-plan.sh
> bump builder version numbers to fix sorting

- Cargo.lock
- components/builder-worker/Cargo.toml
fixes #1598 
This ended up being more urgent since acceptance was panicking on the older tokio. 
> bump tokio in the builder-worker

- Cargo.lock
- components/builder-worker/Cargo.toml
> update habitat_core and retry

- Cargo.lock
- components/builder-jobsrv/Cargo.toml
- components/builder-jobsrv/src/server/handlers.rs
- components/builder-jobsrv/src/server/log_archiver/local.rs
- components/builder-jobsrv/src/server/log_archiver/mod.rs
- components/builder-jobsrv/src/server/log_archiver/s3.rs
- components/builder-jobsrv/src/server/log_ingester.rs
- components/builder-jobsrv/src/server/mod.rs
- components/builder-jobsrv/src/server/worker_manager.rs
> Bump rusoto deps

- Cargo.lock
> bump tar and actix-http

- .expeditor/scripts/post_habitat_release/cargo_update.sh
> fix automated cargo update post build step

- components/builder-web/app/statuspage/_statuspage-indicator.component.scss
- components/builder-web/app/statuspage/statuspage-indicator.component.ts
closes #1673 
We ow need to use the `components` api and filter the component to report.
> migrate from status.habitst.sh to status.chef.io

- .expeditor/config.yml
- .expeditor/release_builder.pipeline.yml
- .expeditor/scripts/post_habitat_release/shared.sh
- .expeditor/scripts/release_builder/hab-raml-converter.js
- .expeditor/scripts/release_builder/update_api_docs.sh
Signed-off-by: pozsgaic <pozsgai@progress.com>
Do not merge until builder api.raml has been merged.
> Add builder api docs release pipeline

- components/builder-db/src/models/package.rs
- components/builder-web/app/actions/packages.ts
- components/builder-web/app/client/depot-api.ts
- components/builder-web/app/package/package-detail/_package-detail.component.scss
- components/builder-web/app/package/package-detail/package-detail.component.html
- components/builder-web/app/package/package-detail/package-detail.component.ts
- components/builder-web/app/package/package-latest/package-latest.component.html
- components/builder-web/app/package/package-latest/package-latest.component.ts
- components/builder-web/app/package/package-release/package-release.component.html
- components/builder-web/app/package/package-release/package-release.component.ts
- components/builder-web/app/package/package/package.component.html
- components/builder-web/app/records/Package.ts
- components/builder-web/app/reducers/packages.ts
- components/builder-web/app/shared/_shared.module.scss
- components/builder-web/app/shared/date/_date.component.scss
- components/builder-web/app/shared/date/date.component.ts
- components/builder-web/app/shared/shared.module.ts
- components/builder-web/app/shared/text/_text.component.scss
- components/builder-web/app/shared/text/text.component.ts
closes #1624
This PR updates the UI for:
1. To Show the HART size
2. To show the promotion date of channels
In addition, it addresses the following fixes:
1. Choose the proper creation and updation date for package channels 
2. Make sure the **Versions** tab is highlighted when expanding the versions nodes.
> Enhancing Builder info (UI)

- components/builder-api/doc/api.raml
Signed-off-by: pozsgaic <pozsgai@progress.com>
> reorder api.raml and add missing descriptions

- CHANGELOG.md
Prepared the changelog for the upcoming release.
> Prepare the change for the next release

- components/builder-api/doc/api.raml
Signed-off-by: pozsgaic <chris.pozsgai@progress.com>
> update rdeps descriptions

- DEVELOPING.md
Signed-off-by: pozsgaic <chris.pozsgai@progress.com>
Adds multipass specific info and separate into VMWare and Multipass sections
> Add multipass info

- components/builder-jobsrv/src/server/scheduler.rs
- components/builder-protocol/protocols/jobsrv.proto
- components/builder-protocol/src/jobsrv.rs
Signed-off-by: pozsgaic <pozsgai@progress.com>
> add handling for not found packages

- components/builder-web/app/package/_package.module.scss
- components/builder-web/app/package/package-sidebar/package-sidebar.component.ts
- components/builder-web/app/package/package/package.component.html
- components/builder-web/app/package/package/package.component.ts
- components/builder-web/app/records/Package.ts
UI changes for native packages:
1. show a tag if it is native next to 'package' or 'artifact' label
2. disable 'Build latest version'
> native pkg UI changes

- components/builder-web/package-lock.json
- components/builder-web/package.json
Update utils-loader package for Prototype pollution.
Install utils-loader packages inside the devDependency
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-4512
> updated loader utils package version

- .expeditor/scripts/post_habitat_release/shared.sh
- Makefile
- components/builder-api/habitat/plan.sh
- components/builder-graph/habitat/plan.sh
- components/builder-jobsrv/habitat/plan.sh
- components/builder-worker/habitat-dev/plan.sh
- components/builder-worker/habitat/x86_64-linux-kernel2/plan.sh
- components/builder-worker/habitat/x86_64-linux/plan.sh
- components/builder-worker/habitat/x86_64-windows/plan.ps1
- rust-toolchain
- support/ci/shared.ps1
- support/ci/shared.sh
This should get dependabot working again.
> use toml rust-toolchain

- components/builder-web/app/package/package-sidebar/package-sidebar.component.html
- components/builder-web/app/package/package-sidebar/package-sidebar.component.spec.ts
Removed the build button and added a message with link to https://docs.chef.io/habitat/pkg_build/ 
#Issues:
https://chefio.atlassian.net/browse/CHEF-13675
> CHEF-13675: Removed build button from UI.

- components/builder-web/app/shared/channels/_channels.component.scss
- components/builder-web/app/shared/channels/channels.component.html
- components/builder-web/stylesheets/base/_colors.scss
- test/builder-api/src/channels.js
Changed colours for channels as per the provided Figma.
https://chefio.atlassian.net/browse/CHEF-13678
https://www.figma.com/design/zq1RMwbjRbTzJaoObNuRWG/Hab_Builder_Latest_Channels?node-id=401-2&t=nf0YPYLVqTcQviFW-0
> CHEF-13678: Changed colour for channels

- .github/workflows/hab-pkg-build-upload.yaml
I snuck in two name changes but this is really about testing if memcached builds with a file added into its hierarchy which should trigger a rebuild of the package.  a subsequent pr will remove the file this pr adds.
> name changes and workflow trigger test

- components/builder-web/app/actions/packages.ts
- components/builder-web/app/initial-state.ts
- components/builder-web/app/package/package-detail/package-detail.component.ts
- components/builder-web/app/package/package-sidebar/package-sidebar.component.html
- components/builder-web/app/package/package-sidebar/package-sidebar.component.ts
- components/builder-web/app/package/package/package.component.ts
- components/builder-web/app/util.ts
show latest and LTS-2024 channel UI created
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-13676
Before : - 
After : -
> Changes : show latest and LTS-2024

- components/builder-web/app/initial-state.ts
- components/builder-web/app/package/package-detail/package-detail.component.ts
- components/builder-web/app/package/package-sidebar/package-sidebar.component.html
- components/builder-web/app/package/package-sidebar/package-sidebar.component.ts
- components/builder-web/app/package/package/package.component.ts
show LTS-2024 and Promote logic change
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-13676
> Changes : show LTS-2024 and Promote logic change

- components/builder-web/app/package/package-promote/package-promote.component.html
- components/builder-web/app/package/package-promote/package-promote.component.ts
- components/builder-web/app/package/package-versions/package-versions.component.html
- components/builder-web/app/package/package-versions/package-versions.component.ts
New promote popup added for version tab
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-14662
> New promote popup added for version tab

- components/builder-web/app/origin/origin-page/origin-page-routing.module.ts
- components/builder-web/app/package/package-routing.module.ts
- components/builder-web/app/shared/guards/visibility-enabled.guard.ts
- components/builder-web/app/shared/shared.module.ts
This fixes a bug where you are redirected to the /pkgs page when clicking the settings tab.
> implement VisibilityEnabledGuard to show visibility settings

- components/builder-web/app/package/package-detail/package-detail.component.ts
- components/builder-web/app/package/package-versions/package-versions.component.ts
- components/builder-web/app/package/package/package.component.ts
Promotable logic change and bug fix for fetch LTS API call
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-14662
> Promotable logic change and bug fix for fetch LTS API call

- components/builder-web/app/package/package/package.component.ts
fetch Current Lts excpetion handle
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-14662
> fetch Current Lts excpetion handle

- components/builder-web/app/package/package-sidebar/package-sidebar.component.html
css changes done
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-14662
> css changes done

- components/builder-api/src/server/resources/profile.rs
- test/builder-api/src/profile.js
> Fixed unauthorized access token deletion bug

- components/builder-web/app/app.component.html
Added EULA link.
Updated copyright date and name.
https://chefio.atlassian.net/browse/CHEF-13952
https://chefio.atlassian.net/browse/CHEF-14969
> CHEF-13952, CHEF-14969: Added EULA link and updated copyright.

- components/builder-api/src/config.rs
- components/builder-api/src/server/mod.rs
- components/builder-api/src/server/resources/pkgs.rs
- test/builder-api/src/channels.js
- test/builder-api/src/packages.js
> Enables native packages by default

- components/builder-web/app/shared/dialog/eula-confirm/eula-confirm.dialog.html
- components/builder-web/app/shared/dialog/eula-confirm/eula-confirm.dialog.ts
- components/builder-web/app/shared/shared.module.ts
- components/builder-web/app/sign-in-page/sign-in-page.component.html
- components/builder-web/app/sign-in-page/sign-in-page.component.ts
Eula popup added while sign in and sign up
Related Tasks:
https://chefio.atlassian.net/browse/CHEF-13951
https://github.com/user-attachments/assets/f0ec8a48-a921-4511-aedc-b0d82e11d7b0
> Eula popup added

- components/builder-web/app/client/depot-api.ts
- components/builder-web/app/package/package/package.component.ts
story :[CHEF-16648](https://progresssoftware.atlassian.net/browse/CHEF-16648)
[CHEF-16648]: https://progresssoftware.atlassian.net/browse/CHEF-16648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix UI version bug

- components/builder-web/app/reducers/packages.ts
- components/builder-web/package.json
@AadeshNichite 
marked package version updated with latest
https://progresssoftware.atlassian.net/browse/CHEF-4510
> marked package version updated with latest

- components/builder-web/package.json
@AadeshNichite
moment package version updated with latest
https://progresssoftware.atlassian.net/browse/CHEF-12264
> moment library update

- components/builder-api/src/server/resources/pkgs.rs
[CHEF-19668](https://progresssoftware.atlassian.net/browse/CHEF-19668)
[CHEF-19668]: https://progresssoftware.atlassian.net/browse/CHEF-19668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Removed Plan content from UI and API

- components/builder-api/habitat/default.toml
- components/builder-api/src/config.rs
- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/resources/pkgs.rs
- components/builder-api/src/server/resources/profile.rs
- test/builder-api/src/channels.js
- test/builder-api/src/packages.js
[CHEF-20135](https://progresssoftware.atlassian.net/browse/CHEF-20135)
[CHEF-20135]: https://progresssoftware.atlassian.net/browse/CHEF-20135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added license validation for pkg download

- components/builder-api/src/server/resources/profile.rs
[CHEF-22123](https://progresssoftware.atlassian.net/browse/CHEF-22123)
[CHEF-22123]: https://progresssoftware.atlassian.net/browse/CHEF-22123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated get license API

- components/builder-api/src/server/resources/pkgs.rs
- components/builder-web/app/package/package-detail/package-detail.component.html
- components/builder-web/app/reducers/packages.ts
[CHEF-22668](https://progresssoftware.atlassian.net/browse/CHEF-22668)
[CHEF-22668]: https://progresssoftware.atlassian.net/browse/CHEF-22668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added package metadata back

- components/builder-api/src/server/helpers.rs
- components/builder-api/src/server/resources/profile.rs
[CHEF-22123](https://progresssoftware.atlassian.net/browse/CHEF-22123)
[CHEF-22123]: https://progresssoftware.atlassian.net/browse/CHEF-22123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed license expiration response

- components/builder-web/app/app.component.html
Updated copyright year range to match current year 2025.
> Update copyright year to 2025
