habitat-sh/builder

Cargo.lock, components/builder-admin/Cargo.toml, components/builder-api/Cargo.toml, components/builder-depot/Cargo.toml, components/builder-http-gateway/Cargo.toml, components/builder-sessionsrv/Cargo.toml, components/builder-worker/Cargo.toml
Merge this _after_ https://github.com/habitat-sh/habitat/pull/4452 merges to point git refs to the `master` branch.
=> Remove references to jb/remove-builder branch

components/builder-admin-proxy/plan.sh, components/builder-api-proxy/plan.sh, support/ci/builder-base-plan.sh
=> Add version bump to git rev count since it's off after the builder migration

Cargo.lock
Update Cargo.lock (cargo update) to fix dependency failures - eg, for habitat_win_users
Note: Cargo update might have been more aggressive than we want and the openssl rev looks like it went backward, so this may not quite be what we want but it gets past the compile error.
=> Update cargo lock to fix dependencies

components/builder-api-proxy/plan.sh
Because we rely on the openssl executable for the build process.
=> Add openssl to builder-api-proxy

tools/ssh_helpers/airlock.sh
We use this helper script to diagnose network issues on Builder workers.
=> Add airlock.sh script

components/builder-web/app/actions/index.ts, components/builder-web/app/actions/packages.ts, components/builder-web/app/client/depot-api.ts, components/builder-web/app/initial-state.ts, components/builder-web/app/origin/origin-page/origin-packages-tab/origin-packages-tab.component.html, components/builder-web/app/package/package-detail/package-detail.component.html, components/builder-web/app/package/package-detail/package-detail.component.spec.ts, components/builder-web/app/package/package-detail/package-detail.component.ts, components/builder-web/app/package/package-promote/_package-promote.component.scss, components/builder-web/app/package/package-release/package-release.component.ts, components/builder-web/app/package/package/package.component.ts, components/builder-web/app/reducers/packages.ts, components/builder-web/assets/images/icons/all.svg
This change adds the promote-to-stable button to the Latest and Release views.
Also fixes a couple of teeny bugs:
* Closes an unclosed tag in the SVG icon markup
* Hides the border of the connected-plans table when there aren't any
Fixes: #4465.
=> Promote from package-detail views

components/builder-web/app/client/github-api.ts
Currently we query the GitHub API to determine the user’s list of connectable repositories. This increases that query’s per-page count from 30 (the default) to 100, which should reduce the overall number of requests we have to make to assemble the list (and thus help with rate-limiting issues).
=> Increase the repositories-per-page query

components/builder-web/.gitignore, components/builder-web/app/search/results/_results.component.scss, components/builder-web/app/search/results/results.component.html, components/builder-web/app/search/results/results.component.spec.ts, components/builder-web/app/search/results/results.component.ts
Looks like this fell through the cracks with the repo split. This restores it and adds an exception to the .gitignore file.
=> Restore search results

.studiorc
Also:
* Remove build-foo functions in favor of build-builder foo
* Add bb alias
* Remove build-{admin-proxy,api-proxy,datastore}
Resolves https://github.com/habitat-sh/builder/issues/103
=> Make build-builder stop on component build failure

components/builder-web/app/shared/checking-input/_checking-input.component.scss, components/builder-web/app/shared/checking-input/checking-input.component.html
Vertical alignment is off a bit because of a class name used elsewhere in the app. This makes the class name more specific to the input component.
=> Fix input icon alignment

components/builder-api-proxy/config/habitat.conf.js, components/builder-api-proxy/default.toml, components/builder-web/app/actions/features.ts, components/builder-web/app/actions/index.ts, components/builder-web/app/app.component.ts, components/builder-web/app/initial-state.ts, components/builder-web/app/origin/origin-page/origin-page-routing.module.ts, components/builder-web/app/origin/origin-page/origin-page.component.html, components/builder-web/app/origin/origin-page/origin-page.component.ts, components/builder-web/app/package/package-routing.module.ts, components/builder-web/app/package/package/package.component.html, components/builder-web/app/package/package/package.component.spec.ts, components/builder-web/app/package/package/package.component.ts, components/builder-web/app/reducers/features.ts, components/builder-web/app/shared/guards/builder-enabled.guard.ts, components/builder-web/app/shared/project-settings/_project-settings.component.scss, components/builder-web/app/shared/shared.module.ts, components/builder-web/habitat.conf.sample.js
This change adds a configuration item, `enable_builder`, to the `builder-api-proxy` package that toggles Builder-specific functionality in the UI. When Builder is enabled, we expose:
* The Integrations and Settings tabs in the Origins section
* The Build Jobs and Settings tabs in the Packages section
When it’s disabled, we’ll also redirect requests to these Builder-specific views to prevent any broken-looking experiences.
=> Toggle Builder features in the UI

.studiorc
Is this as opposed to `hab start "core/builder-$component"`. That failed since
some of the components require extra arguments. Also, run `stop-$component`
for consistency.
=> In dev studio, after `builder-build-component`, run `start-$component`.

tools/ssh_helpers/airlock.sh
This update will check to see if the network interface has been placed
in the correct network namespace and has an IP address. Otherwise, it
will fall back to check for the appropriate failure scenarios to report
back to the operator. Note that not all failure scenarios are easily
actionable with an automated script (hence the report messaging).
=> [tools] Update the `ssh_helpers/airlock.sh` test.

components/builder-api/src/config.rs, components/builder-api/src/lib.rs, components/builder-api/src/server/handlers.rs, components/builder-api/src/server/mod.rs, components/builder-depot/src/config.rs, components/builder-depot/src/lib.rs, components/builder-depot/src/server.rs
This PR introduces a new config flag for both `builder-depot` and `builder-api` called `jobsrv_enabled`.  It's `true` by default, but when it's set to `false`, then no communication with `builder-jobsrv` will occur.
I switched our routes from the macro syntax to the normal function based syntax because it turns out it's difficult to have programmatic control over your routes inside a macro.  I should also note that some of our routes are ambiguous enough (and iron's router isn't capable enough) that some of our routes will get called incorrectly.  One concrete example of this is:
`/pkgs/origins/:origin/stats`
This retrieves package stats and it uses `builder-jobsrv` to do it.  When `jobsrv_enabled` is set to `false`, that route isn't present in the routing table.  However, if you go to, …
=> Introduce config flag to disable jobsrv communication

support/ci/builder-dev-plan.sh
Resolves https://github.com/habitat-sh/builder/issues/168
This appears to be a simple oversight from Just an oversight from a3d05cfa959e948d7a51b5965cbc947d9c1783a9
=> Change `core` origin to `habitat` in `do_builder_install` for builder dev

components/builder-web/app/actions/origins.ts
Currently, when a new origin is created, we make an immediate call to retrieve all origins, but the list that’s returned often leaves out the new origin because of a data-propagation issue. This temporary fix adds a one-second delay to leave enough time for that propagation to happen.
=> Briefly delay the call to fetch origins

components/builder-web/app/actions/gitHub.ts, components/builder-web/app/actions/index.ts, components/builder-web/app/client/github-api.ts, components/builder-web/app/initial-state.ts, components/builder-web/app/reducers/gitHub.ts, components/builder-web/app/shared/project-settings/_project-settings.component.scss, components/builder-web/app/shared/project-settings/project-settings.component.html, components/builder-web/app/shared/project-settings/project-settings.component.ts, components/builder-web/stylesheets/base/_lists.scss
This change modifies the plan-connection UX to allow for click-based selection of organization and repositories. Doing so also allows us to cut way down on the number of API calls we make to GitHub.
Fixes #149.
=> Improve plan-connection flow

components/builder-web/app/shared/project-settings/_project-settings.component.scss
This is a minor tweak that accounts for lists containing only one or two items, which lay out a bit strangely in the project creation view.
=> Fix the height of the orgs and repos lists

components/builder-jobsrv/habitat/hooks/init, components/builder-originsrv/habitat/hooks/init, components/builder-sessionsrv/habitat/hooks/init
This makes jobsrv, originsrv and sessionsrv work when builder-datastore runs
on a port other than the psql default.
Fixes https://github.com/habitat-sh/builder/issues/175
=> Make srv components init hook respect datastore port binding

terraform/scripts/create_bootstrap_bundle.sh
Minor change - removed deprecated package from bootstrap bundle
=> Remove scheduler from bundle

terraform/instances.tf, terraform/scripts/install_base_packages.sh
Fixes the Terraform script to work with the new habitat origin for builder services.
=> Fix terraform to work with habitat origin

support/ci/builder-dev-plan.sh
Also simplify the code for linking in binaries and add more informative
logging of what's happening
Fixes https://github.com/habitat-sh/builder/issues/172
=> Install lifecycle hooks after building builder components locally

components/builder-worker/habitat/hooks/run
Check for PEM file in the builder-worker run hook - if the PEM file does not exist, the worker can crash if a job is queued.
=> Check for PEM file before starting worker

components/builder-api/src/github.rs, components/builder-api/src/server/handlers.rs, components/builder-sessionsrv/src/server/handlers.rs, components/builder-worker/src/runner/mod.rs
This change improves the github related error logging by adding and/or converting debug logs to warnings that can be collected via the syslog.
=> Improve github failure logging

.studiorc, components/builder-worker/src/runner/docker.rs, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/studio.rs, support/linux/provision.sh
=> Add ability for worker to bind to local docker socket for testing exports

components/builder-web/app/actions/builds.ts, components/builder-web/app/actions/index.ts, components/builder-web/app/initial-state.ts, components/builder-web/app/package/build-detail/build-detail.component.html, components/builder-web/app/package/build-detail/build-detail.component.spec.ts, components/builder-web/app/package/build-detail/build-detail.component.ts, components/builder-web/app/reducers/builds.ts, components/builder-web/app/shared/icon/icon.component.ts
Currently, when a user navigates to a running build job, there’s a chance the request for that job’s log output could 404 (e.g., before logging has begun), which leaves the user staring at an empty box that never gets updated. This change adds logic to retry every five seconds until the request succeeds (or the user navigates elsewhere).
=> Retry failed log requests for running builds

components/builder-worker/src/runner/docker.rs
This is a stop-gap measure for the current stable release of
`core/hab-pkg-export-docker` which does not have a `--tag-latest` flag.
This commit should be reverted when habitat-sh/habitat#4617 is shipped
in the next stable release (which restores the latest flags).
=> [builder-worker] Temporarily remove `--tag-latest` when running Docker exporter

components/builder-web/app/actions/builds.ts, components/builder-web/app/client/builder-api.ts
This change adds an `ErrorCode` enum that maps to [Builder’s error codes](https://github.com/habitat-sh/builder/blob/d6ea4585efa49f2f1a11e70d2869675cc7b9acbe/components/builder-protocol/protocols/net.proto#L12), and makes use of the `NotFound` error to handle responses for log files that don’t yet exist.
=> Use Builder error codes

components/builder-sessionsrv/src/server/handlers.rs
This fixes up session creation for build workers - the correct privileges were not getting set.
=> Fix session flag for Builder session

support/on-prem-archive.sh, support/on-prem-install.sh
There are two scripts in this PR:
`on-prem-archive.sh` was my initial attempt at making this work by iterating over all of the plans in the `core-plans` repo, downloading the latest stable release of each one, tarring all of those up and uploading it to S3. It also supported a mode of operation to download the tarball from S3, crack it open, and upload all the resulting hart files to a fresh depot.
That strategy sounded fine at first glance but turned out to be fraught with peril. It turns out that many packages had deps that were older than the latest stable release, so when uploading the transitive deps of some packages, things failed because they couldn't find the right files.
I've left this script in this PR because eventually we're going to want to support air-gapped environments, …
=> Add a script to bootstrap an on-prem depot

.studiorc, .travis.yml, support/builder/config.sh, support/ci/fast_pass.sh
This increases usability by placing the error message in a more visible
context. Also, do some refactoring to reduce redundancy.
Resolves https://github.com/habitat-sh/builder/issues/199
=> Make builder dev environment commands stop when they encounter error

components/builder-web/app/client/builder-api.ts
Currently, when an invitation is extended to a user who hasn’t signed into Builder before, the error message we surface is simply `Unauthorized`, which is not helpful. This just changes that messages to make it clearer what needs to be done.
=> Fix non-existent-user invitation message

Cargo.lock
This picks up a fix for a breaking change from the habitat repo.
=> Update cargo lock to pick up http-client fix

components/builder-worker/habitat/plan.sh
Unpin the worker since stable hab-pkg-export-docker is now updated to latest docker.
=> Unpin worker

components/builder-sessionsrv/src/data_store.rs
Small change to fix getting the account id correctly for token revocation.
=> Fix account token revocation

components/builder-web/app/app.scss
This reverts commit 71d319c7c460bdc8b712f4abc63bcdaa83e6bcbf.
The `overflow-y: scroll` is necessary here for the overall site layout. (It is apparently also causing a display issue on Linux, which I'll file a separate issue for.)
=> Revert "Remove forced overflow-y: scroll"

components/builder-web/app/app.scss, components/builder-web/app/shared/copyable/_copyable.component.scss
This change hides the horizontal scrollbars in the copyable component, and fixes a visible scrollbar on the sign-in screen.
=> Tweak scrollbar visibility

.studiorc, components/builder-api/src/github.rs, components/builder-api/src/lib.rs, components/builder-api/src/server/handlers.rs, components/builder-api/src/server/mod.rs, components/builder-core/src/metrics.rs, components/builder-depot/src/lib.rs, components/builder-depot/src/server.rs, components/builder-http-gateway/src/http/middleware.rs, components/builder-sessionsrv/src/server/handlers.rs, components/builder-worker/src/vcs.rs
This change enables use of statsd metrics - it adds some counters for tracking github API calls. There's also some misc cleanup (removes unused event handling), and adds some additional logging for the github APIs.
=> Enable statsd metrics for github calls

components/builder-sessionsrv/src/server/handlers.rs
1-liner fix to add a missing reply to token validation. Makes builds work again.
=> Missed connection reply in token validation

components/builder-web/package-lock.json, components/builder-web/package.json
This updates the moment.js library to its latest version.
=> Bump moment.js to 2.21.0

Cargo.lock, Cargo.toml, Makefile, components/builder-api/Cargo.toml, components/builder-depot/Cargo.toml, components/builder-http-gateway/Cargo.toml, components/builder-sessionsrv/Cargo.toml, components/builder-worker/Cargo.toml, components/github-api-client/Cargo.toml, components/github-api-client/src/client.rs, components/github-api-client/src/config.rs, components/github-api-client/src/error.rs, components/github-api-client/src/lib.rs, components/github-api-client/src/types.rs
This crate was in the habitat repository, but is only used in this repository. This pulls all history from the code and adds it into this repository.
=> Add GitHub client crate from habitat repository

tools/ssh_helpers/hab-env, tools/ssh_helpers/update-habitat-ssh
Also, clean up shellcheck lints,make the script run correctly regardless of the
current directory, and provide some instructive output if run without args.
I removed the "TODO: constrain the list of possible environments?" comment since
I think that is more the domain of the generate-habitat-env-tmuxinator.sh
script. If we added new environments, we don't want to have to modify this.
=> Create the tmuxinator directory if it doesn't already exist

Cargo.lock, components/builder-api/src/github.rs, components/builder-api/src/lib.rs, components/builder-api/src/metrics.rs, components/builder-api/src/server/handlers.rs, components/builder-core/src/metrics.rs, components/builder-depot/src/lib.rs, components/builder-depot/src/metrics.rs, components/builder-depot/src/server.rs, components/builder-http-gateway/src/http/middleware.rs, components/builder-sessionsrv/src/server/handlers.rs, components/builder-worker/src/lib.rs, components/builder-worker/src/metrics.rs, components/builder-worker/src/vcs.rs, components/github-api-client/Cargo.toml, components/github-api-client/src/client.rs, components/github-api-client/src/lib.rs, components/github-api-client/src/metrics.rs
This commit involves several refactorings of our existing metrics code
that should make it more flexible moving forward. It evolved through
several iterations, so I'll attempt to lay out the story here in
prose, rather than individual commits; sorry :/
Since our existing metrics are mainly around Github API interactions,
that's what most of this discussion will focus on.
First, rather than instrumenting each call site where we make a Github
API call, our metrics calls are now embedded within our Github API
client library; anything that calls it will automatically be measured.
Second, a new set of Github token types are introduced: `AppToken` and
`UserToken`. The former bundles together an API token with the Github
App installation ID that was used to generate it. Everything outside
the …
=> Refactor metrics infrastructure

.travis.yml, Cargo.lock, Cargo.toml, components/builder-api/Cargo.toml, components/builder-depot/Cargo.toml, components/builder-http-gateway/Cargo.toml, components/segment-api-client/Cargo.toml, components/segment-api-client/src/client.rs, components/segment-api-client/src/config.rs, components/segment-api-client/src/error.rs, components/segment-api-client/src/lib.rs, components/segment-api-client/src/main.rs
This pulls the `segment-api-client` crate over from the habitat repository.
See https://github.com/habitat-sh/habitat/issues/4724
=> Add segment-api-client

components/builder-sessionsrv/src/server/handlers.rs, components/builder-web/habitat.conf.sample.js
Modify the access token comparison to ignore the right trailing '='.  This is usually just a filler added by base64 conversion. When copying the token, it's easy to lose the '=', and we want to avoid having unneeded false negatives during the token check.
Also a minor switch to a default in a sample config file.
=> Improve token comparison

Cargo.lock, components/builder-core/Cargo.toml, components/builder-core/src/lib.rs, components/builder-core/src/metrics.rs
This swaps out the generic StatsD client we were using for a DogStatsD
client. We use DataDog as our metrics aggregator, and this will allow
us to take advantage of some DataDog extensions, particularly metric
tags.
No tags are added in this PR, though; this is just a pure replacement
of the stats client.
Closes #267
=> Switch to DogStatsD client

components/builder-http-gateway/src/http/middleware.rs, components/github-api-client/src/client.rs
This makes `UserToken` a real type, as opposed to a simple alias,
which just makes all the typing very explicit; otherwise you could
accidentally pass any old `String` as a `UserToken`, which we don't
want.
In response to https://github.com/habitat-sh/builder/pull/263#discussion_r173257966
=> Turn UserToken into a newtype

components/builder-web/app/shared/copyable/_copyable.component.scss
This is a minor CSS fix that helps to improve the appearance of our side-scrolling input boxes on Linux.
=> Improve side-scrolling

components/builder-worker/src/metrics.rs, components/builder-worker/src/vcs.rs
This was a leftover from a previous incarnation of the metrics
work. Now, we create a `github.authenticated_clone` and `github.clone`
metric to capture both authenticated and non-authenticated clones.
=> Remove installation_id from metric name

terraform/instances.tf, terraform/templates/hab-sup.service
This update enables the Datadog StatsD service that is used for operational metrics.
=> Update Terraform to enable Datadog statsd

components/builder-api-proxy/default.toml, components/builder-web/app/oauth-providers/index.ts
When specified, this URL is used on the sign-in view to link to the OAuth provider's account-creation page. We default to GitHub as our default provider.
=> Specify a default OAuth signup URL

components/builder-api-proxy/config/habitat.conf.js, components/builder-api-proxy/config/index.html, components/builder-api-proxy/config/nginx.conf, components/builder-api-proxy/default.toml, components/builder-api-proxy/plan.sh, components/builder-web/app/actions.test.ts, components/builder-web/app/browser.ts, components/builder-web/app/side-nav/side-nav.component.html, components/builder-web/bin/dist, components/builder-web/habitat.conf.sample.js, components/builder-web/index.html
This change adds two new configuration properties, `hosted` and `cookie_domain`, to allow us to suppress certain behaviors in on-prem installations.
Specifically, we insert third-party scripts (e.g., Google Analytics, Heap Analytics, Segment and StatusPage) only in our hosted environments, and we allow cookie domains to be configurable (defaulting to the current hostname).
Also suppresses third-party scripts in the development environment, which has been causing our UX friends some headaches lately. 😄 
=> Better support on-prem behavior in Builder UI

.studiorc, components/builder-sessionsrv/src/server/handlers.rs, components/github-api-client/src/client.rs, components/github-api-client/src/types.rs, support/builder/config.sh
This PR deprecates the use of github teams for the RBAC-like permission flags that are associated with account logins.  The worker permission has already been moved over to personal access tokens, and the other two (admin and early_access) are not used. Removing the use of github teams will simplify the auth flow for both hosted and on-premise builder deployments. 
This PR also has a couple of updates to configs for the dev environment.
=> Deprecate use of github teams for permissions

components/builder-sessionsrv/habitat/config/config.toml, components/builder-sessionsrv/habitat/default.toml, components/builder-sessionsrv/src/config.rs, components/builder-sessionsrv/src/server/mod.rs, support/builder/config.sh
Remove unused Github and Permissions config from sessionsrv.
=> Remove Github and Permissions Config from sessionsrv

components/builder-web/app/app.scss
This component was removed in 558e32c. (The include is currently breaking the CSS build.)
=> Remove Sass import of deleted component

components/builder-api-proxy/config/habitat.conf.js, components/builder-api-proxy/default.toml, components/builder-web/app/initial-state.ts, components/builder-web/app/origin/origin-page/integration-credentials-form/integration-credentials-form.dialog.html, components/builder-web/app/origin/origin-page/integration-credentials-form/integration-credentials-form.dialog.ts, components/builder-web/app/origin/origin-page/origin-integrations-tab/_origin-integrations-tab.component.scss, components/builder-web/app/origin/origin-page/origin-integrations-tab/origin-integrations-tab.component.html, components/builder-web/app/origin/origin-page/origin-integrations-tab/origin-integrations-tab.component.ts, components/builder-web/app/reducers/features.ts, components/builder-web/habitat.conf.sample.js
This change adds an additional container-publishing option for Azure to the origin Integrations tab. It also adds some differentiation between the three registries’ modal dialogs, since they all differ slightly in their terminology and example settings, and it makes all three publishers configurable as well.
=> Add UI support for Azure Container Registry

components/builder-api-proxy/default.toml
This default config entry was removed by mistake in a922fbb.
=> Restore app_url

.secrets/habitat-env.sample, .studiorc, BUILDER_CONTAINER.md, Dockerfile, components/bitbucket-api-client/src/client.rs, components/bitbucket-api-client/src/config.rs, components/builder-api-proxy/config/habitat.conf.js, components/builder-api-proxy/default.toml, components/builder-api/habitat/default.toml, components/builder-api/src/config.rs, components/builder-api/src/server/mod.rs, components/builder-depot/src/config.rs, components/github-api-client/src/client.rs, components/github-api-client/src/config.rs, support/builder/config.sh
This change does cleanup of the auth configs in readiness for the on-prem builder:
* Rename github "url" configuration to "api_url" (to be consistent across GH / Bitbucket)
* Rename "web_url" to "token_url" to be consistent with OAuth terminology
* Allow token_url to be fully configurable like the API and Authorize URLs
* Add github app URL to a couple of places that were missing it
* Remove deprecated config (admin_team) 
* Add a check to make sure we have exactly one auth config for builder api
* Fix up some unit tests that were failing 
* Other misc cleanup
After this change is merged, builder devs will need to update their .secrets/habitat-env file. The acceptance and prod env will also need appropriate updates to their configs.
=> Config cleanup for Github and Bitbucket clients

tools/ssh_helpers/update-habitat-ssh
Sed in osx allows a space after the `-i` flag but the unix version doesn't.
=> fix sed for linux

components/builder-depot/src/server.rs, test/builder-api/src/keys.js
The server side counterpart to https://github.com/habitat-sh/habitat/pull/4811
Removes un-needed API.
Closes: #294
=> Deprecate hab bldr encrypt

components/builder-worker/habitat/plan.sh, components/builder-worker/src/runner/docker.rs
Yes, this will break some of the isolation in the worker environment but the alternative is building app armor as a hab package.
=> Remove docker pinnings and add sbin to worker path

components/builder-web/app/sign-in-page/_sign-in-page.component.scss
A recent change modified the width of `content` elements to constrain it to 3/4 width on the desktop, but we don’t want to apply that constraint on the sign-in page. This fixes it.
=> Don’t constrain width on the sign-in page

components/builder-api-proxy/config/habitat.conf.js, components/builder-api-proxy/config/index.html, components/builder-api-proxy/default.toml, components/builder-web/app/actions/users.ts, components/builder-web/habitat.conf.sample.js, components/builder-web/index.html
This change adds a new configuration section to allow on-prem customers to share usage data with us via Heap Analytics.
=> Support optional on-prem analytics

components/builder-web/app/origin/origin-create-page/origin-create-page.component.ts, components/builder-web/app/origin/origin-page/origin-members-tab/origin-members-tab.component.ts, components/builder-web/app/shared/docker-export-settings/docker-export-settings.component.ts
As part of the detachment from GitHub auth, we changed source of the information we privilege about the signed-in user. (It had been GitHub, and is now the user’s Builder profile.) This fixes a few places where that change was overlooked.
=> Use profile.name instead of username

components/builder-originsrv/habitat/default.toml, components/builder-originsrv/src/config.rs, components/builder-originsrv/src/data_store.rs, components/builder-originsrv/src/server/mod.rs
This change adds a jobsrv_enabled config value to sessionsrv, so that we don't attempt to sync package metadata with the jobsrv if it is not present.
=> Check for jobsrv_enabled when syncing packages

components/builder-originsrv/src/server/handlers.rs
=> Rename error messages to be unique to origin secrets

components/builder-worker/src/runner/docker.rs
When the `--exec-root` file path is longer than 67 characters
containerd fails to start becuase it can't create it's gRPC sockets.
=> Shorten filepath to get around containerd file path char limit

components/builder-api/src/server/mod.rs, components/builder-depot/src/server.rs, components/builder-jobsrv/src/data_store.rs, components/builder-jobsrv/src/migrations/2018-03-28-021112_job_group_origin_v2/up.sql, components/builder-protocol/protocols/jobsrv.proto, components/libbuild-protocols.rs, docs/Migrations.md
This is the services update for https://github.com/habitat-sh/habitat/pull/4841
Getting the schedule status is now much more lightweight. By default, we only query the last most recent 10 job groups when querying by origin. Also we only return detailed project information when needed instead of always querying and returning it to the caller.
=> Update bldr job status functionality

components/github-api-client/src/client.rs
The serde Value to_string function does not strip quotes from strings.  We need to do the as_... functions to get the quotation marks to get stripped.  This fixes a regression where the logged in user is not correctly recognized.
=> Strip quotes from serde strings

Cargo.lock
Includes:
* habitat-sh/core#19
* habitat-sh/core#22
* habitat-sh/core#20
* habitat-sh/core#21
* habitat-sh/core#22
=> [core] Update git repo to consume habitat-sh/core#22.

components/builder-api/src/server/handlers.rs, components/builder-http-gateway/src/http/helpers.rs, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/scheduler.rs
This fixes a regression from an earlier commit (https://github.com/habitat-sh/builder/commit/048bb282bf173f1d55cf3a68a1cb3b9458c6f0ea) - reverse dependency builds will not work correctly if the include_projects field is not set.
=> Fix regression in use of JobGroupGet message

components/oauth-client/src/client.rs
Fix a missed case for the proxy usage in the OAuth client
=> Fix proxy usage in OAuth client

components/builder-web/package-lock.json, components/builder-web/package.json
This change moves us back to using package-lock.json, removes an unused angular-cli module, and updates the versions of karma, webpack and node-sass.
=> Revert switch to shrinkwrap, remove angluar-cli, update some deps

CODEOWNERS
I won't be doing any habitat PRs for a bit, so I don't want authors waiting around for my response
=> Temporarily remove baumanj

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml, components/builder-api-proxy/habitat/plan.sh
This change enables builder-api-proxy to configure SSL endpoints natively.  This is useful in an on-premise deployment of Builder, where there is no external reverse proxy available.  In order to use this feature, the listen_tls flag needs to be set to true in the config, and the SSL cert and key files need to be uploaded to the builder-api-proxy service via `hab file upload`.  Also, nginx is configured to listen on both IPv4 and IPv6 endpoints.
=> Add native TLS and IPv6 support to builder-api-proxy

components/builder-protocol/protocols/sessionsrv.proto, components/builder-protocol/src/sessionsrv.rs, components/builder-web/app/oauth-providers/index.ts, components/oauth-client/src/gitlab.rs
Authenticating against GitLab was failing because the scope was missing in the request, and it was missing in the protocol definition.
This PR adds the missing pieces and switches to using OpenID for authenticating with GitLab. I've tested this against gitlab.com and a private GitLab EE instance.
These are the URLs that need to be configured:
```
OAUTH_USERINFO_URL="https://gitlab.com/oauth/userinfo"
OAUTH_AUTHORIZE_URL="https://gitlab.com/oauth/authorize"
OAUTH_TOKEN_URL="https://gitlab.com/oauth/token"
```
I did not find a place to document this, so that is not included in this PR.
=> Use OpenID for authenticating against GitLab

components/builder-protocol/protocols/sessionsrv.proto, components/builder-protocol/src/sessionsrv.rs, components/builder-web/app/oauth-providers/index.ts, components/oauth-client/src/client.rs, components/oauth-client/src/lib.rs, components/oauth-client/src/okta.rs
This PR adds Okta as an authentication provider.
To make this work you need to create a new application in Okta and select the "Web" type, configure the URIs and select the option "Authorization Code" in the "Grant type allowed" field.
For Builder you need the following configuration:
```
OAUTH_PROVIDER="okta"
OAUTH_USERINFO_URL="https://<your.okta.domain>.com/oauth2/v1/userinfo"
OAUTH_AUTHORIZE_URL="https://<your.okta.domain>.com/oauth2/v1/authorize"
OAUTH_TOKEN_URL="https://<your.okta.domain>.com/oauth2/v1/token"
```
I've tested this with their Single Single-On and Multi-Factor Authentication products.
=> Add Okta as an authentication provider

Cargo.lock, components/builder-core/src/access_token.rs, components/builder-depot/Cargo.toml, components/builder-depot/src/config.rs, components/builder-depot/src/error.rs, components/builder-depot/src/lib.rs, components/builder-depot/src/server.rs, components/builder-http-gateway/Cargo.toml, components/builder-http-gateway/src/http/helpers.rs, components/builder-http-gateway/src/http/middleware.rs, components/builder-http-gateway/src/lib.rs
This adds support for fetching packages from an upstream depot, as you might have guessed from my clever and obscure PR title.
This is achieved through one new line of configuration in the `[depot]` section of `builder-api`'s config file:
```toml
[depot]
upstream_depot = "http://example.com"
```
This is optional, and it's disabled by default.  Some sites, e.g. public Builder, do not need an upstream.
The primary driver for this is on-prem depots and the need to install packages via `hab pkg install`.  Before `hab pkg install` actually installs packages, it tries to fetch the details for a package from the depot, both to see what the latest version is, and verify that it actually exists.  This is the place where the bulk of the action happens.
In the event that we fail to find the package …
=> Add support for fetching packages from an upstream depot

Cargo.lock, components/segment-api-client/Cargo.toml, components/segment-api-client/src/client.rs, components/segment-api-client/src/error.rs, components/segment-api-client/src/lib.rs
Convert the Segment API client to use APIClient as the base, in order to pick up the proxy support that is a part of APIClient.
=> Convert Segment to use APIClient for proxy support

components/builder-originsrv/habitat/config/config.toml
1-liner fix to properly set the jobsrv_enabled flag on origin server
=> Fix missing jobsrv_enabled flag in config

Makefile, components/builder-depot/src/server.rs
Specifically, via a URL query parameter if present, with a fallback to
the UserAgent header if not.
This is in support of including windows packages in the on-prem bootstrap archive.
=> Refactor the way targets are calculated.

components/builder-depot/src/server.rs
This change removes a costly check from show_package API call.  If we have valid metadata in originsrv for a package, we will assume that it's archive is in the correct location as well.  This will be a valid assumption as we move package storage to S3 shortly. We also don't need to re-check the target since we already pass it in to the OriginPackageGet call.
=> Remove archive check from show_package

CODEOWNERS
This reverts commit 1476bb0066a2c513a02217e373f9b8f248973a45, but has some
extra fixups since there was an intervening change
=> Add baumanj back to CODEOWNERS

support/builder/config.sh
Updates the dev env with more appropriate nginx timeouts and ups the body size limit for package uploads - this matches what we have in the builder on-prem.
=> Update dev env nginx timeouts

support/builder/config.sh
Removing the upstream config from the dev env.  While useful, it should be an explicit choice to enable it since it has potentially unexpected/undesired side effects during development.
=> Remove upstream from dev env

terraform/instances.tf
Fix up a case where base package install is missing in Terraform
=> Fix missing base package install in Terraform

terraform/scripts/create_bootstrap_bundle.sh
=> Remove core/hab-butterfly from list of packages to download

.studiorc, components/builder-api/habitat/default.toml, components/builder-depot/src/backend/s3.rs, components/builder-depot/src/config.rs, components/builder-minio/habitat/default.toml, support/builder/config.sh
A few tweaks to the S3 config / related scripts:
1. Simplify default Minio creds
2. Update bucket creation to be slightly more idempotent
3. Remove file upload of un-needed pem file to minio
4. Remove minio from build commands in dev env (not needed)
5. Tweak the default bucket name to be more consistent with other envs
6. Remove un-defined function call
7. Add a user.toml with updated certs for the minio in the dev env
8. Fix a compile warning in the S3 handler
9. Add some unit tests for the S3 config
=> Some tweaks to S3 config

components/builder-protocol/protocols/sessionsrv.proto, components/builder-protocol/src/sessionsrv.rs, components/builder-web/app/oauth-providers/index.ts, components/oauth-client/src/active_directory.rs, components/oauth-client/src/client.rs, components/oauth-client/src/lib.rs
There is no username in oidc for AD so we duplicate it for our oauth impl
=> Add new active directory provider

components/builder-api/habitat/default.toml, components/builder-depot/src/config.rs, support/builder/s3migrate.sh
A couple of minor tweaks here
1. downcased the backend enum so that in the default.toml's etc we don't have a camel-case "Aws" or "Minio".
2. Changes default.toml to match the default values in the rust component.
3. Most importantly, modifies the s3migrate.sh tool to use the s3bulk go tool.
=> Updates to S3migrate & tweaks to s3backend

components/builder-minio/habitat/config/config.sh, components/builder-minio/habitat/hooks/run
sourcing of the config script fails without bash because `source` is a bash built-in, this removes a need to source the config.
=> Corrects sourcing of config which fails under dash

.studiorc
See https://github.com/habitat-sh/habitat/issues/5172
This shouldn't be merged until https://github.com/habitat-sh/habitat/pull/5187
is released.
=> Remove workaround for broken `hab sup status <IDENT>`

components/builder-web/app/banner/banner.component.html
This change restores the banner that was in place prior to the base-plans refresh.
=> Restore the banner

terraform/instances.tf, terraform/variables.tf, terraform/volumes.tf
This removes the need for Terraform to attach a volume for artifacts to the API node.  
This should only be merged when the corresponding change in cloud-environments is also merged, and after validation is complete.
=> Update API node terraform for S3

components/builder-depot/src/server.rs, components/builder-http-gateway/src/http/helpers.rs, components/builder-originsrv/src/data_store.rs, components/builder-originsrv/src/error.rs, components/builder-originsrv/src/migrations/2018-06-13-213130_add_audit/down.sql, components/builder-originsrv/src/migrations/2018-06-13-213130_add_audit/up.sql, components/builder-originsrv/src/server/handlers.rs, components/builder-originsrv/src/server/mod.rs, components/builder-protocol/protocols/originsrv.proto, components/builder-protocol/src/error.rs, components/builder-protocol/src/originsrv.rs
This writes an entry into an `audit` table every time a package is promoted or demoted.  It includes the package, the channel, what type of operation (promote/demote), the source that triggered the promotion/demotion (hab CLI, Builder UI, unknown), and the user that triggered it.  It mostly follows the pattern of audit logs from jobsrv, with a few slight tweaks.
=> Add audit logs for package promotion and demotion

terraform/instances.tf, terraform/variables.tf
Add support for multiple API nodes (defaults to 2).  
This should be merged with the corresponding change in the cloud-environments repo.
=> Add support for multiple API nodes

terraform/scripts/foundation.sh
This made for unhappy VMs after a restart.
=> Mount drive to /mnt, NOT /hab

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml
This change adds the basic capability to rate limit calls to the builder API.  The default rate limit value is 1 req/sec.
=> Add config for rate limit

.travis.yml, components/airlock/plan.sh, components/builder-api-proxy/habitat-dev/plan.sh, components/builder-api-proxy/habitat/plan.sh, components/builder-db/tests/db/start.sh, components/builder-graph/habitat/plan.sh, components/builder-worker/habitat-dev/plan.sh, components/builder-worker/habitat/plan.sh, support/account_creation_report.sh, support/bash_completion.sh, support/builder/s3migrate.sh, support/ci/builder-base-plan.sh, support/ci/builder-dev-base-plan.sh, support/ci/builder-dev-plan.sh, support/ci/compile_libarchive.sh, support/ci/compile_libsodium.sh, support/ci/compile_zmq.sh, support/ci/fast_pass.sh, support/ci/lint.sh, support/ci/rust_tests.sh, support/ci/what_changed.sh, terraform/scripts/create_bootstrap_bundle.sh, terraform/scripts/install_base_packages.sh, test/builder-api/bin/cleanup-integration-tests.sh, test/shellcheck.sh, tools/bulk_promote/promote.sh, tools/hab-channel-list-pkgs/hab-channel-list-pkgs.sh, tools/ssh_helpers/airlock.sh, tools/ssh_helpers/generate-habitat-env-tmuxinator.sh
The first stage is to add the automation to run [`shellcheck`](https://www.shellcheck.net) in travis with all the errors suppressed. Then, in small, non-bombastic, PRs, fix the lints and remove the suppressions.
See https://github.com/habitat-sh/habitat/issues/4170
=> Automate running shellcheck (part 1)

support/ci/fast_pass.sh, support/ci/lint.sh, support/ci/rust_tests.sh, support/ci/what_changed.sh
Starting with the least risky changes, this is another bite-sized step towards https://github.com/habitat-sh/habitat/issues/4170.
This reverts the `shellcheck` suppressions in favor of actually fixing the lints.
=> Fix shellcheck lints for CI supporting scripts

components/airlock/plan.sh, components/builder-api-proxy/habitat-dev/plan.sh, components/builder-api-proxy/habitat/plan.sh, components/builder-graph/habitat/plan.sh, components/builder-worker/habitat-dev/plan.sh, components/builder-worker/habitat/plan.sh, support/ci/builder-base-plan.sh, support/ci/builder-dev-base-plan.sh, support/ci/builder-dev-plan.sh
Continuing with the second least risky changes, this is another bite-sized step towards habitat-sh/habitat#4170.
This reverts the shellcheck suppressions in favor of actually fixing the lints.
=> Fix shellcheck lints for plan files

components/builder-depot/src/server.rs, components/builder-http-gateway/src/http/helpers.rs, components/builder-originsrv/src/data_store.rs, components/builder-originsrv/src/error.rs, components/builder-originsrv/src/migrations/2018-07-02-232814_add_package_group_audit/down.sql, components/builder-originsrv/src/migrations/2018-07-02-232814_add_package_group_audit/up.sql, components/builder-originsrv/src/server/handlers.rs, components/builder-originsrv/src/server/mod.rs, components/builder-protocol/protocols/originsrv.proto, components/builder-protocol/src/originsrv.rs
I also added some new tables and functions for package auditing, which
effectively abandons the existing tables. This felt like the right move,
though, given the need for multiple auditing tables. Having one called
just "audit" seemed like a bad idea in hindsight. We can leave the old
stuff around for awhile and delete it later on down the road.
It's also worth noting that this code hasn't been tested yet. I spent the entire day trying to get builds working in my local dev env and couldn't.  If someone has builds working in their env, maybe they can test this, or alternatively, we could test it in acceptance.
=> Add auditing for job groups.

components/builder-jobsrv/src/data_store.rs, components/builder-jobsrv/src/migrations/2018-07-09-232521_query_tuning/down.sql, components/builder-jobsrv/src/migrations/2018-07-09-232521_query_tuning/up.sql
It was difficult to come up with a comprehensive set of slow queries to test, because we don't get enough activity for `pg_activity` to show much, unless the db is under a lot of strain, and it hasn't been lately.
One way to track this over time would be to install the `pg_stat_statements` extension, but I didn't do that here.  Instead, I mostly tackled the queries that were represented in the GH issue.
There are 2 main changes worth noting here:
* Switching from matching via a regular expression to using `LIKE` resulted in roughly a 2x speed increase
* Rather than converting from a string to an array on the fly for every record in a result set, creating the array column and pre-populating it ahead of time, and using that, resulted in roughly a 10x speed increase.
Closes …
=> Tune some queries to be a bit faster

Cargo.lock, components/builder-depot/src/backend/s3.rs, components/builder-depot/src/config.rs, components/builder-depot/src/lib.rs, components/builder-depot/src/server.rs, components/builder-protocol/src/originsrv.rs
Breaking config.toml update
---------------------------
There is a potential user-impacting breaking change included with this
change. That is, prior to this change an operator of a
`habitat/builder-api` service would override the default `targets`
section of their configuration with a form similar to this:
```toml
[[targets]]
architecture = "x86_64"
platform = "windows"
[[targets]]
architecture = "x86_64"
platform = "linux"
```
(Note that the above example is *exactly* the defaults for the service
and therefore it would be extremely unlikely to see this in the wild)
With this change, an operator would want to update their configuration
with a form similar to this:
```toml
targets = ["x86_64-linux", "x86_64-windows"]
```
Scope of breaking change
------------------------
Given how our …
=> [BREAKING/depot] Updates due to PackageTarget changes in habitat-sh/core#37

support/account_creation_report.sh, support/bash_completion.sh, support/ci/compile_libarchive.sh, support/ci/compile_libsodium.sh, support/ci/compile_zmq.sh
The antepenultimate step towards https://github.com/habitat-sh/habitat/issues/4170.
This reverts the shellcheck suppressions in favor of actually fixing the lints.
All of these exact changes have already been made in the the [habitat repo](https://github.com/habitat-sh/habitat).
=> Fix shellcheck lints for support scripts

components/builder-depot/src/server.rs
Running `hab bldr job status -o core` can display different results than `hab bldr job status GROUP_ID`, for a `GROUP_ID` that was recently created. This PR disables caching on responses for origin job group status queries, to align it with the response from a job group status queries. 
=> Don't cache response for origin job status

.travis.yml
https://blog.rust-lang.org/2018/07/10/Rust-1.27.1.html
(Note that no code was updated after running `cargo fmt`).
=> [ci] Update to Rust 1.27.1.

components/builder-db/tests/db/start.sh, terraform/scripts/create_bootstrap_bundle.sh, terraform/scripts/install_base_packages.sh, test/builder-api/bin/cleanup-integration-tests.sh
The final step to shellcheck 0.4.6. compliance in the builder repo!
Resolves https://github.com/habitat-sh/habitat/issues/4170
This reverts the shellcheck suppressions in favor of actually fixing the lints.
=> Fix shellcheck lints for miscellaneous scripts

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml, components/builder-depot/src/lib.rs
This PR is mostly about tuning the nginx cache.
* There's now a config directive that can be set to `false` to disable caching completely.
* If caching is enabled, and we want to clear the cache, we can do that with e.g. `curl -v -X PURGE -D - "https://bldr.habitat.sh/*"`
* The above command will only work when run from the API node itself, so internet randos can't purge our caches for us.
* Only 200, 301 and 302 responses are cached, and only for 10 minutes.  Previously, everything was cached indefinitely.
I don't have a ton of experience modifying nginx configuration files, so if I messed something up, I'm not surprised.  Please do let me know.
Unrelated, but I noticed an extraneous `BufWriter` in the rust code to write files that wasn't necessary, so I removed that.  I'm not sure if …
=> Nginx caching

components/oauth-client/src/a2.rs, components/oauth-client/src/client.rs, components/oauth-client/src/lib.rs
This change adds the backend for the A2 auth provider for on-premise builder.  The provider is essentially identical to the Okta provider that was used to successfully authenticate with A2 in a POC.
=> Add chef-automate auth provider for on-premise builder

components/builder-db/tests/db/start.sh
The `ps` command will justify the columns of its output with extra whitespace,
so a simple process substitution can result in the variable containing this
extra whitespace, which confuses `ps` when passed back as an argument. To avoid
this (and good practice in general), use the `read` command which strips
whitespace according to IFS. For example:
```
$ read -r good_pid < <(ps -p 690 -o 'ppid=')
$ echo "#$good_pid#"
#679#
$ bad_pid=$(ps -p 690 -o 'ppid=')
$ echo "#$bad_pid#"
$ ps -p "$good_pid"
PID TTY          TIME CMD
679 ?        00:00:16 runsvdir
$ ps -p "$bad_pid"
error: improper list
Usage:
ps [options]
Try 'ps --help <simple|list|output|threads|misc|all>'
or 'ps --help <s|l|o|t|m|a>'
for additional help text.
For more details see ps(1).
```
See …
=> Fix the assignment of the various PID variables in the db test script

components/builder-api-proxy/habitat/config/nginx.conf
proxy_cache_purge is only available in Nginx Plus version, so we can't use it.
=> Remove nginx cache purge option

components/builder-api-proxy/habitat/config/nginx.conf
Full transparency I have no idea how to test this. But this should check and bypass caching of files that are 0 byte in size.
=> Stops Nginx from caching 0 byte files

.bldr.toml
This adds some missing folders to watch for builder-api webhook builds. Also removes a reference to a non-existent folder.
=> Update bldr toml folders for builder-api

Cargo.lock, components/github-api-client/Cargo.toml, components/github-api-client/src/client.rs, components/github-api-client/src/error.rs, components/github-api-client/src/lib.rs
This migrates us away from a one-off, year old JWT crate to the current latest version of the original JWT crate.
=> Update JWT to use latest frank_jwt crate

Cargo.lock
This enables us to take advantage of https://github.com/habitat-sh/core/pull/46
=> Bump to new core revision

.studiorc, components/builder-api-proxy/habitat/hooks/health_check, components/builder-api-proxy/habitat/hooks/init, components/builder-api/habitat/hooks/health_check, components/builder-api/habitat/hooks/run, components/builder-datastore/hooks/init, components/builder-datastore/hooks/run, components/builder-jobsrv/habitat/hooks/init, components/builder-jobsrv/habitat/hooks/run, components/builder-minio/habitat/hooks/init, components/builder-minio/habitat/hooks/run, components/builder-originsrv/habitat/hooks/init, components/builder-originsrv/habitat/hooks/run, components/builder-router/habitat/hooks/run, components/builder-sessionsrv/habitat/hooks/init, components/builder-sessionsrv/habitat/hooks/run, components/builder-web/bin/build-css, components/builder-worker/habitat/hooks/run, test/shellcheck.sh
The builder version of https://github.com/habitat-sh/habitat/pull/5396
Pretty much all the changes are just double-quotes to suppress unwanted expansion. There is one legit bug (occurring in several places) that I've called out with a comment.
=> Fix a minor issue with finding the files to run shellcheck against

components/builder-depot/src/backend/s3.rs, components/builder-depot/src/error.rs
OK. This adds some validation to the s3 upload functions. After the upload future returns it's status we chain a combinator onto the returned future - we take the configured s3 bucket and key and check that the object exists before the upload function returns it's status.
=> Adds validation of minio write to s3 uploads

components/github-api-client/src/client.rs
Fixing a regression in JWT usage for github apps, which expects integer values for the issued and expiration timestamps, where we were encoding as strings.
=> Fix JWT token for github app

Cargo.lock, components/builder-core/src/api_client.rs, components/builder-http-gateway/Cargo.toml, components/builder-http-gateway/src/http/middleware.rs, components/builder-http-gateway/src/lib.rs, components/builder-worker/Cargo.toml, components/builder-worker/src/lib.rs, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/publisher.rs
Look at all the red in the cargo.lock! This change migrates builder-worker to use the reqwest based mini-api-client in builder.  builder-http-gateway is also updated.  With the change, builder is now completely decoupled from a dependency on the habitat repo. cargo.lock removes a couple of open-ssl related crates - hopefully this will resolve openssl related build issues that have been seen in dev branches.
=> Remove habitat_depot_client dependency from builder

components/builder-core/src/metrics.rs
=> Fix for Rust 1.28 incompatibility

Cargo.lock, components/builder-jobsrv/Cargo.toml, components/builder-jobsrv/src/error.rs, components/builder-jobsrv/src/lib.rs, components/builder-jobsrv/src/server/log_archiver/s3.rs
Mo mo mo more red in the cargo.lock!  This change ports jobsrv to use rusoto instead of aws-rust-sdk, which removes a bunch of deps, as well as consolidates S3 usage to the same set of crates across jobsrv and builder depot, and streamlines the code. This also removes the only known usage of a pre-1.0 serde as a bonus :)
=> Migrate jobsrv to rusoto

Cargo.lock, components/builder-core/src/api_client.rs, components/github-api-client/Cargo.toml, components/oauth-client/Cargo.toml
The grand finale (sort of) of the great Builder deps cleanup journey.. somewhat boring PR as it is mostly updated versions in the Cargo.lock, plus a couple of minor cleanups, which is exactly what we wanted :)
=> Update Cargo.lock to latest

support/ci/lint.sh
This change reimplements the `support/ci/lint.sh` program which tries to
ensure that any Rust code contributions were prepared with the `rustfmt`
tool. The CI invocation of this programs is identical to the prior
implementation, but there are several advantages to this new approach:
* Drop reliance on flags and options in `rustfmt` to better bridge any
future changes to the program. This program attempts to use `rustfmt`
closer to how a code editor would interact with the formatter.
* Update the exit code checking of `rustfmt`, which has slightly changed
over the last 12+ months.
* Drop any remaining references to `rustfmt` version checks. Our current
approach is to use the version of `rustfmt` which ships as a component
in Rustup alongside a Rust toolchain.
* Expose explicit modes of …
=> [ci] Reimplement lint.sh program for better resilience.

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/habitat/config/config.toml, components/builder-api/habitat/default.toml, components/builder-api/src/config.rs, components/builder-api/src/depot/server.rs, components/builder-api/src/handlers/integrations.rs, components/builder-api/src/lib.rs, components/builder-api/src/main.rs, components/builder-api/src/server/handlers.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/upstream.rs, components/builder-worker/src/lib.rs
This change cleans up the builder-api config - it creates a new api section to consolidate some of the old depot configs, as well as others on the root.  Some configs that are not needed (such as events_enabled, etc) are removed. This change also now leverages the features crate and a features_enabled config - job server and upstream enablement are now done via the features_enabled flags.  This gives us a bunch of headroom to add new optional features without adding new config booleans directly. 
=> Clean up builder-api config

components/builder-worker/src/runner/docker.rs, components/builder-worker/src/runner/mod.rs
This should resolve #353. That being said - I'm not 100% certain if this is a safe behavior or not. I would assume that it is since we never flush this token to disk or logs or the like. But, it's probably worth being aware that the token we generate for the workspace is the token we pass through to the export command.
=> Pass --auth to integrations for private packages

terraform/instances.tf, terraform/variables.tf
Add sup_release_channel var to control where Supervisor updates will be coming from.
Works in conjunction with updated cloud-environments infra.
=> Add sup_release_channel

components/builder-api/src/depot/server.rs
Remove path for an experimental API that is no longer needed
=> Disable experimental API

DEVELOPING.md
The root-relative location of the file is `support/builder/config.sh`.
=> Fix the path to config.sh in the dev docs

components/builder-api/habitat/hooks/run, components/builder-jobsrv/habitat/hooks/run, components/builder-originsrv/habitat/hooks/run, components/builder-router/habitat/hooks/run, components/builder-sessionsrv/habitat/hooks/run, components/builder-worker/habitat/hooks/run
When exported to a docker container `/bin/bash` is actually ash which
doesn't support arrays.
Fix for #608
=> Don't use arrays in run hooks

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/lib.rs, components/builder-api/src/main.rs, components/builder-api/src/server/error.rs, components/builder-api/src/server/framework/headers.rs, components/builder-api/src/server/resources/ext.rs, components/builder-api/src/server/resources/notify.rs, components/builder-api/src/server/services/github.rs, components/builder-api/src/server/services/mod.rs
This one is going to need a thorough review. It's not complicated but there's some weird stuff in here. The only thing that I think bears any significant explanation upfront is the changes to main.rs and lib.rs.
I'm sure @fnichol can do a better job explaining what we did than I can but I'll give you the 1k-ft view. Basically - adding in unecessary extern crate calls coupled with pub mod calls from the api library put cargo into a state where it was totally unable to compile some of the modules. Cargo would get confused because including those `pub mod` calls tricked it into a state where it couldn't determine whether the binary build or the library build required those crates. We removed and corrected the instantiation of the modules and refer to the lib.rs now as a crate rather than …
=> Converts github service to use actix

components/builder-api-proxy/habitat/config/nginx.conf
builder-api and buider-api-proxy are on different IPs when run in
containers.  Stop binding to only localhost
=> Allow builder-api to run on non-localhost

CODEOWNERS
The last match has the highest precedence. Without this change, @apriofrost is required to approve many PRs that may not have any UX changes, simply because of the ordering of lines in the file. See https://help.github.com/articles/about-codeowners/ for full details.
=> Adjust for correct precedence.

components/builder-worker/src/runner/mod.rs, components/builder-worker/src/server.rs
(NB: This will be easier to review with whitespace changes hidden)
These are misleading since the core implementation doesn't actually do what the
function names imply, so replace with more illustrative code on a per-platform
basis. Long-term, we should implement the appropriate windows FFI calls, but
the current situation is dangerously misleading.
See https://github.com/habitat-sh/core/blob/master/components/core/src/os/filesystem/windows.rs#L28-L34
=> Remove/replace set_{permissions,owner} calls which aren't supported on windows

components/builder-api/src/server/mod.rs, support/builder/config.sh
Minor tweak to exclude the "v1/status" calls from the logger, and set zmq to error logging in the dev config.
=> Tweak logger to exclude status call

components/builder-api/src/server/resources/notify.rs
Tweak the Github notification handler to not require an auth token - it was inadvertently added.
=> Don't auth webhook notification

components/builder-api/src/server/helpers.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, test/builder-api/src/channels.js, test/builder-api/src/packages.js
We no longer assume that the package target is "x86_64-linux" if it is not specified in by a valid target param, or in a parsable User Agent header on the request.  This resolves https://github.com/habitat-sh/builder/issues/612
=> Dont default target when not present

components/builder-api/src/config.rs, components/builder-api/src/server/resources/pkgs.rs
This updates the builder-api config to add Linux kernel2 target to the default set of supported targets.  Also a minor tweak to the error code we return when a target is un-supported. This resolves https://github.com/habitat-sh/builder/issues/613
=> Enable Linux kernel2 target

components/builder-api/src/config.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-core/src/target_graph.rs, test/builder-api/src/jobs.js, test/builder-api/src/misc.js
This change adds more enablement for Linux kernel2 targets - 1) enables kernel2 in the package graph 2) adds target awareness to the rdeps API 3) updates some tests.  
=> Enable linux kernel2 in target graph

components/builder-web/app/client/depot-api.ts
Since we removed default fallback to x86_64-linux for the package latest calls, we need to add explicit target to the caller. Until we have a more permanent solution that is being worked on, this tweak adds a default target of x86_64-linux to the web UI so that things can continue to function at parity.
=> Make latest calls work again

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs
Update a couple of APIs to not require a target param if the call is for a fully qualified ident.  This should help with being able to see package metadata for Linux kernel2 packages.
=> Don't require target for fully-qualified calls

components/builder-api/src/server/helpers.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/pkgs.rs, test/builder-api/src/channels.js, test/builder-api/src/packages.js
This reverts a change that was made to error out on some APIs if no target was explicitly specified (or parsable via User Agent) - this potentially breaks backward compatibility, so it is best to revert that change. Since we have now unblocked the paths for linux-kernel2 which was the original reason for making the change, we should be safe to do the revert.
=> Revert default target change

components/builder-minio/habitat/default.toml, components/builder-minio/habitat/hooks/post-run, components/builder-minio/habitat/plan.sh, test/shellcheck.sh
This was currently done by the provision.sh but this means if you
fire up the minio service you end up with an unconfigured instance.
This puts the config into a post-run hook (and means a docker 
exported habitat/builder-minio now comes up properly configured)
=>  Add post-run hook to create bucket in minio 

components/builder-api/src/server/resources/pkgs.rs
Update package download to explicitly set content type
=> Add content type to package download

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml
This change adds an option for gzip enablement at the origin, and defaults it to off.   Also defaults the cache option to off by default. 
=> Gzip off at origin; gzipping will be enabled at edge as needed

test/builder-api/test.sh
Travis runs have been failing because we are starting the tests even though a couple of services are still in down state initializing - this change makes it wait until all services are up.
=> Fix travis test failure

components/builder-api/src/server/authorize.rs
We need to check for builder account id when getting session name in order to remove un-needed backend call, and to remove spurious warning.
=> Check for bldr account id for session name

components/builder-jobsrv/src/server/handlers.rs
Currently builder only supports x86_64-linux targets, so we need to add in a check when a job is attempting to get scheduled.
=> Check target when triggering build job

Cargo.lock, components/builder-api/Cargo.toml
One more gzip related change - this turns off default gzip in actix by turning off default features in the Cargo.toml (which also removes a few un-needed dependencies from the Cargo.lock)
=> Turn off gzip in actix by removing default features

components/builder-api-proxy/habitat/config/habitat.conf.js, components/builder-api/src/server/framework/middleware.rs, components/builder-api/src/server/mod.rs, components/builder-web/README.md, components/builder-web/app/actions/oauth.ts, components/builder-web/app/client/builder-api.ts, components/builder-web/app/client/depot-api.ts, components/builder-web/app/origin/origin-page/origin-keys-tab/origin-keys-tab.component.ts, components/builder-web/bs-config.js, components/builder-web/habitat.conf.sample.js, components/builder-web/package-lock.json, components/builder-web/package.json
This change removes CORS support from builder-api and removes the configurability of the `habitat_api_url` setting. It also adds support for proxying Builder API services in development in order to work around this new restriction.
=> Remove CORS support

components/builder-api/src/server/framework/middleware.rs, components/builder-api/src/server/resources/profile.rs, components/builder-api/src/server/services/memcache.rs, components/builder-originsrv/src/server/mod.rs, components/builder-originsrv/src/server/session_handlers.rs, components/builder-protocol/protocols/originsrv.proto, components/builder-protocol/src/originsrv.rs
This change moves session token validation to the edge rather than routing messages all the way back to originsrv.
Performance city - here we come - CHOO CHOO
=> Cache session tokens in memcache rather than a hashmap in originsrv.

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/services/memcache.rs
This change updates the cache strategy for channel packages.  Previously we were caching only the origin package object, however that still left some backend calls uncovered. This change caches the full json response.
=> Update caching strategy for channel packages

components/builder-web/app/origin/origin-page/origin-integrations-tab/origin-integrations-tab.component.html
I can’t say I’m completely sure _why_ Angular Material is canceling the `click` event in Chrome for these buttons, but it is &mdash; so this fix has them use the `mouseup` event instead.
=> Use mouseup for Integration buttons

components/builder-web/app/origin/origin-page/origin-keys-tab/origin-keys-tab.component.ts
With the recent API framework changes, the `Content-Disposition` header sent back with the call to `/depot/origins/:origin/secret_keys/latest` was modified slightly, causing the download button (which parses the header value to obtain a proper filename) to fail. This fixes that.
https://tools.ietf.org/html/rfc6266#section-5
Fixes #668.
=> Fix private-key downloads in the UI

components/builder-api/src/server/framework/middleware.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/services/memcache.rs
We are missing a target in memcache package calls, hence we can return the wrong package.
=> Add target to memcache calls

components/builder-minio/habitat/plan.sh
Resolves https://github.com/habitat-sh/builder/issues/676
=> Make builder-minio version consistent with other bldr svcs

components/builder-api/src/server/resources/pkgs.rs
Add a target check during download - placeholder until we can update retrieval of OriginPackage.
=> Check target during download

components/builder-api/src/server/models/channel.rs, components/builder-api/src/server/models/mod.rs, test/builder-api/src/channels.js
Fun fact: your browser can't handle 64 bit integers even though they are completely valid in json.
2nd fun fact: all of our db IDs are 64 bit integers.
Previously we implemented the serialize trait for each message struct that would get sent over the wire that converted u64 to string.
I hvae written a serialize function that you can use as a decorator in your structs to tell serde to convert an i64 to string.
Ex:
```
use server::model::db_id_format;
struct Foo {
#[serde(with = "db_id_format")]
id: i64,
name: String,
#[serde(with = "db_id_format")]
owner_id: i64,
}
//initialize foo
json!(foo) -> renders quoted i64
```
=> Fix id serialization for channel ID's coming from the database

components/builder-api/src/config.rs, components/builder-api/src/server/mod.rs
The config wasn't being picked up from the config.toml due to a
mismatch between the section name in the toml (`memcache`) and the
key in the `Config` structure in `config.rs` (`memcached`).
Thinks were silently working due to the default being localhost:11211.
This showed up on k8s where `sys.ip` for memcached is different from
the host that builder-api is running on.
Added a test case for config.rs and consolidated on `memcache` as the name
that should be the section header.
=> Fix to actually use the [memcache] section from config.toml

components/builder-core/src/metrics.rs, components/builder-jobsrv/src/data_store.rs, components/builder-jobsrv/src/migrations/2018-09-26-223537_count_jobs/up.sql, components/builder-jobsrv/src/server/metrics.rs, components/builder-jobsrv/src/server/mod.rs, components/builder-jobsrv/src/server/scheduler.rs, components/builder-jobsrv/src/server/worker_manager.rs
This PR adds several statsd metrics to job server, including job completion time, waiting jobs, working jobs, etc. This will allow us to have better visibility on the job server, as well as ability to add alerting on the job waiting queue.
=> Add job metrics

CODEOWNERS
Awhile back, I submitted a PR to rearrange these lines so that the most specific ones (for UX and docs people) went first, and the most generic ones went last.  I did that because [the GH docs for the CODEOWNERS file](https://help.github.com/articles/about-codeowners/) mentions that the last match wins.  With the most specific lines last, PRs were requiring review from e.g. @apriofrost, simply because one of the files she's tagged on had a change, even though there was no UX related change in the file.  The only way to merge a PR in that state was to use admin privs to override it.
I thought this was a bad idea and set about to rectify it by making the most generic tagging the last one.  Those of you that are smarter than me have already realized the flaw in this logic, though, which is …
=> Rearrange lines again, because I'm dumb

components/builder-api/src/server/handlers/account.rs, components/builder-api/src/server/handlers/mod.rs, components/builder-api/src/server/models/account.rs, components/builder-api/src/server/models/mod.rs, components/builder-api/src/server/resources/profile.rs, components/builder-api/src/server/schema/account.rs, components/builder-api/src/server/schema/mod.rs
Initial merge of originsrv  account handling into api. Migrates only get_account and update_account though plumbing for others exists in the PR as well.
=> DB Merge - Accounts (profile)

components/builder-api/src/server/handlers/channel.rs, components/builder-api/src/server/models/channel.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/services/memcache.rs, components/builder-core/src/integrations.rs
This update adds a channel namespace to memcache. This allows the packages in a particular origin/channel to be invalidated when a channel is deleted.
Resolves https://github.com/habitat-sh/builder/issues/691
=> Invalidate package cache on channel deletion

components/github-api-client/src/client.rs, components/github-api-client/src/metrics.rs
Minor tweak to remove un-used GH metric, and convert the other two to a simpler enum type.
Resolves https://github.com/habitat-sh/builder/issues/281
=> Tweak github api metric usage

components/builder-api/habitat/hooks/run
Adding a service startup event datadog event to builder-api.  This will be expanded to the other services eventually after we try this out in acceptance and prod.
=> Add datadog service startup event

components/builder-router/src/server/handlers.rs, components/builder-router/src/server/mod.rs
This change removes all knowledge of shards from builder-router.  This is mostly removal of left-over dead code without any functional change.
=> Remove shard usage from router

components/builder-protocol/protocols/routesrv.proto, components/net/src/app/config.rs, components/net/src/app/mod.rs, support/builder/config.sh
Remove leftover shard code from net/app.  Also makes a minor tweak to change the number of default workers to cpu * 2, instead of cpu * 8.
=> Remove shards from application

components/builder-web/app/origin/origin-page/origin-job-detail/origin-job-detail.component.html, components/builder-web/app/package/job-list/job-list.component.html, components/builder-web/app/package/job-list/job-list.component.spec.ts, components/builder-web/app/shared/dialog/job-cancel/job-cancel.dialog.html
The wording we’re using now is a bit inconsistent; this uses the word “remaining” to include jobs that have either not yet begun or are in progress, and changes the Cancel button to use something other than “cancel”, because the thing you’re confirming happens to be a cancellation.
Also ensures we animate the icon in the jobs list when applicable.
=> Clarify the wording around job cancellation

terraform/templates/hab-sup.service
Ideally, we would use `ExecStop` to issue a `hab sup term`
command. However, according to the [documentation](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStop=),
the command specified for `ExecStop` should be a synchronous one;
currently `hab sup term` is _not_ synchronous.
Additionally, I have noticed issues shutting down services via
`systemd`, where the Launcher itself is not shutting down, but
individual Habitat services get killed and restarted. Then, 90 seconds
later, `systemd` determines that the stop didn't take, and it brutally
kills everything.
A bit of digging shows that we can specify [KillMode](https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=)
to control how `systemd` terminates our process. The default is …
=> Shut down a Supervisor properly in systemd unit file

components/builder-api/src/server/models/invitations.rs, components/builder-api/src/server/models/mod.rs, components/builder-api/src/server/resources/user.rs, components/builder-api/src/server/schema/invitation.rs, components/builder-web/app/client/builder-api.ts, test/builder-api/src/invitations.js
This breaks the existing API by removing the `invitations` key for the list of invitations
=> Convert user invitations to Direct DB access

.travis.yml, components/builder-api/src/config.rs, components/builder-api/src/server/mod.rs, components/builder-protocol/src/originsrv.rs
https://blog.rust-lang.org/2018/09/25/Rust-1.29.1.html
=> [ci,rustfmt] Formatting due to rustfmt-0.99.1-stable in Rust 1.29.1.

terraform/security-groups.tf
Small tweak to add the jobsrv RPC port ingress to the jobsrv security group.
=> Add AWS security group for jobsrv RPC port

components/builder-originsrv/src/migrations/2018-10-10-198563_enum_visibility/up.sql
=> Trim trailing ':' from all text arrays in sql migrations

.travis.yml, test/shellcheck.sh
Updates to Travis to remove un-needed components. The main items removed are the apt-based packages, as we do not need them for builder services where we are only doing end-to-end tests in a studio-based environment.
=> Travis update to remove un-needed components

components/builder-api/src/server/error.rs, components/builder-api/src/server/resources/projects.rs, components/builder-db/Cargo.toml, components/builder-db/src/models/mod.rs, components/builder-db/src/models/package.rs, components/builder-db/src/models/project_integration.rs, components/builder-db/src/models/projects.rs, components/builder-db/src/schema/project.rs, components/builder-db/src/schema/project_integration.rs, support/builder/config.sh
This change migrates the project-related APIs over to direct DB calls.
=> Convert origin projects to direct DB calls

components/builder-db/src/models/integration.rs, components/builder-db/src/models/mod.rs, components/builder-db/src/schema/integration.rs
A small PR to add in a db model for origin integrations.  This will get used later by builder-api and jobsrv.
=> Convert origin integrations to direct db

components/builder-api/src/server/services/memcache.rs
We were seeing cases where the keys were too long on get requests.
This removes the unwraps that were causing a panic and replaces them with
a warn.
=> Don't unwrap memcache calls

components/builder-db/src/models/origin.rs, components/builder-db/src/schema/origin.rs, test/builder-api/src/keys.js
This fixes a regression where we were not returning the private key name with the origin request, thereby causing the UI to not account for keys properly.  Also adds an e2e test for this scenario.
=> Fix regression; return private key name with origin

Cargo.lock, components/builder-db/src/models/project_integration.rs, components/builder-db/src/models/projects.rs, components/builder-jobsrv/Cargo.toml, components/builder-jobsrv/src/error.rs, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/mod.rs, components/builder-jobsrv/src/server/scheduler.rs, components/builder-jobsrv/src/server/worker_manager.rs
This is the first part of the migration of job server to db model usage. This PR adds the infra to hook into the db model to jobsrv, and migrates several of the router-based calls to direct DB.
=> Migrate job server to direct DB - initial infra and partial migration

components/builder-api/src/server/resources/origins.rs, components/builder-db/src/models/integration.rs, components/builder-db/src/models/keys.rs, components/builder-db/src/models/mod.rs, components/builder-db/src/models/origin.rs, components/builder-db/src/models/secrets.rs, components/builder-db/src/schema/key.rs, components/builder-db/src/schema/mod.rs, components/builder-db/src/schema/secrets.rs, test/builder-api/src/keys.js
This PR converts origin encryption keys and origin secrets to direct DB, and also does some cleanup on the models.
=> More conversions to direct DB

components/builder-api/src/server/error.rs, components/builder-api/src/server/resources/origins.rs, test/builder-api/src/keys.js
Fix a couple of key related breakages - return expected status code for conflict, and do a better encoding for content disposition for key download.
=> Fix keys breakage

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/resources/projects.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/projects.rs, components/builder-db/src/schema/audit.rs, components/builder-db/src/schema/project.rs, components/builder-originsrv/src/migrations/2018-10-31-233453_more_enums/down.sql, components/builder-originsrv/src/migrations/2018-10-31-233453_more_enums/up.sql
Fix a breakage in group project promote/demote and convert Project visibility to an enum
=> More direct DB migration for Project and fix for group promote/demote

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/lib.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/Cargo.toml, components/builder-db/src/lib.rs, components/builder-db/src/models/package.rs, components/builder-db/src/schema/package.rs, components/builder-originsrv/src/migrations/2018-11-01-111111_full_text_search/up.sql, test/builder-api/src/packages.js
Move search into a direct db diesel query. Unfortuantely there are some trait bound
issues that prevents us from merging search and search_distinct into the same function.
Ignore the duplication and you'll be just fineeee.
=> Redo search from the ground up using full text search

components/builder-api/src/server/helpers.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/resources/projects.rs, components/builder-db/src/models/package.rs
The last migration.  With this change, all tests pass without originsrv and router running.
=> Migrate platform helper to direct DB

Cargo.lock, components/builder-api/src/server/authorize.rs, components/builder-api/src/server/framework/middleware.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/origins.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/resources/profile.rs, components/builder-api/src/server/resources/projects.rs, components/builder-api/src/server/resources/user.rs, components/builder-api/src/server/services/memcache.rs, components/builder-db/Cargo.toml, components/builder-db/src/lib.rs, components/builder-db/src/models/account.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/integration.rs, components/builder-db/src/models/invitations.rs, components/builder-db/src/models/keys.rs, components/builder-db/src/models/origin.rs, components/builder-db/src/models/package.rs, components/builder-db/src/models/project_integration.rs, components/builder-db/src/models/projects.rs, components/builder-db/src/models/secrets.rs
This PR makes a few key improvements to open up perf for the direct DB builder API.  Since getting a DB connection/making a DB call are blocking operations, we need to ensure we avoid those in the high volume paths. With the changes here, we are able to serve all high volume calls (including authentication/authorization via personal access tokens) without hitting the DB.  Leveraging memcache for origin membership also allows us to make some other key simplifications. Finally, counter metrics are added for every DB API in the builder-db models.
=> Perf and monitoring improvements to builder-api

components/builder-api/src/server/services/memcache.rs, components/builder-api/src/server/services/metrics.rs
Adds trace and metrics for memcache get calls. Also disables Nagle's algorithm in the memcache client which results in a significant perf gain (client calls go from around 47ms to ~0ms).
=> Add memcache timing metric, etc

terraform/files/mcache.yaml, terraform/instances.tf
Updates the Terraform scripts to add sending of memcache stats from the api node to Datadog.
=> Terraform - add memcache stats to datadog

components/builder-db/src/models/secrets.rs, components/builder-db/src/schema/secrets.rs
This fixes a regression where origin secrets list was failing, due to a Diesel trying to map a null owner_id. Currently we don't write out the owner id for secrets, so that column is unused.
=> Fix list secret regression

Cargo.lock, components/oauth-client/Cargo.toml, components/oauth-client/src/client.rs, components/oauth-client/src/lib.rs, components/segment-api-client/Cargo.toml, components/segment-api-client/src/client.rs, components/segment-api-client/src/lib.rs
This PR improves http/https proxy support in builder.  It uses the env_proxy crate to determine the proxy settings, which takes no_proxy into account. The use case is primarily for on-prem builder.
=> Better proxy support for builder-api

components/builder-api/src/server/resources/channels.rs, components/builder-db/src/migrations/2018-11-06-444444_unique_account_id/up.sql, components/builder-db/src/models/account.rs, components/builder-db/src/models/channel.rs
Personal account tokens were able to be duplicated. This change adds a constraint to disallow account_ids with multiple tokens
Channels list now returns sandbox channels correctly
=> Fix channels list logic and PAT token generation

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/resources/profile.rs, components/builder-api/src/server/resources/projects.rs, components/builder-api/src/server/resources/user.rs, components/builder-web/app/origin/origins-page/origins-page.component.ts, components/builder-web/app/shared/project-settings/project-settings.component.ts
=> Cleanup errors and add body to error response

components/builder-web/app/shared/project-settings/project-settings.component.html, components/builder-web/app/shared/project-settings/project-settings.component.ts
This minor change modifies the messaging displayed above the plan-connection view based on whether or not a GitHub app has been installed and configured.
=> Present appropriate GitHub app messaging

components/builder-web/app/origin/origin-page/origin-job-detail/origin-job-detail.component.html, components/builder-web/app/origin/origin-page/origin-page.component.html, components/builder-web/app/origin/origins-page/_origins-page.component.scss, components/builder-web/app/origin/origins-page/origins-page.component.html, components/builder-web/app/origin/origins-page/origins-page.component.ts, components/builder-web/app/package/package-sidebar/package-sidebar.component.html, components/builder-web/app/package/package-sidebar/package-sidebar.component.spec.ts, components/builder-web/app/package/package-sidebar/package-sidebar.component.ts, components/builder-web/app/package/package/package.component.html, components/builder-web/app/package/package/package.component.spec.ts, components/builder-web/app/package/package/package.component.ts, components/builder-web/app/reducers/origins.ts, components/builder-web/app/shared/shared.module.ts, components/builder-web/app/shared/visibility-icon/visibility-icon.component.ts, components/builder-web/app/shared/visibility-selector/visibility-selector.component.html
This change adds package-visibility icons on the origin and package views to indicate more clearly whether a package is (or would be) public or private. It also adds a couple of bits of information to the package sidebar to reflect the connected GitHub repository and whether automatic rebuilds are enabled.
Fixes #480
=> Display visibility settings more prominently in general

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs
This change improves the perf on the channel package call by removing the internal fanout of calls that were being made to retrieve channels and platforms. Instead, it leverages the new packages_with_channel_platform view to perform the same operation.
=> Remove fanout for channel package call

components/builder-core/src/rpc.rs, test/builder-api/src/jobs.js
Small fix to correctly pass back RPC errors to the caller - this fixes some minor issues where we were not returning error codes correctly (eg, returning error 500 instead of 404 on job logs, etc).  Also adds a couple of tests to catch those scenarios.
=> Fix handling of RPC errors

components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/models/package.rs
Another perf update to remove fan out from non-channel package get calls.
=> Remove fan-out for package get calls

components/builder-db/src/migrations/2018-11-15-202231_update_packages_list/up.sql, test/builder-api/src/channels.js
This fixes an issue where we are showing multiple versions of the same package in the UI. The root cause is duplicate rows in the packages view, which is resolved by updating the view defn.  A new test is added to catch this scenario in the future.
=> Update packages view to only show distinct rows

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/metrics.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs
With this PR we go back to using the regular package table instead of the combined package-channels-platform view for the latest package calls due to the perf penalty on the view.  This change also adds a new metric to start tracking DB call times.
=> More perf tuning

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/lib.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/services/memcache.rs
A trio of memcache related bug fixes : 1) we now use a random 64-bit number instead of epoch time seconds as a namespace key 2) no longer incorrectly flush memcache on namespace reset 3) fix json deserialization for package fetch
=> Memcache related bug fixes

components/builder-db/src/models/package.rs
Version sorting is broken - we need to use semver instead of lexicographic sort.
=> Sort version list using semver

terraform/security-groups.tf, terraform/templates/hab-sup.service
This update increases the open file limit settings in order to allow builder-api to run at higher handler counts without running into the "too many open files" error.  Also adds a security group to allow memcache instances to communicate.
=> Increase open file limit for builder-api

components/builder-api-proxy/habitat/config/nginx.conf
We had inadvertently changed the nginx config to add all the builder-api nodes as upstream servers. That is not correct for our current topology which installs nginx on each api node. This change reverts us back to having a single upstream (with a small change to always use the system IP instead of the bind IP).
=> Only route to single upstream

components/builder-web/app/app.component.ts
A recent Angular upgrade must’ve expanded the kinds of events dispatched by the Angular router, breaking post-sign-in redirection. This limits the dispatch of navigation events to navigation-related events.
Fixes #817 
=> Only dispatch route-change events on navigation

components/builder-api/src/server/authorize.rs, components/builder-api/src/server/resources/channels.rs
This fixes a bug where we are not able to find private packages during a Builder build.
=> Bug fix for private package builds

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/lib.rs, components/builder-api/src/server/services/github.rs
This unifies the feature we use across different repos and provides a slightly
nicer interface.
=> Replace rust-crypto crate's fixed_time_eq with core's secure_eq

components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/projects.rs, components/builder-db/src/models/jobs.rs, components/builder-db/src/models/mod.rs, components/builder-db/src/schema/jobs.rs, components/builder-db/src/schema/mod.rs, components/builder-jobsrv/src/data_store.rs, components/builder-jobsrv/src/error.rs, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/mod.rs, components/builder-protocol/protocols/jobsrv.proto, components/builder-protocol/src/jobsrv.rs
Initial job schema migration - this PR creates the jobs schema, and migrates a couple of calls over to use direct to DB instead of RPC calls.
=> Jobs schema migration start

components/builder-datastore/default.toml, components/builder-datastore/hooks/init
In a container based deployment scenario you need to set the password
externally so you can pass it to all containers that need it. This
enables that while maintaining the existing behaviour as the default.
=> Allow setting of datastore superuser password via config

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml
This flag `enable_ipv6` allows service providers to provision bldr on
hosts that do not support ipv6.  By default, bldr will attempt to bind
to ipv6.
closes #875
Signed-off-by: Ben Dang <me@bdang.it>
=> Flag to disable/enable ipv6 binding

components/builder-api/src/server/services/memcache.rs
Update memcache client API usage to fix build break with memcache 0.11
=> Update memcache client API usage

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml
This allows the builder api and api-proxy services to be different hosts (or containers/pods)
=> Use the IP address of API service, not my sys.ip in backend block

components/builder-worker/habitat/config/config.toml, components/builder-worker/habitat/default.toml, components/builder-worker/habitat/hooks/run.ps1, components/builder-worker/habitat/plan.ps1, components/builder-worker/src/config.rs, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/studio.rs, components/builder-worker/src/runner/util.rs, components/builder-worker/src/runner/workspace.rs, components/builder-worker/src/server.rs, components/builder-worker/src/vcs.rs, components/github-api-client/src/client.rs
This change adds a Windows plan, run hook, and updates the runner and associated infrastructure to enable a Windows version of the builder-worker package that can generate builds end-to-end.
This is a first step - the Windows studio currently only runs locally and does not support Airlock. Subsequent changes will enable further isolation. Airlock configuration is also now disabled by default.
=> Windows builder-worker enablement

components/builder-api/habitat/default.toml, components/builder-api/src/config.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/models/jobs.rs, components/builder-db/src/schema/jobs.rs, components/builder-jobsrv/src/data_store.rs, components/builder-jobsrv/src/migrations/2019-01-23-202244_windows-workers/up.sql, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/scheduler.rs, components/builder-jobsrv/src/server/worker_manager.rs, components/builder-protocol/protocols/jobsrv.proto, components/builder-protocol/src/error.rs, components/builder-protocol/src/jobsrv.rs, support/builder/config.sh, test/builder-api/src/jobs.js
This change updates key Builder services (api, jobsrv, worker) to plumb in build targets and orchestrate builds of multiple build targets through the system. A new config has been added to the builder-api to be able to enable/disable build targets.
Currently, non-Linux builds can only be kicked off via the API (cli support via the hab command line is in progress, and UI changes will follow later).
=> Update Builder services for Windows build target

components/builder-api/habitat/default.toml, components/builder-api/src/config.rs, components/builder-api/src/server/resources/pkgs.rs
This adds a config to let us turn off the auto-build on package upload functionality. This is useful in cases where we are expecting a large number of uploads we don't want to trigger builds for - eg, base plan refreshes.
=> Add config for build_on_upload

components/builder-worker/src/runner/mod.rs
Fix a missed case where the studio build results are in different locations on Windows vs. Linux builds
=> Fix to account for different build paths

components/builder-minio/README.md, components/builder-minio/docker-compose.yml, components/builder-minio/habitat/config/hook-helper.sh, components/builder-minio/habitat/config/restart-hook.txt, components/builder-minio/habitat/default.toml, components/builder-minio/habitat/hooks/post-run, components/builder-minio/habitat/hooks/reconfigure, components/builder-minio/habitat/hooks/reload, components/builder-minio/habitat/hooks/run, components/builder-minio/habitat/plan.sh, test/shellcheck.sh
This change completely reworks minio:
* Fix ssl certs not always copied on change
* Fix ssl cert name private.crt -> public.crt
* Add standalone mode (defualt)
* Add automatic cluster mode (using habitat discovery)
* Add explicit cluster mode
* Smart reload/restart service on config changes
Added docker-compose.yml for test.
Signed-off-by: Yauhen Artsiukhou <jsirex@gmail.com>
=> Make builder-minio clustered

components/builder-worker/src/runner/studio.rs
Accomodate plan.ps1 as a valid build path in a project. We can run into this case if the builder project is created initially with a plan.ps1 file.
=> Parse plan.ps1 in build path

Cargo.lock, components/builder-protocol/src/jobsrv.rs
Remove impl Default for JobState since it's now part of the protobuf-generated code.
See https://github.com/stepancheg/rust-protobuf/commit/166966627ebc1e5ce650acd1593489e52757178e
=> cargo update

components/builder-api/src/server/services/github.rs, components/builder-core/src/build_config.rs, components/github-api-client/src/client.rs, components/github-api-client/src/types.rs
This change adds target awareness to the github hook handlers - which allows us to auto schedule Windows builds in addition to Linux builds.  Support for Linux2 will be added in a follow up change.
=> Add target awareness to github webhook handling

components/builder-api/doc/api.raml, components/builder-api/src/server/resources/jobs.rs, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/mod.rs, components/builder-protocol/protocols/jobsrv.proto, components/builder-protocol/src/jobsrv.rs
This change adds a new reverse dependency API that returns the rdeps collated into build groups that can be built in parallel.  This API is a step toward opening up the builder platform to integrate further with external systems.
=> Add reverse dependency grouping API

terraform/instances.tf, terraform/variables.tf
As of hab 0.74 we no longer support Supervisor events - this PR removes events usage from Builder services.
=> Remove Supervisor events in Terraform

components/builder-web/app/origin/origin-page/origin-job-detail/origin-job-detail.component.html, components/builder-web/app/origin/origin-page/origin-job-detail/origin-job-detail.component.ts, components/builder-web/app/shared/dialog/job-cancel/job-cancel.dialog.html, components/builder-web/app/shared/dialog/job-cancel/job-cancel.dialog.ts
When fixing the link part of #819 and running build after build. I never saw the cancel button surface. Following the logic, I think we want the cancel button to show up when build jobs are in progress. Currently, the cancel button is set to surface when jobs are `Pending`. We could also make it surface for both `InProgress` and `Pending`, happy for some direction as the page also currently says `Cancel Remaining Jobs` and the mocks say `Cancel Unfinished Jobs`.
Signed-off-by: shadae <sholmes@chef.io>
=> Fix cancel job groups button to show up when jobs are in progress and pending

terraform/templates/windows_worker_user_data
This drops all TCP traffic from the docker NAT network to the local 10.* ethernet network as well as the NAT default gateway which resolves to the local host. It also blocks all non DNS UDP traffic.
Ideally I would have one rule that blocks everything between those endpoints and than an allow rule for UDP 53 between the docker NAT and its DNS servers but thats not possible with how the windows firewall works. It does not process rules in order but applies the deny rules first and if it finds a match it does not override any allow rules.
=> adds firewall rule to windows worker hardening docker network

components/builder-jobsrv/src/server/worker_manager.rs, components/builder-protocol/protocols/jobsrv.proto, components/builder-worker/habitat/config/config.toml, components/builder-worker/habitat/default.toml, components/builder-worker/src/config.rs, components/builder-worker/src/heartbeat.rs, components/builder-worker/src/server.rs
This change adds a target field to build worker heartbeats. This is in readiness for new Windows and Linux2 build workers.
=> Add target to worker heartbeats

components/builder-api/src/server/services/github.rs
Add a missed check for enabled build targets when kicking off webhook-triggered builds
=> Add check for build_target when triggering web hook

components/builder-worker/habitat/x86_64-linux-kernel2/plan.sh, components/builder-worker/src/runner/mod.rs
This updates builder-worker to check the PackageTarget for supported platforms (x86_64-linux, x86_64-windows) before attempting a docker export of a package, if exports are enabled.  It also introduces a plan variant for x86_64-linux-kernel2 with the docker dependencies removed. 
The `use` statements for the docker export code are still present for the x86_64-linux-kernel2 builds, which contain a `lazy_static!` to determine the path to the `docker` command and `hab-pkg-export-docker` command. If I understand that correctly, that will be evaluated at run-time, which introduces a potential point of failure at run-time as those packages won't be present.  Looking at existing code, it should never be executed, however I'd feel safer if there was a way to not import that module based on the …
=> Check PackageTarget before attempting docker export

components/builder-db/src/models/jobs.rs, components/builder-jobsrv/src/server/metrics.rs, components/builder-jobsrv/src/server/scheduler.rs, components/builder-jobsrv/src/server/worker_manager.rs
This change updates the job server to start sending per-target job metrics to statsd
=> Update jobsrv metrics with targets

components/builder-worker/src/runner/mod.rs
Hab 0.74 has fixed an issue that caused the Windows build path to be different than the Linux path. This means we can now remove the special case that was added to the build worker.
=> Remove special case build path for Windows worker

components/builder-jobsrv/src/server/worker_manager.rs, components/builder-worker/src/heartbeat.rs
Reduce verbosity of some of the jobsrv/worker debug output
=> Tweak a couple of debug traces

components/builder-jobsrv/src/server/handlers.rs
Quick fix to address a case where we are not handling an empty rdep list in the new grouped rdeps API
=> Handle empty rdep list

components/builder-worker/src/runner/job_streamer.rs, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/studio.rs, components/builder-worker/src/server.rs
This change fixes the build worker job cancellation handling. Instead of force exiting the worker process, which left orphaned child processes running, this change lets the worker kill only the studio process directly, which cleans up the studio process as expected.
=> Improved job cancel

components/builder-api/src/server/resources/origins.rs, components/builder-core/src/access_token.rs, components/builder-core/src/integrations.rs, components/builder-jobsrv/src/server/worker_manager.rs
This change fixes some backward compatibility breakages that inadvertently happened while moving to a new crypto data type.
=> Fix crypto compatibility

support/ci/builder-base-plan.sh
We need to add in a PLAN_PACKAGE_TARGET env variable for Habitat builds to correctly pick up the target when building Linux2 packages (eg, builder-worker)
=> Add PLAN_PACKAGE_TARGET to ensure packages are built with correct target

components/airlock/Cargo.toml, components/builder-api/Cargo.toml, components/builder-core/Cargo.toml, components/builder-db/Cargo.toml, components/builder-jobsrv/Cargo.toml, components/builder-protocol/Cargo.toml, components/builder-worker/Cargo.toml, components/github-api-client/Cargo.toml, components/oauth-client/Cargo.toml, components/segment-api-client/Cargo.toml
The current values are inconsistent and don't accurately reflect the real authors of the current code.
=> Set Cargo.toml authors = ["The Habitat Maintainers <humans@habitat.sh>"]

Cargo.lock, components/builder-worker/src/runner/studio.rs
See https://github.com/habitat-sh/habitat/issues/6168
Also https://github.com/habitat-sh/core/pull/119 must merge before CI will pass for this PR
Now that `ChannelIdent` implements the `env::Config` trait, we can use the standardized constant name.
=> Update reference to ChannelIdent override environment variable

components/builder-worker/habitat/x86_64-linux-kernel2/plan.sh, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/studio.rs
Update builder-worker to run Linux2 builds with a Docker-based studio.  
=> Run Linux2 build with Docker Studio

terraform/instances.tf
The last piece of the puzzle for Linux2 builder - this enables the firewall on the node so that the Docker iptables additions function as expected.
=> Enable firewall for Linux2 worker

components/builder-worker/src/runner/mod.rs
Fix some incorrect cases for airlock enablement in builder worker
=> Bug fix for builder-worker

.bldr.toml, components/builder-api/src/server/services/github.rs, components/builder-core/src/build_config.rs, components/github-api-client/src/types.rs
This change adds support for build targets in the bldr.toml file.  If no build_targets are specified explicitly, we default to X86_64_LINUX and X86_64_WINDOWS.  Therefore, in order to build Linux Kernel2 packages via github push, that build target will need to be explicitly specified in a bldr.toml. This decision is because we expect most plans will NOT need to automatically build Kernel2 packages.
=> Add build_targets to bldr toml

components/builder-worker/build.rs, components/builder-worker/habitat-dev/plan.sh, components/builder-worker/habitat/plan.ps1, components/builder-worker/habitat/plan.sh, components/builder-worker/habitat/x86_64-linux-kernel2/plan.sh, components/builder-worker/src/runner/studio.rs
This change locks the version of the hab cli that is used to execute the studio for the Linux2 and Windows build workers. Also a similar change for the Windows docker exporter. This brings things in line with how we are operating with the Linux worker.
=> Update builder-worker to use hardcoded hab / docker exporter

components/builder-db/src/models/jobs.rs, components/builder-jobsrv/src/config.rs, components/builder-jobsrv/src/server/mod.rs, components/builder-jobsrv/src/server/scheduler.rs, components/builder-jobsrv/src/server/worker_manager.rs
This change updates the job scheduler to process work per target. This fixes the case where not having available build workers for a given target can stall builds from getting issued for other targets where workers are actually available.
=> Process pending jobs per target

components/builder-api/src/server/resources/pkgs.rs, test/builder-api/src/packages.js
This fixes a case where specifying a bad target for package download would cause the builder API to panic. Also adds a test to catch this case.
=> Fix panic when bad target specified

components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/studio.rs, components/builder-worker/src/runner/workspace.rs, components/builder-worker/src/server.rs
This converts Linux builder to use Docker studio in non-Airlock mode. It is the next step toward consolidating all the builder workers to use Docker studio. More changes forthcoming.
=> Convert Linux (non-airlock) to Docker Studio

terraform/instances.tf, terraform/templates/windows_worker_user_data
Small change to plumb in the full set of bastions into the Windows builder worker
=> Use full set of bastions for Windows workers

Cargo.lock, components/builder-core/src/build_config.rs
The signature of matches_with changed from 0.2.11 to 0.3.0:
https://docs.rs/glob/0.2.11/glob/struct.Pattern.html#method.matches_with
https://docs.rs/glob/0.3.0/glob/struct.Pattern.html#method.matches_with
=> cargo update and fix for glob crate changes

terraform/files/51-studio-init.cfg, terraform/instances.tf, terraform/scripts/worker_bootstrap.sh
This change modifies the Terraform script to set up build workers to leverage Docker studio. The "ens4" network that was required for Airlock is removed. This will allow us to use smaller worker sizes, with a significantly reduced cost.
=> Terraform worker for Docker studio

components/builder-worker/habitat/plan.ps1
This fixes up the idents that are generated and pinned during the builder-worker Windows builds.
=> Fix idents generated during Windows builder-worker build

Cargo.lock, components/builder-worker/Cargo.toml, components/builder-worker/src/server.rs
This sets up a custom panic hook for builder worker.  In the (rare) case that the builder worker panics on a thread, it will print out the backtrace and panic info, and then exit the process. The process will be restarted by the supervisor. We prefer this behavior to the default, where a single thread (eg, runner) can die, and leave the heartbeat thread running so it appears that the runner is in a working state when it has actually died.
=> Set up panic hook for builder worker

terraform/scripts/create_bootstrap_bundle.sh
* If you forget to supply a version as an argument, we'll now tell you
what you did wrong, instead of making you read source code.
* Add some more detail about configuration of AWS credentials.
=> Minor tweaks to the create_bootstrap_bundle.sh script

Cargo.lock, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/services/s3.rs
Fixing the clippy lints in `core` requires some downstream changes to consumer code.
Now that https://github.com/habitat-sh/core/pull/135 has merged, these fixes need to merge along with the `cargo update` that pulls in the new `core` code.
=> Changes for clippy lint fixes from core

components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/studio.rs
This change stops the Docker studio container when a job is cancelled.  Without this change, leftover studios continue running on the system even when jobs are cancelled.
=> Stop Docker build job when canceling

.travis.yml, Makefile, components/builder-api/src/config.rs, components/builder-core/src/build_config.rs, components/builder-jobsrv/src/server/log_archiver/local.rs, components/builder-protocol/src/jobsrv.rs, components/builder-worker/src/runner/workspace.rs
- Change the list of lints in the Makefile to have parity with habitat
- Update TravisCI to use the Makefile for running clippy
- Fix a few lints
See:
https://rust-lang.github.io/rust-clippy/master/index.html#unreadable_literal
https://rust-lang.github.io/rust-clippy/master/index.html#cyclomatic_complexity
https://rust-lang.github.io/rust-clippy/master/index.html#const_static_lifetime
https://rust-lang.github.io/rust-clippy/master/index.html#into_iter_on_ref
=> Fix clippy lints and update CI

components/builder-api/src/server/resources/authenticate.rs, components/builder-api/src/server/resources/pkgs.rs, components/segment-api-client/src/client.rs, components/segment-api-client/src/config.rs, components/segment-api-client/src/main.rs
This change adds a config setting for Segment reporting capability. By default, the reporting will be disabled as it can cause issues with some on-premise infra. 
=> Add enabled config for Segment usage

components/builder-api/src/server/resources/pkgs.rs, test/builder-api/src/packages.js
This fixes a missed case in the package deletion flow, where we did not remove the package from memcache upon deletion. Also adds a few more tests.
=> Remove package from cache after deletion

.studiorc
Remove un-needed usage of worker account. Resolves https://app.zenhub.com/workspaces/57e1e83308ec936f021c876a/issues/habitat-sh/builder/980
=> Remove unneeded account

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs, test/builder-api/src/jobs.js
This change adds target query param handling to some package related APIs that were missing it - package promote, demote and channel list.
=> Add target params to pkg related APIs

components/builder-db/src/migrations/2019-04-05-002317_update_package_constraints/up.sql
This change updates the builder package schema to update the constraint to be (ident, target) uniqueness instead of just ident uniqueness. 
=> Update origin_packages constraint

components/builder-core/src/api_client.rs, components/builder-worker/src/runner/publisher.rs
This fixes builder upload and promotion for non-Linux targets, which now need to have a target query param specified appropriately.
=> Fix build worker package upload/promotion

components/builder-web/app/actions/packages.ts, components/builder-web/app/client/depot-api.ts, components/builder-web/app/package/package-detail/package-detail.component.html, components/builder-web/app/package/package-detail/package-detail.component.spec.ts, components/builder-web/app/package/package-detail/package-detail.component.ts, components/builder-web/app/package/package-promote/package-promote.component.ts, components/builder-web/app/package/package-versions/package-versions.component.html, components/builder-web/app/package/package-versions/package-versions.component.spec.ts, components/builder-web/app/package/package-versions/package-versions.component.ts
This fixes the promotion/demotion in the web UI by adding a package target query param to the API calls.
=> Fix up web UI to use targets for promote/demote actions

terraform/load-balancers.tf, terraform/variables.tf
Resolves https://github.com/habitat-sh/builder/issues/1012
We no longer need to manually muck with certs during Terraform setup.
There will be a corresponding PR in the cloud environments repo.
=> Update ELB SSL cert management to use ACM cert

components/builder-worker/src/runner/studio.rs
Need to add a couple of flags for studio builds to work with hab 0.79
=> Add no tty flags to builder-worker

components/builder-jobsrv/src/data_store.rs, components/builder-jobsrv/src/server/scheduler.rs
This change ensures we are using ident and target when checking dependencies.  This resolves https://github.com/habitat-sh/builder/issues/1019
=> Use target when checking idents dependencies

.studiorc, test/builder-api/test.sh
This works around a hab bug where the binlink folder is not correct - https://github.com/habitat-sh/habitat/issues/6418
=> Workaround hab 0.79 binlink bug

Cargo.lock, Cargo.toml, components/artifactory-client/Cargo.toml, components/artifactory-client/src/client.rs, components/artifactory-client/src/config.rs, components/artifactory-client/src/error.rs, components/artifactory-client/src/lib.rs, components/builder-api/Cargo.toml, components/builder-api/habitat/config/config.toml, components/builder-api/src/config.rs, components/builder-api/src/server/error.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/server/resources/pkgs.rs
This change enables use of JFrog Artifactory as an optional back end store. This feature is an early preview, and can be enabled via use of a feature flag. It is not turned on by default. When enabled, the configuration for Artifactory should be provided via the builder-api config toml - the config parameters currently supported are the Artifactory REST URL, the Artifactory API key, and a repo name.  The repo must be pre-created in Artifactory.
=> Add artifactory object store

.expeditor/config.yml, .expeditor/verify_private.pipeline.yml
We don't have windows public builders yet, so we'll run the windows tests in the private pipelines for the moment.
=> Add private windows verify pipeline

Cargo.lock, components/builder-api/Cargo.toml, components/builder-core/Cargo.toml, components/builder-jobsrv/Cargo.toml, components/builder-worker/Cargo.toml
As can be seen by the changes in `Cargo.lock`, this is the exact same
code, but it comes from a fork we control.
=> Use habitat-sh/rust-zmq instead of erickt/rust-zmq

components/builder-api/src/server/authorize.rs, components/builder-api/src/server/resources/origins.rs, test/builder-api/src/origins.js, test/builder-api/src/packages.js, test/builder-api/test.sh
This fixes up origin deletion where we were returning error 500 for cases where the origin was not 'empty' - eg, if a project was created for the origin. Now we will fail with a 409 conflict if the origin deletion does not succeed due to associated artifacts in the DB.
Also added a few more tests to validate the origin deletion behavior.
This resolves https://github.com/habitat-sh/builder/issues/1031
=> Fix origin deletion error and add tests

components/builder-api/src/server/resources/pkgs.rs
When deleting packages, only do the rdeps check if jobsrv is enabled
=> Check jobsrv feature during package delete

Cargo.lock, components/artifactory-client/Cargo.toml, components/artifactory-client/src/client.rs
Adds better support for proxies (including no_proxy support) for the artifactory client
Resolves https://github.com/habitat-sh/on-prem-builder/issues/142
=> Update proxy support for artifactory client

.travis.yml, components/builder-worker/src/runner/studio.rs, test/builder-api/test.sh
* All the imports at the top are the same, I just deleted the spaces between them so they're organized like all the other imports now.
* The license boilerplate isn't needed any more.
* The only meaningful change is adding the 2 environment variables for license acceptance and removing the `--no-tty` and `--non-interactive` flags (those got removed in 0.80.0 - the docker studio should auto-detect ttys now).
Please note:  these changes are _entirely untested_.  I'm in the middle of testing them now but running into time constraints so I'm putting this PR up now so y'all can see what I did.
=> Fix the worker for 0.81.0

Cargo.lock, components/builder-worker/src/runner/studio.rs, support/ci/install_hab.sh, support/ci/install_protobuf.sh
There are a bunch of deprecation warnings that I couldn't fix because they're in an upstream crate, but I did issue a PR against upstream to fix them.  We'll see what happens there.
https://github.com/fnichol/features-rs/pull/2
Update:  My PR was merged and there's a new version of the `features` crate, which I pulled into this PR.  I also added license acceptance to a few different scripts to get tests passing.
=> Bump cargo deps as part of 0.81.0 release

components/builder-db/src/migrations/2019-05-13-223900_regex_version/up.sql, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs, components/builder-db/src/schema/channel.rs, components/builder-db/src/schema/package.rs, test/builder-api/src/packages.js
This change removes the usage of the Postgresql semver extension, and instead uses regexp for version ordering. With this change, we now match the regexp algorithm used for ident comparison in Rust code. Some test cases that used to fail with semver now succeed. In addition, this resolves failures such as https://github.com/habitat-sh/on-prem-builder/issues/141. 
=> Use regexp for package version ordering

terraform/scripts/worker_bootstrap.sh
We need to mount the docker overlay directory on a volume with more storage as we can run out of room on large builds
=> Mount docker dir on main volume

components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/migrations/2019-05-16-004032_version_perf/up.sql, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs, components/builder-db/src/schema/package.rs
This resolves a perf issue with the latest package query by eliminating an extra join that was causing significant degradation.  The query performance is now back to the original perf prior to the regexp change.
=> Perf improvement for package versioning

.studiorc, components/builder-api/habitat/config/config.toml, components/builder-api/habitat/default.toml, components/builder-api/habitat/hooks/init, components/builder-api/habitat/plan.sh, components/builder-jobsrv/habitat/config/config.toml, components/builder-jobsrv/habitat/default.toml, components/builder-jobsrv/habitat/hooks/init, components/builder-jobsrv/habitat/plan.sh
In readiness for move to SaaS datastore to RDS, this removes the datastore binds from the builder-api and builder-jobsrv services.  The host and port will be passed in via config as needed.
=> Remove datastore binds from api and jobsrv

components/builder-db/src/migrations/2018-10-10-198563_enum_visibility/up.sql, components/builder-db/src/migrations/2018-11-02-111111_diesel_query_improvements/up.sql, components/builder-db/src/migrations/2019-05-13-223900_regex_version/up.sql, components/builder-db/src/migrations/2108-11-03-111111_search_index/up.sql
This does some cleanup of migrations - 1) remove all references to semver extension (this allows clean non-extension enabled Postgres instances to come up), and 2) remove and replace an incorrectly named migration.
=> Clean up migrations

terraform/instances.tf
To be merged after prod is updated with new bindings, and a new bootstrap tarball has been pushed up.
=> Remove datastore binding from api and jobsrv

components/builder-db/src/config.rs
This change allows the datastore config host to be a regular hostname instead of just an IP address. Both hostname and IP address will work, so the change is backward compatible. This will let us use the RDS DNS endpoint as the hostname in order to allow correct failover.
=> Change datastore host config from IPAddr to String

components/builder-api/src/server/resources/pkgs.rs
Resolves https://github.com/habitat-sh/habitat/issues/6598
We now actually check the value of the passed in params rather than just presence.
=> Fix schedule job param handling

terraform/instances.tf, terraform/scripts/create_bootstrap_bundle.sh, terraform/variables.tf, terraform/volumes.tf
Update Terraform to remove datastore node as we have migrated the DB to RDS.
Also minor tweak to AMI id for Windows worker.
=> Remove datastore node

Cargo.lock, components/builder-jobsrv/Cargo.toml, components/builder-jobsrv/src/server/mod.rs
This  change adds a custom (global) panic handler that will exit the jobsrv process if any of the threads panics. The process will be restarted by hab if running under the supervisor.  This should make us a bit more resilient to panics that could stall build jobs if one of the threads panicked but the process continued to run.
=> Add custom panic handler for jobsrv

components/builder-db/src/models/jobs.rs, components/builder-jobsrv/src/server/scheduler.rs
This change adds a watcher to the job scheduler that can cancel stuck jobs. This is initially targeted at a couple of cases - 1) there are no buildable projects (eg, all projects are skipped due to some error); 2) the build job max limit has been exceeded. More updates to the watcher will be forthcoming once the base usage has been shown to be useful.
=> Add build watchdog

components/builder-db/src/migrations/2019-06-24-198169_regex_update/up.sql, test/builder-api/src/packages.js
Fixes: #1106 
Adds the updated regex to a package view that previously would error if uploaded packages had non-standard versions.
=> Returns non-standard versioned packages in /versions endpoint

.expeditor/config.yml
cleanup from https://github.com/habitat-sh/builder/pull/1103
=> All tests are in public verify now, so we don't need this def

terraform/instances.tf, terraform/scripts/linux2_worker_bootstrap.sh
Fixes up Terraform breakage for linux2 workers by adding a new linux2_worker_bootstrap.sh script that correctly stops/starts the docker service.  Also some no-op auto formatting changes.
=> Fix linux2-worker terraform

terraform/files/sup_log.yml, terraform/instances.tf, terraform/templates/hab-sup.service
This adds a new logging config for the supervisor to the Builder service instances (all instances except the Windows worker for now)
=> Add new supervisor logging to Terraform

terraform/scripts/create_bootstrap_bundle.sh
When running this script on a pre-existing Linux system, we would try
to binlink common utilities that the script uses. However, this would
end up trying to overwrite system utilities like `awk` and `tar`,
which we don't necessarily want to do.
Now, instead of binlinking, we'll just prepend the paths to the
relevant binaries to `PATH`, making them available for the remainder
of the script, but leaving system binaries intact.
=> Temporarily add bootstrap utilities to PATH, instead of binlinking

Cargo.lock
I neglected to do this in my rust 1.37.0 PR.
=> Correct Cargo.lock for the new zmq branch

Cargo.lock, components/artifactory-client/src/client.rs, components/builder-api/src/server/error.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/server/resources/ext.rs, components/builder-core/Cargo.toml, components/builder-core/src/api_client.rs, components/builder-core/src/http_client.rs, components/builder-db/Cargo.toml, components/builder-db/src/config.rs, components/builder-worker/src/error.rs, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/publisher.rs, components/builder-worker/src/vcs.rs, components/github-api-client/src/client.rs, components/oauth-client/src/client.rs, components/segment-api-client/src/client.rs, components/segment-api-client/src/error.rs, components/segment-api-client/src/main.rs
This change enables on-prem Builder services to use cached certificates in "/hab/cache/ssl" as part of the trusted cert chain when communicating with external services such as github or other OAuth providers. This allows for a nicer way to deal with self-signed certs, instead of having to do things like manually modifying the cert.pem file in the core/cacerts installed package.
The one place where we are not using the cached SSL certs is for the S3 Rusoto calls. Those are using the Rusuto http client which has significantly different configuration. This should generally not be an issue for the current on-prem use case which is to use a local Minio instance.
This change also has some minor refactoring done to bubble up Results in a few places instead of unwraps or expects. Also there are a …
=> Enabled use of cached certs for Builder

components/builder-web/app/actions/jobs.ts, components/builder-web/app/client/depot-api.ts, components/builder-web/app/package/package-sidebar/package-sidebar.component.ts, components/builder-web/app/package/package/package.component.html, components/builder-web/app/package/package/package.component.spec.ts
This commit ensures the selected target platform is included w/ the request to build a new package.
Fixes https://github.com/habitat-sh/builder/issues/1157
=> Include `target` param w/ build job create request

components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/models/package.rs
This adds some additional tracing for package version related API requests that will be helpful in diagnosing hard to repro issues, eg, https://github.com/habitat-sh/on-prem-builder/issues/167 
=> Add trace debug for package versions

Cargo.lock, components/builder-jobsrv/src/server/scheduler.rs, components/builder-jobsrv/src/server/worker_manager.rs, components/builder-worker/src/runner/mod.rs, components/builder-worker/src/runner/publisher.rs
* Replace now-removed `wait_for` function
See https://github.com/habitat-sh/habitat/pull/6822 for background.
* Replace `supported_targets` with `targets`
See https://github.com/habitat-sh/habitat/pull/6862 for details.
=> Bump dependencies

.expeditor/scripts/verify/builder-api-functional.sh, .expeditor/templates/studiorc, .expeditor/verify.pipeline.yml, .travis.yml, components/builder-jobsrv/habitat/default.toml, test/builder-api/src/jobs.js, test/builder-api/test.sh
Closes #1166 
This PR migrates the failing builder-api tests to buildkite.  Additionally, it removes the segment-api step in the builder pipeline as that component is no longer part of this repository. 
After this PR merges, the travis-ci integration can be disabled, and the .travis.yml can be removed in a follow-on pr.
=> Migrate builder-api mocha tests to buildkite

components/builder-web/app/package/package-sidebar/package-sidebar.component.html
Closes https://github.com/habitat-sh/builder/issues/293
=> Remove the example commands from the sidebar

components/builder-api/src/config.rs, components/builder-db/src/config.rs
This change allows builder to connect to postgres using SSL for
authentication
=> Add SSL configuration for depot postgres client

components/builder-web/app/actions/oauth.ts, components/builder-web/app/app.component.ts, components/builder-web/app/client/builder-api.ts, components/builder-web/app/client/depot-api.ts, components/builder-web/app/origin/origin-page/origin-keys-tab/origin-keys-tab.component.ts, components/builder-web/app/shared/shared.module.ts, components/builder-web/app/side-nav/side-nav.component.html, components/builder-web/app/sign-in-page/sign-in-page.component.html
Doing this allows us to run builder at a different root path.
For example, automate will put builder at /bldr
=> Use relative paths in builder-web

components/builder-api/src/server/helpers.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/projects.rs, components/builder-api/src/server/services/github.rs, components/builder-db/src/models/projects.rs, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/scheduler.rs, test/builder-api/src/origins.js, test/builder-api/src/projects.js
This PR does a couple of things.
a. It plumbs the new project target requirements through to the jobsrv
b. It provides a mechanism for users to delete ALL projects for a given package by passing a '*' to the query value.
c. Finally, as a goal, it mostly preserves backwards compatibility. By providing the previous behavior of the api through default values.
=> Plumbs new project reqs through jobsrv, preserves backcompat

components/builder-api/src/server/resources/origins.rs, components/builder-core/src/access_token.rs, components/builder-core/src/integrations.rs, components/builder-db/src/migrations/2019-11-05-011907_private_keys/up.sql, components/builder-db/src/models/keys.rs, components/builder-db/src/schema/key.rs
This change adds some infra for keeping origin secret (signing) keys encrypted at rest. New secret keys are encrypted when they are stored in the DB. Pre-existing secret keys are able to be retrieved even if they are not (yet) encrypted. This allows us to be backward compatible, and migration of un-encrypted keys to happen asynchronously.
=> Add infra for key encryption

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/config.rs, components/builder-api/src/server/error.rs, components/builder-api/src/server/mod.rs
The user can optionally enable TLS listening by setting configuration
such as:
```
[http.tls]
cert_path = "/hab/svc/automate-builder-api/config/service.crt"
key_path = "/hab/svc/automate-builder-api/config/service.key"
```
Further, to enable client-certificate authentication, the user can
provide a ca_root_path:
```
[http.tls]
cert_path = "/hab/svc/automate-builder-api/config/service.crt"
key_path = "/hab/svc/automate-builder-api/config/service.key"
ca_cert_path = "/hab/svc/automate-builder-api/config/root_ca.crt"
```
This is similar to hab-sup`s TLS configuration.
This uses the openssl create which was already in use in this
applications.
I've tried to create a configuration that is close to various "modern"
recommendations.
=> Add TLS support to builder-api

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/config.rs, components/builder-api/src/server/error.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/server/services/memcache.rs
This adds optional support for TLS-enabled memcached servers. It
builds on #1218.
Signed-off-by: Steven Danna <steve@chef.io>
=> Support TLS for memcached

components/builder-api/src/server/mod.rs
The rust openssl docs say:
> This value should be set when using client certificates, or each
> request will fail its handshake and need to be restarted.
(https://docs.rs/openssl/0.10.16/openssl/ssl/struct.SslAcceptorBuilder.html#method.set_session_id_context)
Similarly, the SSL documentation says:
> If the session id context is not set on an SSL/TLS server and client
> certificates are used, stored sessions will not be reused but a
> fatal error will be flagged and the handshake will fail.
(https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_session_id_context.html)
I've opted to always set it since it doesn't appear _invalid_ to set
it even when client-certificates are not in use.
I've made our context id a random string. Other popular applications
such as nginx use facts about the …
=> call set_session_id_context

tools/ssh_helpers/update-habitat-ssh
Hey folks, please follow the directions below before approving this PR, as I am using that as a signal everyone is able to access acceptance so we can proceed with the changes to live.  Please reach out to me on slack if you run into any issues. 
Below are the updated steps outlined in our on-call documentation to access our builder environments. Once you have completed `Access to the VPN and Chef jump host` and IT has granted you access, please checkout this branch (so you have access to the updated scripts) and follow the directions in `SSH access to prod/acceptance nodes` and `RDP access to prod/acceptance windows-workers` 
In order to ssh or rdp into the production or acceptance Builder environments, you will need access to the Chef jump host and the VPN.   You will need to be logged …
=> Update ssh_helpers for new access policies

terraform/instances.tf, terraform/security-groups.tf, terraform/templates/windows_worker_user_data
This removes the open security group for rdp access to Windows. Access controls have been moved to Builder environment specific Terraform configuration. 
In addition, we change the source of the hab cli from Bintray to packages.chef.io in this PR.
We also update the array index for our launcher args, as a recent change in the WindowsService move from elements in the array to only 2. 
=> Remove windows-worker specific security group

components/builder-db/src/models/package.rs, components/builder-db/src/schema/member.rs, test/builder-api/src/invitations.js, test/builder-api/src/packages.js, test/builder-api/src/sessions.js
This is going to need some thorough testing in acceptance. Our functional tests all pass but it's hard to say how search is going to perform without a full dataset.
=> Tweaks package search to use origin membership rather than ownership

components/builder-api/src/server/resources/channels.rs
Closes #1188 
This change is based on the assumption that making `target` a required parameter would be a breaking change, as we have older clients that don't set that parameter and we haven't explicitly stated a minimum required `hab` cli version. 
In addition, this change addresses the case where a user passes an invalid combination of `ident`, `target` and `channel`, so this may be a useful addition even if we want to declare `target` as a mandatory parameter.
Without this change, when a user requests a package to demoted, they specify two pieces of information, `ident` and `channel`, with `target` an optional 3rd parameter which, if not specified, is inferred from the current system (in the case of recent `hab` cli versions) or defaulted to `x86_64-linux`.   When the server runs the …
=> Return 404 if no packages were demoted from the users request

.expeditor/post_habitat_release.pipeline.yml
We don't need two accounts... this was leftover from an incomplete
refactoring.
=> [CI] Remove extra AWS account

terraform/www.tf
This change stops Terraform from repeatedly trying to update the www bucket on every run.
=> Update www bucket policy to add version

terraform/instances.tf
Terraform change to increase root block device size to 20GB
=> Increase root block device size

.expeditor/builder_seed.txt
This adds `habitat/builder-memcached` to the bootstrap bundle creation. 
=> Add builder-memcached to boostrap seed

components/builder-api/src/server/migrations.rs, components/builder-api/src/server/mod.rs, components/builder-core/src/integrations.rs, components/builder-db/src/models/keys.rs
This does a incremental migration of the keys stored in the OriginPrivateSigningKey table, encrypting them at rest.
This migration is done at startup, and is designed to be idempotent, rerunning should be a single database check.
This has been tested on production data and the results spot-checked.
=> Add migration tooling for encrypted keys.

Cargo.lock, components/builder-api/Cargo.toml
The updated library fixes a bug where memcache request would fail
because of a short write while writing the payload
=> Update memcache library

components/builder-db/src/metrics.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs
We want to get some more granular metrics on response times for these specific database calls that we know are already expensive calls. The plan is to get these metrics into datadog so we can see exactly which calls are pegging and how long they're taking to respond.
=> Add dbcall specific histogram metrics to DDog

components/builder-api/src/server/resources/jobs.rs, test/builder-api/src/misc.js
This change adds some additional visibility checking to the rdeps APIs. Origins that default to non-package public visibility will have their packages filtered out of the rdeps calls.  Note that one of the API calls (rdeps/.../group) is experimental and may be removed at some later point. 
=> Check rdeps package visibility

components/builder-db/src/migrations/2020-01-28-174159_origins_add_owner_account/up.sql, components/builder-db/src/models/origin.rs, components/builder-db/src/schema/origin.rs, test/builder-api/src/helpers.js, test/builder-api/src/origins.js
Closes https://github.com/habitat-sh/builder/issues/1272
This change updates the `OriginWithSecretKey` struct and underlying db view by adding an `owner_account` field to it, such that a HTTP [GET](https://github.com/habitat-sh/builder/blob/eb9f96bee229b1f9b1e0b26686f1befdd0c8f901/components/builder-api/src/server/resources/origins.rs#L169) of `/depot/origins/{origin}` returns the new [OriginWithSecretKey](https://github.com/habitat-sh/builder/blob/141967f3a5c5eaa2cb03a752dc34d0dd51e04499/components/builder-db/src/models/origin.rs#L80-L86).
Previous view:
```
builder=# \d+ origins_with_secret_key
View "public.origins_with_secret_key"
Column           |           Type            | Modifiers | Storage  | Description
----------------------------+---------------------------+-----------+------- …
```
=> adds owner_account to the OriginWithSecretKey response

components/builder-api/src/config.rs, components/builder-api/src/server/framework/headers.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/pkgs.rs
This change adds a configurable cache expiration for private packages. This allows better control of private packages at the CDN level, and also lets us tune the cache settings for performance as needed.
=> Cache config for private packages

components/builder-web/app/client/github-api.ts
Github is deprecating the use of access token as a query param as a mechanism for authenticating with Github API.  This change replaces the query param with an Authorization header in the web UI calls.
This should resolve https://github.com/habitat-sh/builder/issues/1297
=> Update deprecated token in query param

components/builder-db/src/models/package.rs
Closes #1302 
This change was validated using the same set of packages used to reproduce the error.  On starting jobsrv, it now reports the correct numbers of packages in the build graph. 
```
builder-jobsrv.default(O): [2020-02-12T16:03:44Z INFO  habitat_builder_jobsrv::server] Graph build stats (PT0.002793900S sec):
builder-jobsrv.default(O): [2020-02-12T16:03:44Z INFO  habitat_builder_jobsrv::server] Target x86_64-linux: 1 nodes, 0 edges
builder-jobsrv.default(O): [2020-02-12T16:03:44Z INFO  habitat_builder_jobsrv::server] Target x86_64-linux-kernel2: 1 nodes, 0 edges
builder-jobsrv.default(O): [2020-02-12T16:03:44Z INFO  habitat_builder_jobsrv::server] Target x86_64-windows: 0 nodes, 0 edges
```
Once this change is in acceptance, we should examine the `rdeps` api to confirm it fixes …
=> Include target for evaluating uniqueness in get_all_latest

components/builder-api/src/server/resources/origins.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/migrations/2020-02-11-810532_settings_refresh/up.sql, components/builder-db/src/models/package.rs, components/builder-db/src/models/settings.rs, test/builder-api/src/packages.js
Should be pretty straightforward, this is in service of the ui changes. It should add another migration to refresh the data that exists in the `origin_package_settings` table, alter package upload to create an entry in origin_package_settings in the case that it doesn't yet exist, and alters the origin packages route to look in the new table rather than the previous table. 
Whether we bundle it into this migration or not - I think it probably makes sense to change the 'origin_packages' table to a different name. Perhaps `origin_package_artifacts` or the like.
=> Change route to pull from origin_package_settings, create settigs on upload

components/builder-web/app/package/package-versions/package-versions.component.html, components/builder-web/app/package/package-versions/package-versions.component.ts, components/builder-web/cypress/fixtures/package-detail/version-releases.json, components/builder-web/cypress/integration/package-detail.spec.ts
As part of https://github.com/habitat-sh/builder/issues/1189, this commit adds the ability to link to a specific version in a package's version list and have it affect the open/close state of the list item.
=> Allow package versions in versions list to be linkable

.expeditor/post_habitat_release.pipeline.yml, .expeditor/scripts/post_habitat_release/cargo_update.sh, .expeditor/scripts/post_habitat_release/shared.sh
This pulls in the relevant bits for updating the Cargo.lock after a release from the [habitat repository](https://github.com/habitat-sh/habitat).
Closes #1232
=> Update cargo.lock after Habitat release

.expeditor/scripts/generate_bootstrap_bundle.sh
The version used by default in CI doesn't support the toml format of the seed file for `hab pkg download`.  This installs the just-released hab cli to be used fetch packages to generate the bootstrap bundle. 
=> [CI] Update hab cli to version with toml download-file support

components/builder-web/app/package/package-sidebar/package-sidebar.component.html, components/builder-web/app/package/package-sidebar/package-sidebar.component.ts
Updates the package sidebar to display visibility settings from the package settings endpoint/table instead of displaying the visibility of individual projects.
Signed-off-by: Scott Christopherson <scott@chef.io>
=> Display package viz settings in sidebar instead of legacy project viz

components/builder-db/src/migrations/2020-03-03-000001_origins_with_stats/up.sql
This changes our origins_with_stats endpoint to look at the pkg settings table. It should be a marginally quicker query but also will take into account when a "package" has been created but no artifact built or plan connected.
Fixes #1325
=> Swap package count to use origin_package_settings table

.studiorc
This PR handles the scenario where the user enters the studio and first runs `bb` expecting all services to be built, then started. However, they find that `builder-api` and `builder-worker` services are infinitely waiting on keys.
With this change, a `bb` invocation upon first entering a studio will ensure that these two services are functionally working. Additionally, if a user builds either of these two services individually, we will also ensure the keys have been uploaded after the build.
This is a minor but important scenario that wasn't handled in https://github.com/habitat-sh/builder/pull/1314
=> handle uploading keys after building api and worker services

terraform/instances.tf
Came to find out our Windows AMI was no longer available:
```
module.builder_environment.module.builder.aws_instance.windows-worker[0]: Creating...
Error: Expected 1 AMI for ID: ami-0a6b38f2d62c0cc94 (No images found for AMI ami-0a6b38f2d62c0cc94)
```
This PR provides an update to the latest image of the same type.
=> required update of our Windows AMI

terraform/instances.tf, terraform/scripts/install_base_packages.sh
This PR unifies our Builder bootstrap process, consolidating everything into the `install_base_packages.sh` which now takes optional arguments for platform type and installs from the bootstrap bundle containing .harts for all target types.
=> install_base_packages.sh supports all linux platform targets

.expeditor/scripts/generate_bootstrap_bundle.sh, terraform/scripts/install_base_packages.sh
The purpose of this PR is to include both linux platform target `hab` binaries in the bootstrap bundle such that we can utilize the appropriate target binary when installing artifacts.
`bin/hab` will remain in place, though as a symlink to `bin/hab-x86_64-linux`
```
root@ip-10-0-0-76:/home/ubuntu# ls -l hab_bootstrap_1584031400/bin/
total 36284
lrwxrwxrwx 1 root root       16 Mar 12 18:55 hab -> hab-x86_64-linux
-rwxr-xr-x 1 root root 18540176 Mar  3 16:39 hab-x86_64-linux
-rwxr-xr-x 1 root root 18611160 Mar  3 16:39 hab-x86_64-linux-kernel2
root@ip-10-0-0-76:/home/ubuntu#
```
=> x86_64-linux x86_64-linux-kernel2 hab binaries to bootstrap bundle

components/builder-api/src/server/migrations.rs, components/builder-api/src/server/services/s3.rs, components/builder-core/src/logger.rs, components/builder-jobsrv/src/server/handlers.rs, components/builder-jobsrv/src/server/mod.rs
When we cleaned up our time code, we generally used the
Duration::as_secs api; however that rounds to the nearest integer. For
quick things that isn't too useful.
This is a selective replacement of as_secs with as_secs_f64 where it
seemed to make sense.
=> Fix some uses of Duration::as_secs to f64

DEVELOPING.md
This adds steps to the DEVELOPING document for building against core origin packages that have not been promoted to stable yet. 
=> Add testing steps for core-plans refresh

components/builder-api/src/server/resources/pkgs.rs, components/builder-jobsrv/src/server/mod.rs
closes #1365 
This increases the max payload size to 256KB to hopefully eliminate the following error for low-level packages that have lots of metadata:
```
Mar 25 10:42:55 ip-10-0-0-222 hab[23699]: builder-jobsrv.acceptance(O): [2020-03-25T10:42:55Z DEBUG actix_web::types::json] Failed to deserialize Json from payload. Request path: /rpc
Mar 25 10:42:55 ip-10-0-0-222 hab[23699]: builder-jobsrv.acceptance(O): [2020-03-25T10:42:55Z DEBUG actix_web::middleware::logger] Error in response: Overflow
```
=> increase max JsonConfig playload size for jobsrv /rpc endpoint

components/builder-db/src/migrations/2020-03-27-193418_origin_members_dupe_fixes/up.sql
This PR corrects several issues discovered during preliminary RBAC work:
* adds uniqueness constraints to the origin_members and
origin_invitations tables
* removes duplicate entries from the origin_members table
With these changes, users will not be able to send multiple invitations
to a specific user for any origin. As a result, users should no longer
be able to accept multiple invitations to the same origin which
previously resulted in them having multiple entries for the same origin
in the origins_members table.
As mentioned, the duplicate entries that do currently exist in the origin_members
table will be deleted. We've identified that the calling functions,
including the web UI, handle conflict errors gracefully.
The migrations have been vetted and tested both in local builder …
=> clean up data modeling issues

.github/no-response.yml, .github/stale.yml
This adds configuration for probot/stalebot and probot/no-responsebot.     Once the bots are added to the repository, this PR can be merged if we are happy with the configuration. 
=> Add configuration for stalebot and noresponsebot

components/builder-web/app/shared/project-settings/_project-settings.component.scss
Fixes https://github.com/habitat-sh/builder/issues/1387
Connect-plan modal had an overly large z-index value. NG material overlays start their z-indexes at `1000` which is why the docker-settings overlay was being hidden by `9999` z-index connect-plan.
Signed-off-by: Scott Christopherson <scott@chef.io>
=> Reduce connect-plan modal z-index

components/builder-db/src/metrics.rs, components/builder-db/src/models/channel.rs, components/builder-db/src/models/package.rs
This adds metrics to everything that queries the origin_packages table
in a way that looks likely perform poorly. This addresses issue #1391.
It follows the existing naming convention as best I could. There's a
lot of boilerplate, which seems a little bit hard to remove.
However I'd like to suggest a different convention: let's construct
the name as structname,functionname using the approprate
inflection/casing scheme. E.g. for the Packages::count_origin_packages
functionthe enum names would be PackagesCountOriginPackagesCallTime,
and the logging keys would be
db-call.packages-count-origin-packages-call-time. I find it easier to
figure out, and I believe it will make it easier to group related
statistics.
This potentially breaks existing logs, and I'd suggest we log twice,
once with the …
=> First pass at adding db metrics

components/builder-api/habitat/hooks/run
We check to see if Jobsrv is enabled in builder-api, only then do we wait on the `builder-github-app.pem` file. 
Noticed this was an issue raised by a user in our forums: https://forums.habitat.sh/t/on-prem-builder-api-port-not-binding/1316
=> accounting for other oauth providers in api run hook

support/ci/builder-base-plan.sh
When building a package of a past commit, the git-based versioning logic
in builder-base-plan.sh used the master branch to derive the version
number from the number of commits. This resulted in always having a
version number based on your local copy of the master branch, even when
trying to build from an older revision.
This change now uses whatever the user has checked out as HEAD to derive
the version number, resulting in version numbers that more accurately
reflect the version of the code that they were built against.
Signed-off-by: Stephen Delano <stephen@chef.io>
=> builder-base-plan: get version from current rev

components/builder-worker/build.rs, components/builder-worker/habitat-dev/plan.sh, components/builder-worker/habitat/plan.ps1, components/builder-worker/habitat/plan.sh, components/builder-worker/src/runner/docker.rs, components/builder-worker/src/runner/job_streamer.rs
This unpins the dependencies for the linux builder-worker to start using the post-refresh versions of packages. It also updates the dependencies to use the renamed container exporter package.
=> Update package dependencies for builder-worker

.expeditor/config.yml, .expeditor/scripts/post_datadog_merge_event.sh
This will allow us to overlay merge events onto our Datadog graphs. 
It should help strengthen our pre-release process to the Live environment by hi-lighting any behavioral changes that may have been introduced as a result of a code change. It should also prove useful in troubleshooting.
=> post a datadog event when merge to master occurs

components/builder-api/doc/api.raml, components/builder-api/src/server/helpers.rs, components/builder-api/src/server/resources/channels.rs, components/builder-db/src/metrics.rs, components/builder-db/src/models/channel.rs, test/builder-api/src/channels.js
First pass at #1419
This provides a way to list all latest packages for a channel.
We chose the endpoint
/depot/channels/{origin}/{channel}/pkgs/latest?target=TARGET which is
mildly problematic, as it aliases with any package called latest. This
is an existing problem, in that we also alias for promote, but in that
case we can differentiate because one is GET and the other PUT.
One possibility would be to revert to the suggested
/depot/channels/ORIGIN/CHANNEL/latest?target=TARGET endpoint, but that
has it's own problems, as discussed in #1419
(https://github.com/habitat-sh/builder/issues/1419#issuecomment-632667908)
Further testing would be useful; the current test only has one package
in the origin.
=> Add API to list latest packages for channel

Cargo.lock, components/artifactory-client/Cargo.toml, components/artifactory-client/src/client.rs, components/artifactory-client/src/error.rs, components/builder-api/Cargo.toml, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/services/s3.rs, components/builder-core/Cargo.toml, components/builder-core/src/api_client.rs, components/builder-db/Cargo.toml, components/builder-db/src/models/package.rs, components/builder-graph/Cargo.toml, components/builder-jobsrv/Cargo.toml, components/builder-protocol/Cargo.toml, components/builder-worker/Cargo.toml, components/builder-worker/src/runner/workspace.rs
This PR removes the `habitat_core` pins added in 720ce93ecda78a439411e52b05e171a4fd163b67.
The changes are largely mechanical, working the `Result` returned by `PackageArchive::new()` and the `String->&str` return through.  
Lines 1023-1030 and 1044-1050 in  components/builder-api/src/server/resources/pkgs.rs bear closer examination to ensure I've use the correct pattern for returning a new error so that the failure is reported correctly back to the user.
=> Unpin habitat_core crate

components/artifactory-client/src/error.rs, components/builder-api/src/config.rs, components/builder-api/src/server/error.rs, components/builder-core/src/error.rs, components/builder-db/src/error.rs, components/builder-graph/src/error.rs, components/builder-jobsrv/src/error.rs, components/builder-protocol/src/error.rs, components/builder-worker/src/error.rs, components/github-api-client/src/error.rs, components/oauth-client/src/error.rs
The `description` fn in the Error trait has been deprecated since Rust 1.42.0. This commit removes all
usage of it in builder, in addition to removing any error::Error impl that are no longer necessary. 
Reference: https://doc.rust-lang.org/std/error/trait.Error.html#method.description
=> Remove description fn from error::Error impl

components/github-api-client/src/client.rs
Github has deprecated the existing app installations api endpoint and moved it to a new location under `/app`
https://developer.github.com/changes/2020-04-15-replacing-create-installation-access-token-endpoint/
=> Update github app installations url

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/server/services/memcache.rs, components/builder-jobsrv/Cargo.toml, components/builder-jobsrv/src/server/log_archiver/local.rs
As part of the update to 0.9.0, the RustCrypto suite of crates has changed some function names in their public api:
https://github.com/RustCrypto/traits/issues/43
https://github.com/RustCrypto/hashes/pull/157
This commit updates to the 0.9.x version of the sha2 crate from that suite and changes function calls as appropriate.
=> Update sha2 crate to 0.9.0

components/builder-graph/src/error.rs, components/builder-graph/src/graph_helpers.rs, components/builder-graph/src/main.rs, components/builder-graph/src/package_graph.rs, components/builder-graph/src/package_graph_target.rs, components/builder-graph/src/package_ident_intern.rs, components/builder-graph/src/util.rs
Add a command to take a set of packages and produce an annotated list of their plan deps. This is emitted one package per line, with a list of which packages in the original list pull them in.
For example:
```compute_attributed_deps deps_test.out --idents core/ruby core/openssl```
Produces a file that looks like this:
```
core/acl        core/ruby
core/attr       core/ruby
core/binutils   core/ruby
core/cacerts    core/openssl, core/ruby
core/coreutils  core/ruby
```
=> Add a command to map a set of packages to their dependencies

terraform/templates/windows_worker_user_data.tpl
resolves #1282 
This enforces normal hab cli usage to access hab from binlink. This way updating hab can be done via `hab pkg install core/hab -b --force` just like one would do on linux.
=> binlink hab package for normal cli access

components/builder-api/src/server/authorize.rs
Circling back around and fixing a TODO.
Previously, when `Maintainer` was the default role for new members and nobody had changed roles from such, this line in `authorize.rs` was fine. 
In many places, resource endpoints make calls such as `authorize_session(&req, Some(&origin), None)` indicating the caller doesn't require a minimum role, but does require origin membership for a read operation.  As the new default membership role is now `ReadonlyMember`, this PR allows those callers to remain unchanged.
I have verified with all the callers that behave as such:
```
✔ ~/Projects/builder [jeremymv2/minimum_req_role L|…12⚑ 13]
14:44 $ find components/ -name \*\.rs | xargs grep -n authorize_session | grep "), *None)"
components//builder-api/src/server/resources/origins.rs:957:    let …
```
=> OriginMemberRole::ReadonlyMember is the new minimum member level

components/builder-graph/src/cyclic_package_graph.rs, components/builder-graph/src/lib.rs, components/builder-graph/src/main.rs, components/builder-graph/src/package_graph.rs, components/builder-graph/src/package_graph_target.rs, components/builder-graph/src/package_graph_trait.rs, components/builder-graph/src/package_info.rs
This takes the new cyclic graph work and wraps it in the
package_graph_trait. There's some conversion work required as the
existing API uses Strings where we might have a PackageIdent, and
package information is represented as a originsrv::OriginPackage and
needs to be converted to the internal representation.
This is the first part of the solution to issue  #1476 (closes #1476) and is on the path between #1456 and #1457 
Co-authored-by: Scott Macfarlane <smacfarlane@chef.io>
Co-authored-by: Mark Anderson <mark@chef.io>
=> Wrap package_graph_for_target in package_graph_trait compatible layer

components/builder-web/app/sign-in-page/sign-in-page.component.html, components/builder-web/app/user-nav/user-nav.component.html
Adds Chef patent links to sign-in view and user-nav dropdown.
Closes https://github.com/habitat-sh/builder/issues/1484
=> Add Chef patent links

components/builder-web/app/package/package-release/package-release.component.ts
If an unauthenticated or non-origin member happens to navigate directly to a private artifact, they are redirected to the top-level packages route `/pkgs` instead of seeing a blank artifact view.
Fixes https://github.com/habitat-sh/builder/issues/1480
**Before**
**After**
=> Redirect non-origin members from private artifact view

.expeditor/scripts/post_habitat_release/build_worker.sh
The install path for `hab` in the containers has changed and takes
precedence over the curl|bash installed hab. This change ensure we're
always using the binary we just installed so that we're building using
the latest hab for the correct target.
This change is a sibling commit to https://github.com/habitat-sh/habitat/pull/7854
=> Update worker builds to use $hab_binary

test/run_clippy.sh
Rather than installing Rust, clippy, setting environment variables,
etc. everywhere, we'll only do this in CI. In this way, we can allow
developers to set up their workstation as they want, but still be able
to easily run `make lint`.
=> Only run setup steps for `make lint` in CI

support/builder/datastore.toml
Sometimes a developer's CPU thread number can cause the default workers to exceed the prior limits, inhibiting their ability to test in the studio.
This raises the `max_connections` from the default of 100->200.
=> bump postgres max_connections for local studio dev

test/builder-api/src/jobs.js, test/builder-api/test.sh
We've recently started seeing the occasional test run fail because the 'db-cleanup' step would fire before the migrations had finished running:
```
> test-builder
...
Performing DB cleanup
ERROR:  relation "origin_channel_packages" does not exist
LINE 1: DELETE FROM origin_channel_packages WHERE channel_id IN (SEL...  
```
In the process of debugging it, we also found two tests that were sensitive to timing, `list_all_jobs` and `get_job_logs`.  The first would intermittently fail by returning an empty list with the `range_end` set to 49, rather than 0, because the jobsrv hadn't yet populated the `jobs` table.   The second would fail to create a dummy log file on retry because the `after` block doesn't appear to fire between retries. I didn't do a deep investigation as to the cause, but …
=> Add some additional guards to our timing senstive tests

components/builder-jobsrv/src/server/worker_manager.rs, components/builder-worker/src/runner/mod.rs
We are occasionally seeing Workers that appear to be in a semi-connected
state. They are listed as ready in our dashboards, work is assigned to
them but the job isn't dispatched. Logging in the acceptance environment
indicates a zmq issue `(Failed to dispatch job to worker, err=Zmq(Host unreachable))`.
This is a first pass at being able to gather additional information.
Includeing additional state in the logs will help us trace what
machines are involved, along with the work we are attempting to do.
These events should be infrequent and treated as something noteworthy
and worth investigating, so their log level has been adjusted
accordingly.
=> Change worker heartbeat log levels

components/builder-api/src/server/resources/origins.rs, components/builder-core/src/access_token.rs, components/builder-core/src/crypto.rs, components/builder-db/src/migrations/2020-09-08-195315_stop_base64_encoding/up.sql
Previously, we would store all encrypted data in the database as a
base64-encoded string. However, this doesn't actually do anything
meaningful, since our encrypted messages are themselves already
strings (partly plaintext metadata indicating which key(s) are
involved in the encryption/decryption process, and partly
base64-encrypted ciphertext) and not simply binary data. Adding an
additional layer of base64 encoding amounts to "busywork", in addition
to increasing the size of the stored data by 1/3.
We also modify the `crypto` module to stop encoding and decoding
encrypted data, which means that the rest of the code should continue
to work transparently. We still use `String` as the type we pass into
and out of this module because the rest of Builder doesn't really care
what kind of …
=> [MIGRATION] Stop storing encrypted content as base64-encoded strings

test/builder-api/src/roles.js
Fixing misspelling (`emtpy`). How did this ever...?
Additionally, a couple of other fixes that were failing locally for me in `test-builder`.
=> fixes for API tests

Cargo.lock, components/builder-api/src/server/framework/middleware.rs, components/builder-api/src/server/resources/profile.rs, components/builder-core/Cargo.toml, components/builder-core/src/access_token.rs, components/builder-worker/src/runner/mod.rs
In an attempt to further streamline and clarify code around tokens, a
new `AccessToken` type is introduced. This is the type that is
ultimately responsible for creating the string form of a token that
users interact with.
Please read individual commit messages for additional details, as well
as the new code documentation.
=> [REFACTOR] Encapsulate access token in a new AccessToken type

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/habitat/config/config.toml, components/builder-api/habitat/default.toml, components/builder-api/habitat/plan.sh, components/builder-api/src/config.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/services/events.rs, components/builder-api/src/server/services/mod.rs, support/ci/builder-base-plan.sh
This PR adds all the required bits for the initial piece of confluent cloud integration for the builder API hidden behind a feature flag. It only generates an event on individual package promotions. Getting this merged means we can start to investigate more interesting levels of kafka interaction in the SaaS services and serves as a model for event production and submission to confluent as an event bus. It should have no impact on live/acceptance whatsoever.
=> Adds feature-flagged POC for kafka producer to builder api

terraform/instances.tf
This aligns the Windows instances with our Linux instances in the
expectation that the public key is set to the value of the key rather
than the path to a file containing the key
=> Change the source for the connection public key

components/builder-worker/src/runner/studio.rs
The local development environment uses the chroot studio for building packages in the worker.   This requires the HOME variable to be set. For production builder we clear the environment before creating the studio which includes clearing the HOME variable. This sets it to a hard-coded  path (the same as what is set by default in the config) only when we are in the development studio. 
The change here is a little awkward in shape,  but the job dispatch would likely need to be refactored to make supporting both the docker and chroot studio, along with windows builds, a little more ergonomic to set up. While this would be worthwhile taking on, it's a little out of scope for the scheduler work currently in flight, but we do need to be able to run the Worker in the studio as part of validating …
=> Set HOME in job dispatch for local development

components/builder-worker/habitat/_common/config.toml, components/builder-worker/habitat/_common/default.toml, components/builder-worker/src/config.rs, components/builder-worker/src/runner/mod.rs, support/builder/config.sh
The builder-worker currently blocks its main run loop for up to 60 seconds, or until a message from jobsrv arrives.  This has a side effect of blocking job completion until the polling times out, as the jobserv in normal operation won't send a message to a busy worker.   The blocking occurs because we use an mspc channel to signal back to the main loop that work has completed, which is only read after the zmq poll finishes. https://github.com/habitat-sh/builder/blob/master/components/builder-worker/src/runner/mod.rs#L715-L755
This PR exposes that value as a config object, with the default of its current value 60 seconds (converted to ms for zmq).  It also sets the default for the studio dev environment to 5 seconds, so that we can tighten up our feedback loop while iterating on the …
=> Expose worker zmq poll interval as config object

components/builder-api/src/server/migrations.rs, components/builder-api/src/server/migrations/encrypt_secret_keys.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/server/resources/origins.rs, components/builder-db/src/models/keys.rs, components/builder-db/src/models/migration_support.rs, components/builder-db/src/models/mod.rs, components/builder-jobsrv/src/server/worker_manager.rs
There's a mixture of refactorings here to further consolidate key retrieval operations. Ideally, we just "ask for keys" and we get the core business logic types, with things like decryption handled transparently for us. Similarly, when saving keys to the database, we should only have to pass in one of the core business logic key types, and the encryption and saving is handled for us.
Additionally, recent refactorings revealed that origin secret encryption keys were not themselves encrypted in the database. This PR introduces a migration to encrypt everything currently in the database, and handle encryption/decryption on save/retrieval as necessary.
Of particular note for reviewers is the structure set up around the "live" migration code. Since this migration involves complex business …
=> [MIGRATION + REFACTOR] Ensure keys are encrypted at rest in database

components/builder-graph/src/data_store.rs, components/builder-graph/src/graph_helpers.rs, components/builder-graph/src/package_build_manifest_graph.rs, components/builder-graph/src/target_graph.rs, components/builder-graph/src/util.rs
The build workers don't allow exact package resolution, but instead
resolve the latest from a channel. The execution ordering of the base
graph is specified only by the direct dependencies of the
package. This creates an antidependency (read before write) as it is
possible that we build the next iteration of a package before all of
the consumers of the last iteration have started; if that happens
those packages might pick up the wrong iteration. This is likely
harmless, except it makes the process + nondeterministic and hard to
debug. Constraining this will protect against this nondeterminism at
the cost of some parallelism.
Co-authored-by: Mark Anderson <mark@chef.io>
Co-authored-by: Scott …
=> Extend package build manifest to support existing build workers.

components/builder-jobsrv/src/server/mod.rs
In some cases the manifest for a package can be larger than the maximum
default of 32k for the json body in rpc calls to jobsrv.  This was
previously corrected in #1366, but reappeared recently in our testing of
the scheduler.
Actix 2.0.0 added an `app_data` in addition to the `data` method that
makes the configuration available at the application level, rather than
the resource level.  Changing from the previously correct `data` to
`app_data` when setting the config value appears to again correctly set
the maximum payload size to 256K.
https://docs.rs/actix-web/2.0.0/actix_web/struct.Resource.html#method.app_data
=> Change default max json body size [jobsrv]

components/builder-api/src/server/resources/channels.rs, components/builder-events/src/connection.rs, components/builder-events/src/event.rs, components/builder-events/src/kafka.rs
This change improves the `EventConsumer` trait's `.poll()` method by returning a `BuilderEvent` instead of `String` type. The `BuilderEvent` type now becomes the contract message implementation for the `EventConsumer` and `EventPublisher` APIs. The `BuilderEvent` struct includes an `event_type` field that we can match on to flexibly deserialize the JSON `payload` field into a downstream Type of our choosing. This should allow us to handle any sort of business logic we need with these libraries.
=> replace String return type for EventConsumer

Cargo.lock, components/builder-worker/Cargo.toml, components/builder-worker/src/runner/mod.rs
This fixes the Windows workers inability to clean the cloned source directory tree.
=> use remove_dir_all crate to clean source tree on worker

components/builder-api-proxy/habitat/config/nginx.conf, components/builder-api-proxy/habitat/default.toml
updates builder-api-proxy to allow for nginx rate limiting to depot locations
Allows for uses of `on-prem-builder` to have a method to implement nginx rate limiting for depot locations if needed to help as a component prevent network over-saturation in the event of an intended or accidental mass package deployment.  Applies configuration to `depot` locations from `builder-api-proxy` and seeds with some sample initial values, also adding a toggle to default to false.
Signed-off-by: Collin McNeese <cmcneese@chef.io>
=> updates builder-api-proxy to allow for nginx rate limiting

components/builder-api/src/server/resources/pkgs.rs, components/builder-graph/src/acyclic_package_graph.rs, components/builder-graph/src/cyclic_package_graph.rs, components/builder-graph/src/graph_helpers.rs, components/builder-graph/src/package_graph_target.rs, components/builder-graph/src/package_graph_trait.rs, components/builder-graph/src/package_ident_intern.rs, components/builder-jobsrv/src/server/mod.rs
Add API endpoint to jobsrv to return graph
Adds a resource in the form: /graph?target=TARGET&origin=ORIGIN to return a json dump of the graph.
If origin is not provided gives full graph
If target is not provided chooses x86_64-linux
Also add a bit more tracing to help track api calls
=> Add API endpoint to jobsrv to return graph 

components/builder-api-proxy/habitat/plan.sh, components/builder-datastore/plan.sh, components/builder-memcached/plan.sh, components/builder-minio/habitat/plan.sh, components/builder-worker/habitat/x86_64-windows/plan.ps1
Some of our plans produce a version based on commit count of HEAD but others get the count from master. Head is better since that will give a reproducible version for any given checkout.
=> get commit count from HEAD not master

components/builder-db/src/migrations/2020-11-09-000001_job_graph_scheduler/up.sql
There's apparently no `IF NOT EXISTS` clause for this, so we have to
be a bit more verbose.
=> Guard the creation of job_exec_state type

components/builder-db/src/migrations/00000000000000_diesel_initial_setup/up.sql, components/builder-db/src/migrations/2020-11-09-000001_job_graph_scheduler/up.sql
This effectively undoes #1565 and #1566, as we now believe them to have been unnecessary.
The problem they were attempting to solve was a failure to apply migrations in our acceptance environment. Initially, we added the idempotency guards from those two PRs to address apparent failures in the migration. Ultimately, we were able to get the migration applied in our acceptance environment, thanks to their help. Further inspection revealed that an earlier version of the migration, identified by a different, earlier timestamp had been applied in the acceptance environment (we have not been able to find this migration in version control history, leading us to suspect some manner of "out-of-band" application, perhaps as some kind of manual validation). As a result, the migration script ended up …
=> Revert unnecessary schema changes

components/builder-api/src/server/resources/pkgs.rs, components/builder-db/src/models/package.rs, test/builder-api/src/packages.js
The current search functionality in builder will only search for packages when their org/package name matches. The problem with this is that the user has to know the origin/package name upfront to search for packages. It does not allow to search for packages that can start with an origin or package name.
Postgress [full text search](https://www.postgresql.org/docs/9.6/textsearch-intro.html) supports [prefix matching](https://www.postgresql.org/docs/9.6/textsearch-controls.html).
With this fix, the search can support the following prefix cases:
cor
core
core/rust
The limitation of the current search is restricted to prefix match only. It does not support trigram matches.
=> Enable package search by prefix match

components/builder-core/src/job.rs
In Rust 2021, the assert macro can also accept expressions, format! is no longer needed to pass a string literal.
=> warning: panic message is not a string literal

terraform/files/nginx.yaml
restore previously removed tag
Signed-off-by: Riju VV <riju.vv@progress.com>
=> Fix the tags which are used in datadog dashboard OPS-1909

Makefile
Makefile target can be invoked with:
$ make prereq
Target will refresh apt-get, and install packages preventing clean installation on MacOS workstation
=> Add makefile target for installing MacOS prerequisite packages

components/builder-api/src/server/resources/projects.rs, components/builder-web/app/client/builder-api.ts, components/builder-web/app/shared/project-settings/project-settings.component.ts
closes #1602
When creating a new connection, if the package name does not match with the name in the plan file, it creates a record in the projects table but subsequently fails.
Upon updating the connection, it displays HTTP status text, which does not say what went wrong.
Along with handling the scenarios mentioned on the backend, this PR also handles displaying the message on UI.
=> Handle package name mismatch in connection creation

components/builder-web/app/client/depot-api.ts, components/builder-web/app/events/events-saas/events-saas.component.ts
Case 1: When the date filter changed on the Events (SaaS), results in console errors.
Fixes the dropdown change on the Events (SaaS) page.
Case 2: When the user logged in and tried to access Events (SaaS), results in console errors.
This is occurring because the user is logged into a different environment (acceptance/on-prem) and the auth same token is used for the production instance. Currently, we can only show events that are publicly accessible. 
We need to handle the login case separately. Below are the possible options:
1. Use separate auth credentials when accessing Events (SaaS) - may not be the right choice.
2. Support multi-login (on-prem and SaaS), use the token based on the context.
3. Any other options?
=> Event log fixes on the SaaS events page

terraform/variables.tf
closes #1614 
The variable should contain the actual value and not the file path of the public key. Running `make init` in the `cloud-environments` repo will pull the value from vault and set this variable.
=> correct description of connection_public_key tf variable

components/builder-api/habitat/default.toml, components/builder-api/src/config.rs, components/builder-api/src/server/services/github.rs
Code to suppress autobuild using via cli command "hab config apply"
=> suppress autobuild in builder api

components/builder-api-proxy/habitat/config/nginx.conf
fixes #1663 
I noticed that the upload stream was hanging after a couple GB. Eventually the connection on the client or the nginx gateway would timeout which would close the stream leaving an incomplete temp file and ultimately resulting in a `premature eof` error while extracting the archive. I also observed that `builder-api` did not begin to read the stream until the client had sent the entire file. That seemed odd since the http 1.1 chunked encoding should allow for proper streaming. 
I eventually tried bypassing nginx and sending the upload strictly to builder-api. This resulted in a successful upload as well as proper streaming behavior.
I later discovered the [`proxy_request_buffering` setting in nginx](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering …
=> turn off proxy request buffering to allow for better upload streaming and fix super large uploads

components/builder-jobsrv/src/server/log_ingester.rs
While investigating another unrelated issue, I notices that the jobsrvr would panic when uploading build logs to S3 with:
```
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
The job server would restart and the log still made its way to S3 so this error would go largely unnoticed until we got any decent build load which would cause the job server to crash at the end of every build.
This probably came up some time in the last 6 months during a tokio upgrade.
I built and tested the binary on acceptance and validated that the panic does not occur with this fix.
=> spawn log ingester thread in a tokio runtime to fix jobsrv panic

Makefile, build.sh
Signed-off-by: pozsgaic <pozsgai@progress.com>
Added a build script and modified the Makefile to enable building from Makefile:
--   sudo make build-builder-api
Or directly using the build script
--  sudo ./build.sh builder-api
=> add build script and update Makefile

components/builder-api/src/server/resources/pkgs.rs, test/builder-api/src/packages.js
We can get the package metadata with the /latest route with the omission of the version and or release options.
This PR fixes getting package HART size as part of package metadata in those situations.
It also updates a few functional tests to check the size attribute in the response JSON.
=> Fix size computing for packages with /latest route

components/builder-api/doc/api.raml
Fix issue in format of original file
Manual convert to 1.0
Backfill missing content that is implemented in code
=> api raml update

components/builder-api/src/server/resources/pkgs.rs
When we do not supply the target parameter for a package, it will default to X86_64_Linux. However, if the input ident is fully qualified, the builder determines the correct target when finding a package.
Sample route:
<builder-url>/v1/depot/pkgs/neurosis/testapp/0.1.4/20181115124506
After identifying the package, the target property from the newly found package should be used instead of the default.
=> Fix picking the pkg target for fully qualified ident

Cargo.lock, components/builder-api/Cargo.toml, components/builder-api/src/server/authorize.rs, components/builder-api/src/server/framework/middleware.rs, components/builder-api/src/server/mod.rs, components/builder-api/src/server/resources/channels.rs, components/builder-api/src/server/resources/jobs.rs, components/builder-api/src/server/resources/origins.rs, components/builder-api/src/server/resources/pkgs.rs, components/builder-api/src/server/resources/profile.rs, components/builder-api/src/server/resources/projects.rs, components/builder-api/src/server/resources/settings.rs, components/builder-api/src/server/resources/user.rs, components/builder-core/src/access_token.rs, components/builder-jobsrv/Cargo.toml, components/builder-jobsrv/src/server/mod.rs
This PR updates the actix-web crate to the latest (4.0.1).
Below are the steps followed to update the crate:
- Update actix-web to 4.0.1 in Cargo.toml (builder-api, and builder-jobsrv)
- run **cargo update -p actix-web**
- Manually update the crate versions in the package section of Cargo.lock (This might happen when the update command moves the crates to a lower version)
- Address the API/other breaking changes one after the other.
Tips:
1. Observe the failed crates, and check the crate versions in Cargo.lock to fix them. For example, for the error below, we need to check the package section with the name **habitat_builder_api**.
Caused by:
process didn't exit successfully: `rustc --crate-name habitat_builder_api --ed
=> Update actix-web crate

components/builder-web/app/package/package/package.component.html
If we navigate to the 'Build Jobs' or 'Settings' page on the package page, the corresponding tab is not active. This change will fix the tab activation.
This 'routerLinkActiveOptions' was removed for the versions tab to be active even after selecting a particular version from the list. The same is true for Build Jobs.
We will investigate how to handle the child's routes to be active later.
=> Fix activating 'Build Jobs' on package page

components/builder-web/app/package/package-versions/package-versions.component.ts
The logic has a flaw in computing the expanded nodes. We are creating a list with new objects each time, and this keeps on updating the version nodes on hover. It prevents the other functionality to not working.
We should reuse the pkg object rather than create a new one each time a rerender is required.
=> Fix copy to clipboard functionality

components/builder-api-proxy/habitat/config/nginx.conf
This is really to compensate for recent changes in the automate oauth flow. If using a modern automate for oauth, the CORS headers need to be set. This introduces a new config setting: `allow_oauth_origin`. If a user is using automate as an oauth provider, they can set this setting to the domain of their automate server: `https://my.automate.server.com`.
We will update the `install.sh` of the on-prem builder to do this automatically.
=> allow an Access-Control-Allow-Origin header to be set for certain oauth providers like automate

components/builder-api-proxy/habitat/config/index.html
Updated the Google Tag Manager code as per the recommendations. Have used the same parameter 'cfg.hosted' to load GTM tags, if its set, so that GTM tags are only run if it is a SAS deployment.
https://chefio.atlassian.net/browse/CHEF-6083
https://chefio.atlassian.net/browse/CHEF-8154
PS: I was not able to test these changes on local.
=> CHEF-6083: Updated the GTM code as per the recommendation.

components/builder-api-proxy/habitat/config/index.html, components/builder-web/index.html
Added the testing version of One Trust script in both development file(components/builder-web/index.html) and in deployment file(components/builder-api-proxy/habitat/config/index.html) along with the required GTM changes.
Have used the same parameter 'cfg.hosted' to load One Trust and GTM tags, if its set, so that these scripts are only run if it is a SAS deployment. 
We will need to host these changes in our acceptance environment ( https://bldr.acceptance.habitat.sh/#/pkgs/core ) and share it with relevant stakeholders for testing. Once the testing is completed, team will share the production version of One Trust script which we will need to update in our code base.
https://chefio.atlassian.net/browse/CHEF-6081
PS: I was not able to test the deployment file changes on local.
=> CHEF-6081: Added testing version of OneTrust script.

components/builder-api-proxy/habitat/config/index.html
Added the production version of One Trust script in deployment file(components/builder-api-proxy/habitat/config/index.html). Have used the same parameter 'cfg.hosted' to load One Trust and GTM tags, if its set, so that these scripts are only run if it is a SAS deployment.
We will need to host these changes in our acceptance environment ( https://bldr.acceptance.habitat.sh/#/pkgs/core ) and share it with relevant stakeholders for testing. Once the testing is completed, we can do the deployment in the production environment.
https://chefio.atlassian.net/browse/CHEF-6081
PS: I was not able to test the deployment file changes on local.
=> CHEF-6081: Added production version of OneTrust script.

components/builder-api-proxy/habitat/plan.sh
Removed the unneeded package `phantomjs` from build dependencies.
=> remove phantomjs

Cargo.lock
=> Fixed OAuth error in github login for builder

components/builder-api/src/server/framework/middleware.rs, components/builder-core/src/access_token.rs
This add some tracing code that helped to troubleshoot and identify the underlying cause of 401s authenticating to builder with generated user tokens.
From the comments:
// Prior to the chronos update 4 months ago this is the max timestamp used for user tokens
// We have succesfully parsed this value via the call to Utc.timestamp_opt above for years
// Yesterday (2024-09-12), this value became out of bounds and yields a 401 trying to auth
// Right now we have no idea why and some day perhaps we will all laugh around the fire as 
// we remember this bug and how trivial it truly was. Today no one is laughing. I hope there
// will be a better fix than this in the near future but this will allow the many keys currently
// out in the wild with this value to authenticate.
That sadly is close to …
=>  allow older user tokens to succesfully authenticate

components/builder-minio/README.md, components/builder-minio/habitat/config/hook-helper.sh, components/builder-minio/habitat/hooks/post-run, components/builder-minio/habitat/hooks/reconfigure, components/builder-minio/habitat/hooks/run, components/builder-minio/habitat/plan.sh
Needed to to trigger the github build action for minio and realized it was an opportunity to take these actions.
=> Clean up via shellcheck, shfmt, and markdownlint

.github/actions/hab-pkg-build-and-upload-linux/action.yaml
Set the HAB_REFRESH_CHANNEL to LTS-2024 to fix the failing workflow.
=> Fixes adhoc workflow

components/builder-api-proxy/habitat/config/habitat.conf.js
The rendered JSON has an error because the channel name is not included in quotes.
=> include quotes in config

CODE_OF_CONDUCT.md, DEVELOPING.md, MAINTAINERS.md, ON_CALL.md, components/builder-web/README.md, docs/Migrations.md, tools/bldr_toml_create/README.md, tools/hab-channel-list-pkgs/README.md, tools/hab_token/Usage.md, tools/project_create/README.md, tools/ssh_helpers/Usage.md
This set of documents for review was selected via the following command
```shell
code $(find -name "*md" -! -path "*test*" -! -path "*node_modules*" -! -path "*.github*" -! -path "*target*" | grep -v -e builder-jobsrv -e builder-graph -e builder-protocol -e CHANGELOG.md | xargs)
```
The documents were then review with markdown lint and the code spell checker extensions active. Ultimately the spell checker just detected technical things like "passwordless" and different command line programs that didn't need to be corrected.
NOTE: This PR isn't about correcting content. That will be a future PR.
=> Address Markdown lint errors

.expeditor/verify.pipeline.yml, Makefile
The fmt targets of the Makefile were inconsistent with our expeditor pipeline.  The verify expeditor pipeline directly called the script support/ci/rustfmt.sh while the Makefile had its own rule where cargo fmt was called within each component directory.  Also, a lot of the .PHONY targets that should have been fmt-SOMETHING where still clean-SOMETHING from a copy and paste error.
In this PR all fmt targets are removed from the Makefile except for fmt which now calls the support/ci/rustfmt.sh directly.
Also, the verify pipeline now calls make fmt as opposed to calling the script directly. This mirrors the practice whereby clippy is executed via make lint.
=> Aligns rustfmt between Makefile and verify pipeline

components/builder-api-proxy/habitat/config/habitat.conf.js, components/builder-api-proxy/habitat/default.toml, components/builder-api/habitat/default.toml, components/builder-api/src/config.rs, components/builder-api/src/server/resources/origins.rs, components/builder-web/app/origin/origins-page/_origins-page.component.scss, components/builder-web/app/origin/origins-page/origins-page.component.html, components/builder-web/app/origin/origins-page/origins-page.component.ts, components/builder-web/app/package/package-latest/package-latest.component.html, components/builder-web/app/sign-in-page/sign-in-page.component.html, components/builder-web/habitat.conf.sample.js, support/builder/config.sh, test/builder-api/src/origins.js
This allows a builder instance to configure a list of usernames in the builder-api user.toml:
```
[api]
allowed_users_for_origin_create = ['bobo', 'mystique', 'wesker', 'lkennedy']
```
If this list is specified and not empty, a user MUST be in this list in order to create any origin.
=> ability to restrict origin creation to authorized users

components/builder-api/src/server/migrations.rs, components/builder-api/src/server/migrations/encrypt_secret_keys.rs, components/builder-api/src/server/mod.rs, components/builder-core/src/crypto.rs, components/builder-core/src/keys.rs
The Builder API service requires a user key named `bldr`, which is created with the following command:
```sh
hab user key generate bldr
```
The bldr keys are then used to encrypt and decrypt authentication tokens and origin secret keys. These keys are always specified through the `key_path` configuration in `config.toml`.
The command generates two keys, as shown below:
- bldr-20250324065740.pub (public key)
- bldr-20250324065740.box.key (private key)
Although both the public and private keys are generated, only the private key (bldr-20250324065740.box.key) is used during the service lifecycle. The public key is never used, and only the private key is required for the Builder API service to function.
This PR adds support for supplying the secret key via the new environment variable …
=> Support loading builder encryption key from env

.gitignore, components/builder-db/src/migrations/2025-04-24-000001_hide_origins/down.sql, components/builder-db/src/migrations/2025-04-24-000001_hide_origins/up.sql, components/builder-db/src/models/package.rs, components/builder-db/src/models/settings.rs, components/builder-db/src/schema/package.rs, components/builder-db/src/schema/settings.rs
This hides origins and packages with `hidden=true` in ui, cli, and api. I think this captures all the key scenarios. There may be some edge cases like listing the keys of a hidden origin is possible. But adding yet another hidden column or adding a join did not seem worth it.
=> soft delete origins

Cargo.lock, components/artifactory-client/Cargo.toml, components/builder-api/Cargo.toml, components/builder-core/Cargo.toml, components/builder-db/Cargo.toml, components/builder-protocol/Cargo.toml, components/github-api-client/Cargo.toml, components/oauth-client/Cargo.toml
I found a couple of tools (machete, shears) when I was shrinking the builder code base that can be use to find unnecessary dependencies in a rust project. I took another look at those and decided they were fairly close and chose machete over shears. They seem roughly equivalent and I think that if we ever wanted to switch it should be rather easy.
Reasons that dependencies were removed include
- The dependency was already available as a transitive dependency
- The shrinking of the code base eliminated the need for the dependency
Serde was added to the ignore list because the parent crate is needed for the macros. Interestingly shears might be able to detect that in the future but that feature doesn’t seem to be done baking just yet and I liked the --with-metadata option in machete
=> Taking cargo machete to our crates

.expeditor/templates/studiorc, support/builder/config.sh
While reviewing a build in buildkite I notice several messages about 'hab sup status' commands being deprecated in favor of 'hab svc status'.  This PR updates to using 'hab svc status'.
=> Updates deprecated 'hab sup status' commands to 'hab svc status' calls

components/builder-api/habitat/default.toml
We will manage the channels for license restrictions via user.toml for SAAS. In default.toml they should be empty so that on-prem instances are not impacted by license restrictions.
=> remove restricted channel settings in default toml

.buildkite/hooks/pre-command, .expeditor/builder_seed.toml, .expeditor/scripts/verify/builder-api-functional.sh, .expeditor/templates/studiorc, .expeditor/verify.pipeline.yml
- Works around a bug in hab 2.0 for .expeditor/scripts/verify/builder-api-functional.sh by
- now explicitly installing hab-studio, hab-sup, and hab-launcher as a workaround
- exporting HAB_AUTH_TOKEN as appropriate for chef-oss pipelines so that it's available
- Does a s/core/chef/ in .expeditor/builder_seed.toml
- Removes #! and adds comment to .expeditor/templates/studiorc
- this cleans up the concatenation of .expeditor/templates/studiorc and helps makes that a bit more explicit
- Removes some comments from there verify piepline that were "sectioning" as well as one that is ~base knowledge for hab team but wasn't mirrored in other pipelines so why have this extra bit.
- makes a white space change in the verify pipeline to eliminate extra indentation in the yaml comb structure.
- I just …
=> Fixes verify pipeline and a bit of hygeine

components/builder-web/app/actions/users.ts, components/builder-web/app/events/events-routing.module.ts, components/builder-web/app/origin/origin-page/origin-page-routing.module.ts, components/builder-web/app/package/package-routing.module.ts, components/builder-web/app/reducers/users.ts, components/builder-web/app/routes.ts, components/builder-web/app/search/search-routing.module.ts, components/builder-web/app/shared/guards/license-required.guard.ts, components/builder-web/app/shared/guards/signed-in.guard.ts
1) On-prem (non SaaS) users may not be signed or have valid license to access any routes.
2) SaaS users with valid license are allowed to access all routes after signing in and are by default moved to /origins page.
3) SaaS users without license get 404 code and after signed-in has to stay on /profile page till license is provided.
4) SaaS users with expired license should also stay on /profile page after sign-in till valid license is provided.
5) On refresh the users should remain on same page, if still signed-in.
https://progresssoftware.atlassian.net/browse/CHEF-23586
On-prem (hosted=false)
https://github.com/user-attachments/assets/bfd6a78b-675d-427e-ab85-d897f4bb4963
SaaS (hosted=true)
https://github.com/user-attachments/assets/2190eec6-082a-47d0-acbe-5c15754c04e9
=> CHEF-23586: Update license handling for SaaS users

components/builder-api/src/server/resources/authenticate.rs
If an oauth provider like github returns an error due to some obsure downstream issue with token provisioning, these errors are lost to us. This should help us debug scenarios like the one we had with a customer who had azureAD integrated as a SSO provider for their github accounts that was not configured to provide tokens.
=> do not swallow oauth provider errors. let their light shine
